export const COURSE_GROUPS = [
  {
    id: 'data-ai',
    label: 'Data & AI',
    icon: 'chart-bar',
    color: '#7c3aed',
    iconBg: 'rgba(167,139,250,0.15)',
    slugs: ['data-analytics-bi', 'data-engineering', 'quantum-computing'],
  },
  {
    id: 'cloud-devops',
    label: 'Cloud & DevOps',
    icon: 'cloud',
    color: '#0f766e',
    iconBg: 'rgba(45,212,191,0.15)',
    slugs: ['cloud-computing', 'devops-multi-cloud', 'cyber-security'],
  },
  {
    id: 'programming',
    label: 'Programming',
    icon: 'code',
    color: '#7c3aed',
    iconBg: 'rgba(167,139,250,0.15)',
    slugs: ['programming-full-stack', 'software-testing-os'],
  },
  {
    id: 'business',
    label: 'Business & Enterprise',
    icon: 'building',
    color: '#9f1239',
    iconBg: 'rgba(251,113,133,0.15)',
    slugs: ['erp-crm-enterprise-tools', 'human-resource', 'medical-coding'],
  },
  {
    id: 'design-career',
    label: 'Design & Career',
    icon: 'palette',
    color: '#be185d',
    iconBg: 'rgba(244,114,182,0.15)',
    slugs: ['digital-design', 'professional-soft-skills'],
  },
]

export const CATEGORY_ACCENTS: Record<string, string> = {
  'data-analytics-bi':          'linear-gradient(90deg,#7c3aed,#a78bfa)',
  'data-engineering':           'linear-gradient(90deg,#0369a1,#38bdf8)',
  'quantum-computing':          'linear-gradient(90deg,#0e7490,#67e8f9)',
  'cloud-computing':            'linear-gradient(90deg,#1e40af,#60a5fa)',
  'devops-multi-cloud':         'linear-gradient(90deg,#0f766e,#2dd4bf)',
  'cyber-security':             'linear-gradient(90deg,#065f46,#34d399)',
  'programming-full-stack':     'linear-gradient(90deg,#7c3aed,#a78bfa)',
  'software-testing-os':        'linear-gradient(90deg,#1d4ed8,#93c5fd)',
  'erp-crm-enterprise-tools':   'linear-gradient(90deg,#9f1239,#fb7185)',
  'human-resource':             'linear-gradient(90deg,#7c3aed,#c4b5fd)',
  'medical-coding':             'linear-gradient(90deg,#166534,#86efac)',
  'digital-design':             'linear-gradient(90deg,#be185d,#f472b6)',
  'professional-soft-skills':   'linear-gradient(90deg,#92400e,#fcd34d)',
}

export const CATEGORY_ICONS: Record<string, string> = {
  'data-analytics-bi':          '📊',
  'data-engineering':           '🔧',
  'quantum-computing':          '⚛️',
  'cloud-computing':            '☁️',
  'devops-multi-cloud':         '⚙️',
  'cyber-security':             '🛡️',
  'programming-full-stack':     '💻',
  'software-testing-os':        '🧪',
  'erp-crm-enterprise-tools':   '🏢',
  'human-resource':             '👥',
  'medical-coding':             '🏥',
  'digital-design':             '🎨',
  'professional-soft-skills':   '🤝',
}
