import type { CourseCardProps } from '@/components/CourseCard'

export interface CourseItem {
  name: string;
  duration: string;
  level: string;
  highlights: string[];
  fee?: string;
}

export interface CourseCategoryData {
  name: string;
  slug: string;
  emoji: string;
  tagline: string;
  description: string;
  courses: CourseItem[];
  whyLearn: string[];
  tools: string[];
  careers: string[];
  faqs: { q: string; a: string }[];
}

const cloudCourses: CourseCategoryData = {
  name: 'Cloud Computing',
  slug: 'cloud-computing',
  emoji: '☁️',
  tagline: 'Master AWS, Azure & Google Cloud',
  description: 'Become a certified cloud professional with hands-on training in AWS, Microsoft Azure, and Google Cloud Platform. Our industry-led curriculum prepares you for real-world cloud roles with practical labs and globally recognized certifications.',
  courses: [
    { name: 'AWS Cloud Training', duration: '2–3 Months', level: 'Beginner to Advanced', highlights: ['EC2, S3, RDS, Lambda', 'VPC & Security Groups', 'AWS Solutions Architect', 'Hands-on Labs'], fee: '₹ 15,000–25,000' },
    { name: 'Microsoft Azure Training', duration: '2–3 Months', level: 'Beginner to Advanced', highlights: ['Azure Virtual Machines', 'Azure Active Directory', 'Azure DevOps', 'AZ-900 / AZ-104 Certification'], fee: '₹ 15,000–25,000' },
    { name: 'Google Cloud Training', duration: '2 Months', level: 'Intermediate', highlights: ['GCP Core Services', 'BigQuery & Dataflow', 'Kubernetes Engine', 'Associate Cloud Engineer'], fee: '₹ 12,000–20,000' },
    { name: 'Multi-Cloud Engineer', duration: '4 Months', level: 'Advanced', highlights: ['AWS + Azure + GCP', 'Cloud Migration', 'Cost Optimization', 'Multi-Cloud Architecture'], fee: '₹ 25,000–40,000' },
    { name: 'Cloud Architecture', duration: '3 Months', level: 'Advanced', highlights: ['Solution Design', 'High Availability', 'DR & Backup Strategies', 'Cost Management'], fee: '₹ 20,000–35,000' },
  ],
  whyLearn: ['Highest paying IT domain globally', 'Cloud jobs growing 30%+ year over year', 'Remote work opportunities worldwide', 'Industry certifications from AWS, Microsoft, Google'],
  tools: ['AWS Console', 'Azure Portal', 'Google Cloud Console', 'Terraform', 'CloudFormation', 'Ansible'],
  careers: ['Cloud Engineer', 'Solutions Architect', 'Cloud Administrator', 'DevOps Engineer', 'Cloud Consultant'],
  faqs: [
    { q: 'Do I need prior IT experience for cloud courses?', a: 'Our beginner batches start from scratch. Basic computer knowledge is sufficient.' },
    { q: 'Which cloud certification should I start with?', a: 'AWS Solutions Architect Associate or Azure AZ-900 are ideal starting points.' },
    { q: 'Are lab sessions included?', a: 'Yes, all cloud courses include hands-on labs on real cloud environments.' },
  ],
};

const devopsCourses: CourseCategoryData = {
  name: 'DevOps & Multi-Cloud',
  slug: 'devops-multi-cloud',
  emoji: '⚙️',
  tagline: 'Master CI/CD, Docker & Kubernetes',
  description: 'Become a DevOps Engineer with comprehensive training in CI/CD pipelines, containerization, infrastructure automation and multi-cloud deployments. Learn the tools and practices used by top tech companies worldwide.',
  courses: [
    { name: 'AWS DevOps', duration: '3 Months', level: 'Intermediate', highlights: ['CodePipeline & CodeDeploy', 'CloudFormation', 'ECS & EKS', 'Monitoring with CloudWatch'] },
    { name: 'Azure DevOps', duration: '3 Months', level: 'Intermediate', highlights: ['Azure Pipelines', 'Boards & Repos', 'Azure Kubernetes Service', 'ARM Templates'] },
    { name: 'Docker & Kubernetes', duration: '2 Months', level: 'Intermediate', highlights: ['Container Fundamentals', 'Docker Compose', 'Kubernetes Orchestration', 'Helm Charts'] },
    { name: 'Terraform & IaC', duration: '1.5 Months', level: 'Advanced', highlights: ['Infrastructure as Code', 'Multi-cloud Provisioning', 'State Management', 'Modules & Workspaces'] },
    { name: 'Jenkins & CI/CD', duration: '1 Month', level: 'Intermediate', highlights: ['Pipeline as Code', 'Integration with Git', 'Build Automation', 'Deployment Strategies'] },
    { name: 'Full DevOps Bootcamp', duration: '5 Months', level: 'Beginner to Advanced', highlights: ['Git & GitHub', 'Linux Admin', 'Docker + K8s', 'AWS/Azure + Jenkins + Terraform'] },
  ],
  whyLearn: ['DevOps engineers earn 40–60% more than traditional developers', 'Fastest-growing engineering role in 2024–25', 'Automation skills are universally in demand', 'Bridge between dev and ops teams'],
  tools: ['Jenkins', 'Docker', 'Kubernetes', 'Terraform', 'Ansible', 'Git', 'SonarQube', 'Prometheus', 'Grafana'],
  careers: ['DevOps Engineer', 'Site Reliability Engineer', 'Cloud Infrastructure Engineer', 'Platform Engineer', 'Release Manager'],
  faqs: [
    { q: 'Should I learn Linux before DevOps?', a: 'Yes, basic Linux knowledge is recommended. We cover Linux essentials in our bootcamp.' },
    { q: 'Is Docker and Kubernetes mandatory?', a: 'Absolutely — they are the backbone of modern DevOps. All our programs include them.' },
    { q: 'What certifications can I get?', a: 'AWS DevOps Professional, Azure DevOps Expert, CKA (Kubernetes) are popular choices.' },
  ],
};

const programmingCourses: CourseCategoryData = {
  name: 'Programming & Full Stack Development',
  slug: 'programming-full-stack',
  emoji: '💻',
  tagline: 'Build Full-Stack Web Applications',
  description: 'Learn to build end-to-end web applications with Java, Python, React, Node.js and more. Our full-stack programs cover both front-end and back-end development with real-world project experience.',
  courses: [
    { name: 'Java Full Stack', duration: '5 Months', level: 'Beginner to Advanced', highlights: ['Core Java & Advanced Java', 'Spring Boot & Microservices', 'React.js Frontend', 'MySQL & MongoDB'] },
    { name: 'Python Full Stack', duration: '4 Months', level: 'Beginner to Advanced', highlights: ['Python Fundamentals', 'Django / Flask', 'React.js', 'REST APIs & Databases'] },
    { name: 'MERN Stack', duration: '4 Months', level: 'Intermediate', highlights: ['MongoDB', 'Express.js', 'React.js', 'Node.js'] },
    { name: 'React.js', duration: '2 Months', level: 'Intermediate', highlights: ['Component Architecture', 'React Hooks', 'Redux', 'API Integration'] },
    { name: 'Core Java', duration: '2 Months', level: 'Beginner', highlights: ['OOPs Concepts', 'Collections & Generics', 'Exception Handling', 'JDBC'] },
  ],
  whyLearn: ['Web development is the backbone of every digital business', 'High demand for full-stack developers worldwide', 'Ability to build complete products independently', 'Freelancing and startup opportunities'],
  tools: ['VS Code', 'IntelliJ IDEA', 'Git & GitHub', 'Postman', 'MySQL Workbench', 'MongoDB Compass', 'npm/yarn'],
  careers: ['Full Stack Developer', 'Java Developer', 'Python Developer', 'React Developer', 'Backend Engineer', 'Software Engineer'],
  faqs: [
    { q: 'Which language should I start with — Java or Python?', a: 'Both are excellent. Java is widely used in enterprise; Python is popular in AI/data. Our trainers help you decide.' },
    { q: 'Will I build real projects?', a: 'Yes — every course includes 2–3 real-world projects that you can showcase in your portfolio.' },
    { q: 'Is this course suitable for non-IT graduates?', a: 'Absolutely. Many of our successful students are from non-IT backgrounds.' },
  ],
};

const dataEngCourses: CourseCategoryData = {
  name: 'Data Engineering',
  slug: 'data-engineering',
  emoji: '🔧',
  tagline: 'Build Scalable Data Pipelines',
  description: 'Master the tools and technologies used to build, maintain and optimize large-scale data infrastructure. Learn Azure Data Engineering, Spark, Hadoop, and ETL pipeline development.',
  courses: [
    { name: 'Azure Data Engineer', duration: '3 Months', level: 'Intermediate', highlights: ['Azure Data Factory', 'Azure Synapse Analytics', 'Databricks', 'DP-203 Certification'] },
    { name: 'Apache Spark & PySpark', duration: '2 Months', level: 'Intermediate', highlights: ['Spark Architecture', 'PySpark DataFrames', 'Streaming', 'Spark ML'] },
    { name: 'Hadoop Ecosystem', duration: '2 Months', level: 'Intermediate', highlights: ['HDFS & MapReduce', 'Hive & Pig', 'HBase', 'Sqoop & Flume'] },
    { name: 'ETL & Data Pipelines', duration: '1.5 Months', level: 'Intermediate', highlights: ['ETL Design Patterns', 'SSIS & Informatica', 'Airflow', 'Pipeline Orchestration'] },
  ],
  whyLearn: ['Data engineering is among the highest-paid IT roles', 'Every company needs engineers to manage data at scale', 'Bridge between raw data and insights', 'Growing demand in fintech, healthcare, and e-commerce'],
  tools: ['Azure Data Factory', 'Databricks', 'Apache Spark', 'Hadoop', 'Airflow', 'dbt', 'Kafka'],
  careers: ['Data Engineer', 'Azure Data Engineer', 'Big Data Engineer', 'ETL Developer', 'Data Pipeline Engineer'],
  faqs: [
    { q: 'Do I need to know Python for data engineering?', a: 'Yes, basic Python is essential. We include a Python primer in the course.' },
    { q: 'Is DP-203 covered in the Azure Data Engineer course?', a: 'Yes, the curriculum is aligned with the DP-203 exam objectives.' },
  ],
};

const cyberCourses: CourseCategoryData = {
  name: 'Cyber Security & Networking',
  slug: 'cyber-security',
  emoji: '🔒',
  tagline: 'Become a Certified Security Expert',
  description: 'Learn ethical hacking, penetration testing, SOC analysis and network security with hands-on labs. Gain the skills needed to protect organizations from modern cyber threats.',
  courses: [
    { name: 'Ethical Hacking & CEH', duration: '3 Months', level: 'Intermediate', highlights: ['Penetration Testing', 'Network Scanning', 'Vulnerability Assessment', 'CEH Certification'] },
    { name: 'SOC Analyst', duration: '2 Months', level: 'Beginner to Intermediate', highlights: ['SIEM Tools', 'Incident Response', 'Threat Intelligence', 'Log Analysis'] },
    { name: 'CCNA Networking', duration: '2 Months', level: 'Beginner', highlights: ['Network Fundamentals', 'Routing & Switching', 'VLANs', 'CCNA Certification'] },
    { name: 'Network Security', duration: '2 Months', level: 'Intermediate', highlights: ['Firewall Configuration', 'VPN Setup', 'IDS/IPS', 'Security Policies'] },
  ],
  whyLearn: ['Cyber attacks are increasing — security talent is scarce', 'High-paying roles in banking, government, and IT', 'Work as a freelance penetration tester', 'Globally recognized certifications'],
  tools: ['Kali Linux', 'Metasploit', 'Wireshark', 'Nmap', 'Splunk', 'Burp Suite', 'Nessus'],
  careers: ['Ethical Hacker', 'Penetration Tester', 'SOC Analyst', 'Network Security Engineer', 'CISO', 'Security Consultant'],
  faqs: [
    { q: 'Is ethical hacking legal?', a: 'Ethical hacking is completely legal when done with proper authorization. Our course covers legal frameworks too.' },
    { q: 'What are the prerequisites for cyber security?', a: 'Basic networking and OS knowledge. We provide foundational modules in the course.' },
  ],
};

const erpCourses: CourseCategoryData = {
  name: 'ERP, CRM & Enterprise Tools',
  slug: 'erp-crm-enterprise-tools',
  emoji: '🏢',
  tagline: 'Master SAP, Salesforce & Oracle',
  description: 'Learn industry-standard enterprise platforms used by Fortune 500 companies. Our ERP/CRM training covers SAP, Salesforce, Oracle Fusion HCM and business process automation.',
  courses: [
    { name: 'SAP FICO', duration: '3 Months', level: 'Beginner to Advanced', highlights: ['Financial Accounting', 'Controlling Module', 'SAP S/4HANA', 'Real-time Configuration'] },
    { name: 'Salesforce CRM', duration: '2 Months', level: 'Beginner', highlights: ['Salesforce Admin', 'Sales Cloud', 'Service Cloud', 'Salesforce Certification'] },
    { name: 'Oracle Fusion HCM', duration: '2.5 Months', level: 'Intermediate', highlights: ['HR Management', 'Payroll & Benefits', 'Workforce Management', 'Oracle Cloud'] },
    { name: 'SAP HR', duration: '2 Months', level: 'Beginner to Intermediate', highlights: ['Personnel Management', 'Payroll in SAP', 'Org Management', 'Time Management'] },
  ],
  whyLearn: ['SAP & Salesforce skills command premium salaries', 'Enterprise tools are used in 90% of large companies', 'Limited talent pool means better career opportunities', 'Remote and consulting opportunities worldwide'],
  tools: ['SAP S/4HANA', 'Salesforce Lightning', 'Oracle HCM Cloud', 'MS Dynamics', 'ServiceNow'],
  careers: ['SAP Consultant', 'Salesforce Admin/Developer', 'Oracle HCM Consultant', 'ERP Analyst', 'Business Analyst'],
  faqs: [
    { q: 'Do I need a finance background for SAP FICO?', a: 'Basic accounting knowledge helps but is not mandatory. We cover the basics in our course.' },
    { q: 'Can I get a job after Salesforce training?', a: 'Yes, Salesforce certified professionals have very high placement rates in our alumni network.' },
  ],
};

const testingCourses: CourseCategoryData = {
  name: 'Software Testing & OS',
  slug: 'software-testing-os',
  emoji: '🧪',
  tagline: 'QA, Automation & Linux Administration',
  description: 'Master software quality assurance, test automation with Selenium, and Linux system administration. Build the skills to ensure software quality and manage enterprise Linux environments.',
  courses: [
    { name: 'Manual Testing', duration: '1.5 Months', level: 'Beginner', highlights: ['SDLC & STLC', 'Test Case Design', 'Bug Reporting', 'Agile/Scrum'] },
    { name: 'Selenium Automation', duration: '2 Months', level: 'Intermediate', highlights: ['Selenium WebDriver', 'Java/Python with Selenium', 'TestNG / PyTest', 'CI/CD Integration'] },
    { name: 'Linux Administration', duration: '2 Months', level: 'Beginner to Intermediate', highlights: ['Linux Commands', 'Shell Scripting', 'User Management', 'Server Administration'] },
    { name: 'API Testing', duration: '1 Month', level: 'Intermediate', highlights: ['REST & SOAP APIs', 'Postman', 'REST Assured', 'JSON/XML Parsing'] },
  ],
  whyLearn: ['QA engineers are in high demand at every software company', 'Linux is fundamental for cloud and DevOps roles', 'Automation testing multiplies your productivity', 'Lower entry barrier compared to development roles'],
  tools: ['Selenium', 'JIRA', 'TestNG', 'Postman', 'Jenkins', 'Linux Terminal', 'Git', 'Maven'],
  careers: ['QA Engineer', 'Automation Test Engineer', 'Linux System Admin', 'SDET', 'DevOps Engineer'],
  faqs: [
    { q: 'Is coding required for automation testing?', a: 'Basic Java or Python is needed. We include a programming primer in the automation course.' },
    { q: 'Is Linux training useful for non-developers?', a: 'Absolutely — it is essential for cloud, networking, and DevOps careers.' },
  ],
};

const digitalCourses: CourseCategoryData = {
  name: 'Digital & Design',
  slug: 'digital-design',
  emoji: '🎨',
  tagline: 'Digital Marketing & UI/UX Design',
  description: 'Learn digital marketing, SEO, social media management, and UI/UX design. Build skills to grow businesses online and create beautiful user experiences.',
  courses: [
    { name: 'Digital Marketing', duration: '2.5 Months', level: 'Beginner', highlights: ['SEO & Google Ads', 'Social Media Marketing', 'Email Marketing', 'Google Analytics'] },
    { name: 'UI/UX Design', duration: '2 Months', level: 'Beginner', highlights: ['Wireframing & Prototyping', 'Figma & Adobe XD', 'User Research', 'Design Systems'] },
    { name: 'Graphic Design', duration: '1.5 Months', level: 'Beginner', highlights: ['Adobe Photoshop', 'Illustrator', 'Canva', 'Brand Identity'] },
    { name: 'SEO & Content Marketing', duration: '1.5 Months', level: 'Beginner to Intermediate', highlights: ['On-page & Off-page SEO', 'Content Strategy', 'Link Building', 'SEO Audits'] },
  ],
  whyLearn: ['Every business needs a digital presence', 'Freelancing opportunities with global clients', 'Combine creativity with technology', 'Low investment, high return career choice'],
  tools: ['Google Ads', 'Meta Ads Manager', 'Figma', 'Adobe Creative Suite', 'Semrush', 'Ahrefs', 'Canva'],
  careers: ['Digital Marketing Executive', 'SEO Specialist', 'UI/UX Designer', 'Social Media Manager', 'Content Strategist'],
  faqs: [
    { q: 'Is a design degree required for UI/UX?', a: 'No. Anyone with an eye for aesthetics and willingness to learn can become a UI/UX designer.' },
    { q: 'Can I do freelancing after digital marketing training?', a: 'Yes, many of our students work as freelancers or start their own agencies.' },
  ],
};

const softSkillsCourses: CourseCategoryData = {
  name: 'Professional & Soft Skills',
  slug: 'professional-soft-skills',
  emoji: '🎯',
  tagline: 'Communication, MS Office & English',
  description: 'Build the professional skills that complement your technical expertise. Our courses in MS Office, Spoken English, and Communication Skills prepare you for workplace success.',
  courses: [
    { name: 'MS Office (Excel, Word, PPT)', duration: '1.5 Months', level: 'Beginner', highlights: ['Excel Formulas & Pivot Tables', 'Word Processing', 'PowerPoint Presentations', 'Excel Macros & VBA'] },
    { name: 'Spoken English', duration: '2 Months', level: 'Beginner', highlights: ['Grammar & Pronunciation', 'Business Communication', 'Group Discussion', 'Interview Preparation'] },
    { name: 'Communication Skills', duration: '1 Month', level: 'Beginner', highlights: ['Public Speaking', 'Business Writing', 'Presentation Skills', 'Body Language'] },
    { name: 'Tally ERP', duration: '1.5 Months', level: 'Beginner', highlights: ['GST Accounting', 'Payroll Management', 'Inventory Management', 'TDS & Reports'] },
  ],
  whyLearn: ['Soft skills are essential for career growth', 'MS Office is required in virtually every job', 'English fluency opens global career doors', 'Tally skills are must-have for accounting roles'],
  tools: ['MS Excel', 'MS Word', 'PowerPoint', 'Tally ERP 9', 'Google Workspace'],
  careers: ['Administrative Executive', 'Accountant', 'Data Entry Operator', 'Office Manager', 'HR Executive', 'Customer Service'],
  faqs: [
    { q: 'Is Tally useful in today\'s market?', a: 'Absolutely. Tally is the most widely used accounting software in India for SMEs.' },
    { q: 'Can students from regional medium benefit from spoken English?', a: 'Yes, this course is specifically designed for students who want to improve their English communication.' },
  ],
};

const dataAnalyticsCourses: CourseCategoryData = {
  name: 'Data, Analytics & BI',
  slug: 'data-analytics-bi',
  emoji: '📊',
  tagline: 'Data Science, AI, ML & Business Intelligence',
  description: 'Master data science, machine learning, AI, Power BI, Tableau and analytics. Learn to extract insights from data and drive business decisions with cutting-edge tools.',
  courses: [
    { name: 'Data Science', duration: '5 Months', level: 'Beginner to Advanced', highlights: ['Python for Data Science', 'Machine Learning', 'Deep Learning', 'NLP & Computer Vision'] },
    { name: 'Machine Learning', duration: '3 Months', level: 'Intermediate', highlights: ['Supervised & Unsupervised ML', 'Scikit-learn', 'Model Evaluation', 'Feature Engineering'] },
    { name: 'Artificial Intelligence (AI)', duration: '4 Months', level: 'Intermediate to Advanced', highlights: ['Neural Networks', 'TensorFlow & PyTorch', 'Generative AI', 'AI Applications'] },
    { name: 'Power BI', duration: '1.5 Months', level: 'Beginner', highlights: ['Data Modeling', 'DAX Measures', 'Interactive Dashboards', 'Power Query'] },
    { name: 'Full Stack Power BI', duration: '3 Months', level: 'Beginner to Advanced', highlights: ['Power BI + SQL + Excel', 'Data Warehousing', 'Paginated Reports', 'Power BI Service'] },
    { name: 'Azure Data Analyst', duration: '2 Months', level: 'Intermediate', highlights: ['Azure Synapse', 'Power BI Integration', 'DP-100 Prep', 'Data Visualization'] },
  ],
  whyLearn: ['Data science is the #1 most in-demand job globally', 'AI skills are the future of every industry', 'Power BI is used in 90% of Fortune 500 companies', 'Salary packages of ₹6–25 LPA for freshers'],
  tools: ['Python', 'Pandas', 'NumPy', 'Scikit-learn', 'TensorFlow', 'Power BI', 'Tableau', 'SQL', 'Azure ML'],
  careers: ['Data Scientist', 'ML Engineer', 'AI Engineer', 'Business Intelligence Analyst', 'Data Analyst', 'Power BI Developer'],
  faqs: [
    { q: 'Do I need a math background for data science?', a: 'Basic mathematics helps but is not a strict requirement. We cover statistics as part of the curriculum.' },
    { q: 'Is Power BI difficult to learn?', a: 'Not at all. Power BI is one of the easiest BI tools with a drag-and-drop interface. Beginners pick it up quickly.' },
    { q: 'What is the difference between Data Science and AI?', a: 'Data Science focuses on analysis and modelling; AI is a broader field including robotics, NLP and neural networks. Both overlap significantly.' },
  ],
};

export const courseData: Record<string, CourseCategoryData> = {
  'cloud-computing': cloudCourses,
  'devops-multi-cloud': devopsCourses,
  'programming-full-stack-development': programmingCourses,
  'programming-full-stack': programmingCourses,
  'data-engineering': dataEngCourses,
  'cyber-security-networking': cyberCourses,
  'cyber-security': cyberCourses,
  'erp-crm-enterprise-tools': erpCourses,
  'software-testing-os': testingCourses,
  'digital-design': digitalCourses,
  'professional-soft-skills': softSkillsCourses,
  'data-analytics-bi': dataAnalyticsCourses,
};

// ═══════════════════════════════════════════════════════════════
// UPGRADED COURSE CARD DATA — CourseCardProps arrays (12 categories)
// ═══════════════════════════════════════════════════════════════

export const dataAnalyticsBiCourses: CourseCardProps[] = [
  {
    title: 'Data Science Training in Hyderabad',
    badge: 'Most Popular',
    badgeVariant: 'teal',
    accentVariant: 'data',
    categoryLabel: "DATA ANALYTICS & BI",
    duration: '5 Months',
    mode: 'Classroom',
    level: 'Beginner – Advanced',
    description: 'Master Python, ML, deep learning, and NLP with live projects and expert trainers. Build a job-ready portfolio covering the full data science pipeline.',
    highlights: ['Python, ML & Deep Learning included', 'Real-world capstone projects'],
    originalPrice: '₹45,000',
    discountedPrice: '₹32,000',
    emi: 'EMI from ₹2,700/mo',
    href: '/courses/data-science-training-institute-in-hyderabad',
  },
  {
    title: 'Machine Learning Training in Hyderabad',
    badge: 'High Demand',
    badgeVariant: 'teal',
    accentVariant: 'data',
    categoryLabel: "DATA ANALYTICS & BI",
    duration: '3 Months',
    mode: 'Classroom',
    level: 'Intermediate',
    description: 'Learn supervised & unsupervised ML, Scikit-learn, and feature engineering with live labs. Deploy production-ready models on real datasets.',
    highlights: ['Scikit-learn & feature engineering', 'Model deployment on cloud'],
    originalPrice: '₹28,000',
    discountedPrice: '₹20,000',
    emi: 'EMI from ₹1,700/mo',
    href: '/machine-learning-training-institute-in-hyderabad/',
  },
  {
    title: 'Artificial Intelligence (AI) Training',
    badge: 'Trending',
    badgeVariant: 'teal',
    accentVariant: 'data',
    categoryLabel: "DATA ANALYTICS & BI",
    duration: '4 Months',
    mode: 'Classroom',
    level: 'Intermediate – Advanced',
    description: 'From neural networks to Generative AI and LLMs — build AI apps using TensorFlow, PyTorch, and OpenAI APIs with hands-on labs.',
    highlights: ['TensorFlow, PyTorch & Generative AI', 'Industry AI project portfolio'],
    originalPrice: '₹40,000',
    discountedPrice: '₹28,000',
    emi: 'EMI from ₹2,350/mo',
    href: '/artificial-intelligence-ai-training-institute-in-hyderabad/',
  },
  {
    title: 'Power BI Training in Hyderabad',
    badge: 'Newly Added',
    badgeVariant: 'teal',
    accentVariant: 'data',
    categoryLabel: "DATA ANALYTICS & BI",
    duration: '1.5 Months',
    mode: 'Classroom',
    level: 'Beginner',
    description: 'Create stunning dashboards with DAX, data modeling, and Power Query. The most in-demand BI tool in India — learn it in just 6 weeks.',
    highlights: ['DAX measures & Power Query', 'Interactive dashboards from scratch'],
    originalPrice: '₹18,000',
    discountedPrice: '₹12,000',
    emi: 'EMI from ₹1,000/mo',
    href: '/full-stack-power-bi-training-institute-in-hyderabad/',
  },
  {
    title: 'Full Stack Power BI Training',
    badge: 'Best Seller',
    badgeVariant: 'teal',
    accentVariant: 'data',
    categoryLabel: "DATA ANALYTICS & BI",
    duration: '3 Months',
    mode: 'Classroom',
    level: 'Beginner – Advanced',
    description: 'The complete Power BI program — SQL, Excel, data warehousing, Power BI Service, and paginated reports for enterprise analytics roles.',
    highlights: ['SQL + Power BI + Excel combo', 'Power BI Service deployment'],
    originalPrice: '₹32,000',
    discountedPrice: '₹22,000',
    emi: 'EMI from ₹1,850/mo',
    href: '/full-stack-power-bi-training-institute-in-hyderabad/',
  },
  {
    title: 'Azure Data Analyst Training',
    badge: 'Updated 2026',
    badgeVariant: 'teal',
    accentVariant: 'data',
    categoryLabel: "DATA ANALYTICS & BI",
    duration: '2 Months',
    mode: 'Classroom',
    level: 'Intermediate',
    description: 'Combine Azure Synapse Analytics with Power BI for enterprise analytics and DP-100 exam prep with real Azure environment access.',
    highlights: ['Azure Synapse & Power BI integration', 'DP-100 exam preparation'],
    originalPrice: '₹24,000',
    discountedPrice: '₹17,000',
    emi: 'EMI from ₹1,450/mo',
    href: '/courses/data-analytics-training-institute-in-hyderabad',
  },
];

export const cloudComputingCourses: CourseCardProps[] = [
  {
    title: 'AWS Cloud Training in Hyderabad',
    badge: 'Most Popular',
    badgeVariant: 'teal',
    accentVariant: 'cloud',
    categoryLabel: "CLOUD COMPUTING",
    duration: '2–3 Months',
    mode: 'Classroom',
    level: 'Beginner – Advanced',
    description: 'Become an AWS Certified Solutions Architect with hands-on labs on EC2, S3, RDS, Lambda, and VPC. 100% exam assistance.',
    highlights: ['AWS Solutions Architect exam prep', 'Hands-on labs on real AWS'],
    originalPrice: '₹25,000',
    discountedPrice: '₹18,000',
    emi: 'EMI from ₹1,500/mo',
    href: '/aws-cloud-training-in-hyderabad/',
  },
  {
    title: 'Microsoft Azure Training in Hyderabad',
    badge: 'High Demand',
    badgeVariant: 'teal',
    accentVariant: 'cloud',
    categoryLabel: "CLOUD COMPUTING",
    duration: '2–3 Months',
    mode: 'Classroom',
    level: 'Beginner – Advanced',
    description: 'Master Azure Virtual Machines, Active Directory, AKS, and Azure DevOps. Prepare for AZ-900 and AZ-104 certifications with live lab access.',
    highlights: ['AZ-900 / AZ-104 certification prep', 'Live Azure environment access'],
    originalPrice: '₹25,000',
    discountedPrice: '₹18,000',
    emi: 'EMI from ₹1,500/mo',
    href: '/azure-training-institute-in-hyderabad/',
  },
  {
    title: 'Google Cloud Training in Hyderabad',
    badge: 'Updated 2026',
    badgeVariant: 'teal',
    accentVariant: 'cloud',
    categoryLabel: "CLOUD COMPUTING",
    duration: '2 Months',
    mode: 'Classroom',
    level: 'Intermediate',
    description: 'Explore GCP core services, BigQuery, Dataflow, and Kubernetes Engine. Prepare for the Associate Cloud Engineer certification with expert trainers.',
    highlights: ['Associate Cloud Engineer certification', 'BigQuery & GKE hands-on labs'],
    originalPrice: '₹22,000',
    discountedPrice: '₹16,000',
    emi: 'EMI from ₹1,350/mo',
    href: '/google-cloud-training-institute-in-hyderabad/',
  },
  {
    title: 'Multi-Cloud Engineer Training',
    badge: 'Trending',
    badgeVariant: 'teal',
    accentVariant: 'cloud',
    categoryLabel: "CLOUD COMPUTING",
    duration: '4 Months',
    mode: 'Classroom',
    level: 'Advanced',
    description: 'Master AWS, Azure, and GCP together — cloud migration, cost optimization, and multi-cloud architecture for enterprise environments.',
    highlights: ['AWS + Azure + GCP combined', 'Multi-cloud architecture projects'],
    originalPrice: '₹42,000',
    discountedPrice: '₹30,000',
    emi: 'EMI from ₹2,500/mo',
    href: '/courses/multi-cloud-architecture-training-in-hyderabad',
  },
  {
    title: 'Cloud Architecture Training',
    badge: 'Newly Added',
    badgeVariant: 'teal',
    accentVariant: 'cloud',
    categoryLabel: "CLOUD COMPUTING",
    duration: '3 Months',
    mode: 'Classroom',
    level: 'Advanced',
    description: 'Design high-availability, DR-ready cloud solutions with advanced cost management strategies. Build enterprise-grade cloud architecture skills.',
    highlights: ['High availability & DR design', 'Cloud cost optimization strategies'],
    originalPrice: '₹38,000',
    discountedPrice: '₹26,000',
    emi: 'EMI from ₹2,200/mo',
    href: '/courses/cloud-computing/',
  },
];

export const devopsMultiCloudCourses: CourseCardProps[] = [
  {
    title: 'AWS DevOps Training in Hyderabad',
    badge: 'High Demand',
    badgeVariant: 'rose',
    accentVariant: 'devops',
    categoryLabel: "DEVOPS & MULTI-CLOUD",
    duration: '3 Months',
    mode: 'Classroom',
    level: 'Intermediate',
    description: 'Master CodePipeline, CodeDeploy, ECS, EKS, and CloudWatch for complete AWS DevOps workflows. AWS DevOps Professional exam prep included.',
    highlights: ['CodePipeline & EKS deployment', 'AWS DevOps Professional prep'],
    originalPrice: '₹30,000',
    discountedPrice: '₹22,000',
    emi: 'EMI from ₹1,850/mo',
    href: '/aws-devops-course-in-hyderabad-by-coss-cloud-solutions/',
  },
  {
    title: 'Azure DevOps Training in Hyderabad',
    badge: 'Most Popular',
    badgeVariant: 'rose',
    accentVariant: 'devops',
    categoryLabel: "DEVOPS & MULTI-CLOUD",
    duration: '3 Months',
    mode: 'Classroom',
    level: 'Intermediate',
    description: 'Learn Azure Pipelines, Boards, Repos, AKS, and ARM Templates. Prepare for Azure DevOps Expert certification with real project labs.',
    highlights: ['Azure Pipelines & AKS deployment', 'Azure DevOps Expert certification'],
    originalPrice: '₹30,000',
    discountedPrice: '₹22,000',
    emi: 'EMI from ₹1,850/mo',
    href: '/azure-devops-courses-in-hyderabad-by-coss-cloud-solutions/',
  },
  {
    title: 'Docker and Kubernetes Training',
    badge: 'Trending',
    badgeVariant: 'rose',
    accentVariant: 'devops',
    categoryLabel: "DEVOPS & MULTI-CLOUD",
    duration: '2 Months',
    mode: 'Classroom',
    level: 'Intermediate',
    description: 'Build, ship, and orchestrate containers from fundamentals to production. CKA exam prep and real-world deployment projects included.',
    highlights: ['CKA exam prep & practice labs', 'Real-world deployment projects'],
    originalPrice: '₹24,000',
    discountedPrice: '₹18,000',
    emi: 'EMI from ₹1,500/mo',
    href: '/devops-training-institute-in-hyderabad/',
  },
  {
    title: 'Terraform & Infrastructure as Code',
    badge: 'Updated 2026',
    badgeVariant: 'rose',
    accentVariant: 'devops',
    categoryLabel: "DEVOPS & MULTI-CLOUD",
    duration: '1.5 Months',
    mode: 'Classroom',
    level: 'Advanced',
    description: 'Provision multi-cloud infrastructure with Terraform — state management, modules, workspaces, and CI/CD integration with live labs.',
    highlights: ['Multi-cloud Terraform provisioning', 'CI/CD pipeline integration'],
    originalPrice: '₹20,000',
    discountedPrice: '₹14,000',
    emi: 'EMI from ₹1,200/mo',
    href: '/devops-training-in-hyderabad/',
  },
  {
    title: 'Jenkins & CI/CD Training',
    badge: 'Newly Added',
    badgeVariant: 'rose',
    accentVariant: 'devops',
    categoryLabel: "DEVOPS & MULTI-CLOUD",
    duration: '1 Month',
    mode: 'Classroom',
    level: 'Intermediate',
    description: 'Master Jenkins pipelines, Git integration, build automation, and deployment strategies for real-world CI/CD workflows.',
    highlights: ['Pipeline as Code with Jenkins', 'Git + Jenkins deployment strategies'],
    originalPrice: '₹15,000',
    discountedPrice: '₹10,000',
    emi: 'EMI from ₹850/mo',
    href: '/devops-training-in-hyderabad/',
  },
  {
    title: 'Full DevOps Bootcamp',
    badge: 'Best Seller',
    badgeVariant: 'rose',
    accentVariant: 'devops',
    categoryLabel: "DEVOPS & MULTI-CLOUD",
    duration: '5 Months',
    mode: 'Classroom',
    level: 'Beginner – Advanced',
    description: 'The complete DevOps journey — Git, Linux, Docker, Kubernetes, AWS/Azure, Jenkins, and Terraform in one comprehensive program.',
    highlights: ['Git + Linux + Docker + K8s + AWS', 'End-to-end DevOps project portfolio'],
    originalPrice: '₹55,000',
    discountedPrice: '₹38,000',
    emi: 'EMI from ₹3,200/mo',
    href: '/devops-training-in-hyderabad/',
  },
];

export const programmingFullStackCourses: CourseCardProps[] = [
  {
    title: 'Java Full Stack Training in Hyderabad',
    badge: 'Most Popular',
    badgeVariant: 'green',
    accentVariant: 'fullstack',
    categoryLabel: "PROGRAMMING & FULL STACK",
    duration: '5 Months',
    mode: 'Classroom',
    level: 'Beginner – Advanced',
    description: 'Build enterprise web apps with Core Java, Spring Boot, Microservices, React.js, and MySQL — the complete full-stack Java career program.',
    highlights: ['Spring Boot & Microservices project', 'React.js + MySQL integration'],
    originalPrice: '₹48,000',
    discountedPrice: '₹34,000',
    emi: 'EMI from ₹2,850/mo',
    href: '/java-training-institute-in-hyderabad/',
  },
  {
    title: 'Python Full Stack Training in Hyderabad',
    badge: 'High Demand',
    badgeVariant: 'green',
    accentVariant: 'fullstack',
    categoryLabel: "PROGRAMMING & FULL STACK",
    duration: '4 Months',
    mode: 'Classroom',
    level: 'Beginner – Advanced',
    description: 'Learn Python fundamentals, Django/Flask, React.js, and REST APIs — build complete full-stack applications from backend to frontend.',
    highlights: ['Django/Flask + React.js full stack', 'REST API development projects'],
    originalPrice: '₹42,000',
    discountedPrice: '₹30,000',
    emi: 'EMI from ₹2,500/mo',
    href: '/python-training-institute-in-hyderabad/',
  },
  {
    title: 'MERN Stack Training in Hyderabad',
    badge: 'Trending',
    badgeVariant: 'green',
    accentVariant: 'fullstack',
    categoryLabel: "PROGRAMMING & FULL STACK",
    duration: '4 Months',
    mode: 'Classroom',
    level: 'Intermediate',
    description: 'Master MongoDB, Express.js, React.js, and Node.js to build modern web applications end-to-end with real-world startup projects.',
    highlights: ['MongoDB + Node.js backend', 'React.js frontend with Redux'],
    originalPrice: '₹38,000',
    discountedPrice: '₹26,000',
    emi: 'EMI from ₹2,200/mo',
    href: '/courses/programming-full-stack/full-stack-java-developer-training-in-hyderabad',
  },
  {
    title: 'React.js Training in Hyderabad',
    badge: 'Updated 2026',
    badgeVariant: 'green',
    accentVariant: 'fullstack',
    categoryLabel: "PROGRAMMING & FULL STACK",
    duration: '2 Months',
    mode: 'Classroom',
    level: 'Intermediate',
    description: 'Build dynamic single-page applications with React Hooks, Redux, and API integration. Learn component architecture through hands-on projects.',
    highlights: ['React Hooks & Redux state management', 'API integration projects'],
    originalPrice: '₹22,000',
    discountedPrice: '₹15,000',
    emi: 'EMI from ₹1,250/mo',
    href: '/courses/programming-full-stack/full-stack-java-developer-training-in-hyderabad',
  },
  {
    title: 'Core Java Training in Hyderabad',
    badge: 'Newly Added',
    badgeVariant: 'green',
    accentVariant: 'fullstack',
    categoryLabel: "PROGRAMMING & FULL STACK",
    duration: '2 Months',
    mode: 'Classroom',
    level: 'Beginner',
    description: 'Build strong Java fundamentals — OOPs, Collections, Exception Handling, and JDBC. The essential foundation for any Java developer career.',
    highlights: ['OOPs, Collections & JDBC mastery', 'Hands-on project assignments'],
    originalPrice: '₹18,000',
    discountedPrice: '₹12,000',
    emi: 'EMI from ₹1,000/mo',
    href: '/java-training-institute-in-hyderabad/',
  },
];

export const dataEngineeringCourses: CourseCardProps[] = [
  {
    title: 'Azure Data Engineer Training',
    badge: 'Most Popular',
    badgeVariant: 'violet',
    accentVariant: 'data',
    categoryLabel: "DATA ENGINEERING",
    duration: '3 Months',
    mode: 'Classroom',
    level: 'Intermediate',
    description: 'Master Azure Data Factory, Azure Synapse Analytics, and Databricks for enterprise data pipelines. DP-203 certification exam prep included.',
    highlights: ['Azure Data Factory & Synapse', 'DP-203 certification preparation'],
    originalPrice: '₹32,000',
    discountedPrice: '₹22,000',
    emi: 'EMI from ₹1,850/mo',
    href: '/courses/data-engineering/azure-data-factory-training-in-hyderabad',
  },
  {
    title: 'Apache Spark & PySpark Training',
    badge: 'High Demand',
    badgeVariant: 'violet',
    accentVariant: 'data',
    categoryLabel: "DATA ENGINEERING",
    duration: '2 Months',
    mode: 'Classroom',
    level: 'Intermediate',
    description: 'Process massive datasets with Apache Spark, PySpark DataFrames, Spark Streaming, and Spark ML. Hands-on cluster labs included.',
    highlights: ['PySpark DataFrames & Streaming', 'Spark ML pipeline projects'],
    originalPrice: '₹26,000',
    discountedPrice: '₹18,000',
    emi: 'EMI from ₹1,500/mo',
    href: '/data-engineering-training-institute-in-hyderabad/',
  },
  {
    title: 'Hadoop Ecosystem Training',
    badge: 'Updated 2026',
    badgeVariant: 'violet',
    accentVariant: 'data',
    categoryLabel: "DATA ENGINEERING",
    duration: '2 Months',
    mode: 'Classroom',
    level: 'Intermediate',
    description: 'Learn HDFS, MapReduce, Hive, Pig, HBase, Sqoop, and Flume — the complete Hadoop ecosystem for big data engineering roles.',
    highlights: ['HDFS, Hive & HBase hands-on', 'Sqoop & Flume data ingestion'],
    originalPrice: '₹22,000',
    discountedPrice: '₹15,000',
    emi: 'EMI from ₹1,250/mo',
    href: '/data-engineering-training-institute-in-hyderabad/',
  },
  {
    title: 'ETL & Data Pipelines Training',
    badge: 'Newly Added',
    badgeVariant: 'violet',
    accentVariant: 'data',
    categoryLabel: "DATA ENGINEERING",
    duration: '1.5 Months',
    mode: 'Classroom',
    level: 'Intermediate',
    description: 'Design and build data pipelines with SSIS, Informatica, and Apache Airflow. Learn ETL patterns and pipeline orchestration for production systems.',
    highlights: ['SSIS, Informatica & Airflow', 'ETL design patterns & orchestration'],
    originalPrice: '₹18,000',
    discountedPrice: '₹13,000',
    emi: 'EMI from ₹1,100/mo',
    href: '/data-engineering-training-institute-in-hyderabad/',
  },
];

export const cyberSecurityCourses: CourseCardProps[] = [
  {
    title: 'Ethical Hacking & CEH Training',
    badge: 'High Demand',
    badgeVariant: 'rose',
    accentVariant: 'security',
    categoryLabel: "CYBER SECURITY",
    duration: '3 Months',
    mode: 'Classroom',
    level: 'Intermediate',
    description: 'Learn penetration testing, network scanning, and vulnerability assessment. CEH certification preparation with live ethical hacking labs.',
    highlights: ['CEH certification preparation', 'Live penetration testing labs'],
    originalPrice: '₹30,000',
    discountedPrice: '₹22,000',
    emi: 'EMI from ₹1,850/mo',
    href: '/ethical-hacking-in-hyderabad-coss-cloud-solutions/',
  },
  {
    title: 'SOC Analyst Training in Hyderabad',
    badge: 'Most Popular',
    badgeVariant: 'rose',
    accentVariant: 'security',
    categoryLabel: "CYBER SECURITY",
    duration: '2 Months',
    mode: 'Classroom',
    level: 'Beginner – Intermediate',
    description: 'Master SIEM tools, incident response, threat intelligence, and log analysis. Build the skills to work in enterprise security operations centers.',
    highlights: ['SIEM & incident response', 'Threat intelligence & log analysis'],
    originalPrice: '₹24,000',
    discountedPrice: '₹17,000',
    emi: 'EMI from ₹1,450/mo',
    href: '/ethical-hacking-in-hyderabad-coss-cloud-solutions/',
  },
  {
    title: 'CCNA Networking Training in Hyderabad',
    badge: 'Updated 2026',
    badgeVariant: 'rose',
    accentVariant: 'security',
    categoryLabel: "CYBER SECURITY",
    duration: '2 Months',
    mode: 'Classroom',
    level: 'Beginner',
    description: 'Build a solid networking foundation with routing & switching, VLANs, and CCNA certification prep. Hands-on Cisco lab equipment included.',
    highlights: ['CCNA certification preparation', 'Hands-on Cisco lab access'],
    originalPrice: '₹20,000',
    discountedPrice: '₹14,000',
    emi: 'EMI from ₹1,200/mo',
    href: '/ccna-networking-training-in-hyderabad/',
  },
  {
    title: 'Network Security Training in Hyderabad',
    badge: 'Newly Added',
    badgeVariant: 'rose',
    accentVariant: 'security',
    categoryLabel: "CYBER SECURITY",
    duration: '2 Months',
    mode: 'Classroom',
    level: 'Intermediate',
    description: 'Configure firewalls, VPNs, IDS/IPS systems, and security policies in real enterprise network environments with live labs.',
    highlights: ['Firewall & VPN configuration', 'IDS/IPS & security policy labs'],
    originalPrice: '₹22,000',
    discountedPrice: '₹16,000',
    emi: 'EMI from ₹1,350/mo',
    href: '/ccna-networking-training-in-hyderabad/',
  },
];

export const erpCrmCourses: CourseCardProps[] = [
  {
    title: 'SAP S/4HANA Finance (FICO) Training',
    badge: 'Updated 2026',
    badgeVariant: 'amber',
    accentVariant: 'sap',
    categoryLabel: "ERP, CRM & ENTERPRISE",
    duration: '3 Months',
    mode: 'Classroom',
    level: 'Beginner – Advanced',
    description: 'Complete SAP FI/CO consultant training — GL, accounts payable/receivable, cost centre accounting, and S/4HANA workflows. SAP certified trainer.',
    highlights: ['SAP certified trainer, live system', '₹12–₹35 LPA average salary'],
    originalPrice: '₹38,000',
    discountedPrice: '₹28,000',
    emi: 'EMI from ₹2,350/mo',
    href: '/sap-fico-training-institute-in-hyderabad/',
  },
  {
    title: 'Salesforce CRM Training in Hyderabad',
    badge: 'Most Popular',
    badgeVariant: 'amber',
    accentVariant: 'oracle',
    categoryLabel: "ERP, CRM & ENTERPRISE",
    duration: '2 Months',
    mode: 'Classroom',
    level: 'Beginner',
    description: 'Become a Salesforce Admin — master Sales Cloud, Service Cloud, and Salesforce certification with real CRM project experience.',
    highlights: ['Salesforce Admin certification', 'Sales & Service Cloud projects'],
    originalPrice: '₹26,000',
    discountedPrice: '₹18,000',
    emi: 'EMI from ₹1,500/mo',
    href: '/salesforce-training-center-in-hyderabad/',
  },
  {
    title: 'Oracle Fusion Cloud HCM Training',
    badge: 'High Demand',
    badgeVariant: 'amber',
    accentVariant: 'oracle',
    categoryLabel: "ERP, CRM & ENTERPRISE",
    duration: '2.5 Months',
    mode: 'Classroom',
    level: 'Intermediate',
    description: 'Become an Oracle HCM consultant — master Global HR, Payroll, Talent Management, and Workforce Compensation on Oracle Fusion Cloud.',
    highlights: ['Live Oracle cloud tenant access', '₹8–₹25 LPA average salary'],
    originalPrice: '₹32,000',
    discountedPrice: '₹24,000',
    emi: 'EMI from ₹2,000/mo',
    href: '/oracle-fusion-cloud-hcm-training-in-hyderabad/',
  },
  {
    title: 'SAP HR Training in Hyderabad',
    badge: 'Newly Added',
    badgeVariant: 'amber',
    accentVariant: 'sap',
    categoryLabel: "ERP, CRM & ENTERPRISE",
    duration: '2 Months',
    mode: 'Classroom',
    level: 'Beginner – Intermediate',
    description: 'Learn SAP HR modules — Personnel Management, Payroll, Org Management, and Time Management with real SAP system configuration.',
    highlights: ['SAP Payroll & Org Management', 'Real SAP system configuration'],
    originalPrice: '₹26,000',
    discountedPrice: '₹19,000',
    emi: 'EMI from ₹1,600/mo',
    href: '/sap-fico-training-institute-in-hyderabad/',
  },
];

export const softwareTestingCourses: CourseCardProps[] = [
  {
    title: 'Manual Testing Training in Hyderabad',
    badge: 'Newly Added',
    badgeVariant: 'orange',
    accentVariant: 'devops',
    categoryLabel: "SOFTWARE TESTING",
    duration: '1.5 Months',
    mode: 'Classroom',
    level: 'Beginner',
    description: 'Learn SDLC, STLC, test case design, bug reporting, and Agile/Scrum methodologies. The essential foundation for any QA career.',
    highlights: ['SDLC, STLC & Agile testing', 'Bug reporting with JIRA'],
    originalPrice: '₹15,000',
    discountedPrice: '₹10,000',
    emi: 'EMI from ₹850/mo',
    href: '/software-testing-training-institute-in-hyderabad/',
  },
  {
    title: 'Selenium Automation Testing Training',
    badge: 'Most Popular',
    badgeVariant: 'orange',
    accentVariant: 'devops',
    categoryLabel: "SOFTWARE TESTING",
    duration: '2 Months',
    mode: 'Classroom',
    level: 'Intermediate',
    description: 'Automate web testing with Selenium WebDriver, TestNG, PyTest, and CI/CD pipeline integration. Java/Python with Selenium covered.',
    highlights: ['Selenium WebDriver + TestNG', 'CI/CD pipeline integration'],
    originalPrice: '₹22,000',
    discountedPrice: '₹15,000',
    emi: 'EMI from ₹1,250/mo',
    href: '/software-testing-training-institute-in-hyderabad/',
  },
  {
    title: 'Linux Administration Training',
    badge: 'High Demand',
    badgeVariant: 'orange',
    accentVariant: 'devops',
    categoryLabel: "SOFTWARE TESTING",
    duration: '2 Months',
    mode: 'Classroom',
    level: 'Beginner – Intermediate',
    description: 'Master Linux commands, shell scripting, user management, and server administration. The essential skill for cloud, DevOps, and networking careers.',
    highlights: ['Shell scripting & user management', 'Server admin for cloud & DevOps'],
    originalPrice: '₹20,000',
    discountedPrice: '₹14,000',
    emi: 'EMI from ₹1,200/mo',
    href: '/linux-training-in-hyderabad/',
  },
  {
    title: 'API Testing Training in Hyderabad',
    badge: 'Updated 2026',
    badgeVariant: 'orange',
    accentVariant: 'devops',
    categoryLabel: "SOFTWARE TESTING",
    duration: '1 Month',
    mode: 'Classroom',
    level: 'Intermediate',
    description: 'Test REST & SOAP APIs with Postman and REST Assured. Learn JSON/XML parsing and integrate API tests into CI/CD pipelines.',
    highlights: ['Postman & REST Assured testing', 'CI/CD API test integration'],
    originalPrice: '₹15,000',
    discountedPrice: '₹10,000',
    emi: 'EMI from ₹850/mo',
    href: '/software-testing-training-institute-in-hyderabad/',
  },
];

export const digitalDesignCourses: CourseCardProps[] = [
  {
    title: 'Digital Marketing Training in Hyderabad',
    badge: 'Most Popular',
    badgeVariant: 'violet',
    accentVariant: 'digital',
    categoryLabel: "DIGITAL & DESIGN",
    duration: '2.5 Months',
    mode: 'Classroom',
    level: 'Beginner',
    description: 'Master SEO, Google Ads, Social Media Marketing, Email Marketing, and Google Analytics. Build campaigns on real ad accounts with live budgets.',
    highlights: ['Live Google Ads & Meta campaigns', 'SEO & Google Analytics mastery'],
    originalPrice: '₹25,000',
    discountedPrice: '₹18,000',
    emi: 'EMI from ₹1,500/mo',
    href: '/digital-marketing-course-in-hyderabad-by-coss-cloud-solutions/',
  },
  {
    title: 'UI/UX Design Training in Hyderabad',
    badge: 'Trending',
    badgeVariant: 'violet',
    accentVariant: 'digital',
    categoryLabel: "DIGITAL & DESIGN",
    duration: '2 Months',
    mode: 'Classroom',
    level: 'Beginner',
    description: 'Design wireframes, prototypes, and design systems using Figma and Adobe XD. Conduct user research and build a portfolio of real-world projects.',
    highlights: ['Figma & Adobe XD full course', 'User research & portfolio projects'],
    originalPrice: '₹22,000',
    discountedPrice: '₹15,000',
    emi: 'EMI from ₹1,250/mo',
    href: '/ui-ux-design-training-institute-in-hyderabad/',
  },
  {
    title: 'Graphic Design Training in Hyderabad',
    badge: 'Newly Added',
    badgeVariant: 'violet',
    accentVariant: 'digital',
    categoryLabel: "DIGITAL & DESIGN",
    duration: '1.5 Months',
    mode: 'Classroom',
    level: 'Beginner',
    description: 'Create stunning visuals with Adobe Photoshop, Illustrator, and Canva. Build brand identity designs and a freelance-ready portfolio.',
    highlights: ['Photoshop & Illustrator mastery', 'Brand identity design projects'],
    originalPrice: '₹18,000',
    discountedPrice: '₹12,000',
    emi: 'EMI from ₹1,000/mo',
    href: '/digital-marketing-course-in-hyderabad-by-coss-cloud-solutions/',
  },
  {
    title: 'SEO & Content Marketing Training',
    badge: 'High Demand',
    badgeVariant: 'violet',
    accentVariant: 'digital',
    categoryLabel: "DIGITAL & DESIGN",
    duration: '1.5 Months',
    mode: 'Classroom',
    level: 'Beginner – Intermediate',
    description: 'Master on-page & off-page SEO, content strategy, link building, and SEO audits. Learn to rank websites and drive organic traffic.',
    highlights: ['On-page & off-page SEO mastery', 'Content strategy & link building'],
    originalPrice: '₹18,000',
    discountedPrice: '₹12,000',
    emi: 'EMI from ₹1,000/mo',
    href: '/digital-marketing-training-institute-in-dilsukhnagar-hyderabad/',
  },
];

export const professionalSoftSkillsCourses: CourseCardProps[] = [
  {
    title: 'MS Office Training in Hyderabad',
    badge: 'Most Popular',
    badgeVariant: 'green',
    accentVariant: 'softskills',
    categoryLabel: "PROFESSIONAL SKILLS",
    duration: '1.5 Months',
    mode: 'Classroom',
    level: 'Beginner',
    description: 'Master Excel formulas, Pivot Tables, Word processing, PowerPoint presentations, and Excel Macros & VBA for office productivity.',
    highlights: ['Excel Macros & VBA included', 'Pivot Tables & advanced formulas'],
    originalPrice: '₹15,000',
    discountedPrice: '₹10,000',
    emi: 'EMI from ₹850/mo',
    href: '/ms-office-course-near-me-in-hyderabad-coss-cloud-solutions/',
  },
  {
    title: 'Spoken English Training in Hyderabad',
    badge: 'High Demand',
    badgeVariant: 'green',
    accentVariant: 'softskills',
    categoryLabel: "PROFESSIONAL SKILLS",
    duration: '2 Months',
    mode: 'Classroom',
    level: 'Beginner',
    description: 'Improve grammar, pronunciation, and business communication for workplace success. Group discussions and mock interview practice included.',
    highlights: ['Business English & pronunciation', 'Group discussion & mock interviews'],
    originalPrice: '₹15,000',
    discountedPrice: '₹10,000',
    emi: 'EMI from ₹850/mo',
    href: '/spoken-english-institute-in-hyderabad-coss-cloud-solutions/',
  },
  {
    title: 'Communication Skills Training',
    badge: 'Newly Added',
    badgeVariant: 'green',
    accentVariant: 'softskills',
    categoryLabel: "PROFESSIONAL SKILLS",
    duration: '1 Month',
    mode: 'Classroom',
    level: 'Beginner',
    description: 'Develop public speaking, business writing, presentation skills, and confident body language for professional environments.',
    highlights: ['Public speaking & presentations', 'Business writing & body language'],
    originalPrice: '₹12,000',
    discountedPrice: '₹8,000',
    emi: 'EMI from ₹680/mo',
    href: '/communication-skills-training-in-hyderabad-coss-cloud-solutions/',
  },
  {
    title: 'Tally ERP Training in Hyderabad',
    badge: 'Best Seller',
    badgeVariant: 'green',
    accentVariant: 'softskills',
    categoryLabel: "PROFESSIONAL SKILLS",
    duration: '1.5 Months',
    mode: 'Classroom',
    level: 'Beginner',
    description: 'Learn GST accounting, payroll management, inventory management, TDS, and reports with Tally ERP 9 — the most used accounting software in India.',
    highlights: ['GST accounting & payroll in Tally', 'TDS, inventory & financial reports'],
    originalPrice: '₹12,000',
    discountedPrice: '₹8,000',
    emi: 'EMI from ₹680/mo',
    href: '/tally-classes-in-hyderabad/',
  },
];

export const humanResourceCourses: CourseCardProps[] = [
  {
    title: 'HR Recruitment Training in Hyderabad',
    badge: 'Newly Added',
    badgeVariant: 'orange',
    accentVariant: 'hr',
    categoryLabel: "HUMAN RESOURCE",
    duration: '3 Months',
    mode: 'Classroom',
    level: 'Beginner – Advanced',
    description: 'Launch your HR career with industry-focused recruitment training covering sourcing, interviewing, onboarding, and HR tools — built for freshers.',
    highlights: ['Live projects + mock interviews', 'Placement assistance included'],
    originalPrice: '₹35,000',
    discountedPrice: '₹25,000',
    emi: 'EMI from ₹2,100/mo',
    href: '/enroll-now-with-coss/',
  },
  {
    title: 'HR Analytics Training in Hyderabad',
    badge: 'High Demand',
    badgeVariant: 'orange',
    accentVariant: 'hr',
    categoryLabel: "HUMAN RESOURCE",
    duration: '2 Months',
    mode: 'Classroom',
    level: 'Intermediate',
    description: 'Use data analytics to drive HR decisions — workforce planning, attrition analysis, and people metrics with Excel, Power BI, and Python.',
    highlights: ['Workforce & attrition analytics', 'Power BI HR dashboard projects'],
    originalPrice: '₹24,000',
    discountedPrice: '₹17,000',
    emi: 'EMI from ₹1,450/mo',
    href: '/enroll-now-with-coss/',
  },
  {
    title: 'HR Operations Training in Hyderabad',
    badge: 'Updated 2026',
    badgeVariant: 'orange',
    accentVariant: 'hr',
    categoryLabel: "HUMAN RESOURCE",
    duration: '2 Months',
    mode: 'Classroom',
    level: 'Beginner – Intermediate',
    description: 'Master end-to-end HR operations — payroll processing, compliance, employee lifecycle management, and HRMS tools used in Indian companies.',
    highlights: ['Payroll & compliance processes', 'HRMS tools & employee lifecycle'],
    originalPrice: '₹20,000',
    discountedPrice: '₹14,000',
    emi: 'EMI from ₹1,200/mo',
    href: '/enroll-now-with-coss/',
  },
];

export const quantumComputingCourses: CourseCardProps[] = [
  {
    title: 'Quantum Computing Fundamentals',
    badge: 'Newly Added',
    badgeVariant: 'teal',
    accentVariant: 'quantum',
    categoryLabel: "QUANTUM COMPUTING",
    duration: '2 Months',
    mode: 'Classroom',
    level: 'Beginner',
    description: 'Explore qubits, quantum gates, superposition, and entanglement. Build the conceptual foundation for quantum computing with hands-on simulations.',
    highlights: ['Qubit & quantum gate fundamentals', 'Quantum circuit simulations'],
    originalPrice: '₹22,000',
    discountedPrice: '₹15,000',
    emi: 'EMI from ₹1,250/mo',
    href: '/enroll-now-with-coss/',
  },
  {
    title: 'Qiskit & Python Quantum Training',
    badge: 'Trending',
    badgeVariant: 'teal',
    accentVariant: 'quantum',
    categoryLabel: "QUANTUM COMPUTING",
    duration: '3 Months',
    mode: 'Classroom',
    level: 'Intermediate',
    description: 'Program real quantum computers with IBM Qiskit and Python. Build quantum circuits, run jobs on IBM Quantum cloud, and explore variational algorithms.',
    highlights: ['IBM Qiskit & quantum cloud access', 'Variational quantum algorithms'],
    originalPrice: '₹28,000',
    discountedPrice: '₹20,000',
    emi: 'EMI from ₹1,700/mo',
    href: '/enroll-now-with-coss/',
  },
  {
    title: 'Quantum Algorithms Training',
    badge: 'Updated 2026',
    badgeVariant: 'teal',
    accentVariant: 'quantum',
    categoryLabel: "QUANTUM COMPUTING",
    duration: '2.5 Months',
    mode: 'Classroom',
    level: 'Advanced',
    description: "Study Shor's, Grover's, and QAOA algorithms with applications in cryptography and optimization. Hands-on IBM Quantum and Python implementation.",
    highlights: ["Shor's & Grover's algorithms", 'Quantum cryptography projects'],
    originalPrice: '₹30,000',
    discountedPrice: '₹22,000',
    emi: 'EMI from ₹1,850/mo',
    href: '/enroll-now-with-coss/',
  },
];

export const courseCardDataMap: Record<string, CourseCardProps[]> = {
  'data-analytics-bi':         dataAnalyticsBiCourses,
  'cloud-computing':            cloudComputingCourses,
  'devops-multi-cloud':         devopsMultiCloudCourses,
  'programming-full-stack':     programmingFullStackCourses,
  'programming-full-stack-development': programmingFullStackCourses,
  'data-engineering':           dataEngineeringCourses,
  'cyber-security':             cyberSecurityCourses,
  'cyber-security-networking':  cyberSecurityCourses,
  'erp-crm-enterprise-tools':   erpCrmCourses,
  'software-testing-os':        softwareTestingCourses,
  'digital-design':             digitalDesignCourses,
  'professional-soft-skills':   professionalSoftSkillsCourses,
  'human-resource':             humanResourceCourses,
  'quantum-computing':          quantumComputingCourses,
};
