import createMDX from '@next/mdx';

/** @type {import('next').NextConfig} */
const nextConfig = {
  trailingSlash: false,
  pageExtensions: ['js', 'jsx', 'mdx', 'ts', 'tsx'],
  images: {
    // Allowlist only the CDN hostnames actually used by <Image> components
    // (Cloudinary), to prevent this server being used as an open
    // image-optimization proxy for arbitrary external URLs.
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'res.cloudinary.com',
        pathname: '/dfditihuw/**',
      },
    ],
    formats: ['image/avif', 'image/webp'],
  },

  async headers() {
    const isDev = process.env.NODE_ENV === 'development';
    return [
      {
        source: '/(.*)',
        headers: [
          // Prevents click-jacking — boosts security trust signals for Google
          { key: 'Cache-Control', value: 'no-store, must-revalidate' },
          { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
          // Stops MIME-type sniffing — another security trust signal
          { key: 'X-Content-Type-Options', value: 'nosniff' },
          // Forces HTTPS for 1 year (includeSubDomains) — helps HTTPS ranking factor
          { key: 'Strict-Transport-Security', value: 'max-age=31536000; includeSubDomains; preload' },
          // Referrer policy — sends origin on cross-origin requests (helps analytics)
          { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
          // Permissions policy — restrict unneeded browser features
          { key: 'Permissions-Policy', value: 'camera=(), microphone=(), geolocation=()' },
          // Content Security Policy — blocks Flash/plugins, base-tag hijacking,
          // and unauthorized framing. script-src retains 'unsafe-inline' because
          // Next.js 14 App Router emits inline hydration scripts; a nonce-based
          // CSP would be required to remove it without breaking the app.
          // 'unsafe-eval' is added in development only for React Fast Refresh (HMR).
          {
            key: 'Content-Security-Policy',
            value: [
              "default-src 'self'",
              `script-src 'self' 'unsafe-inline' ${isDev ? "'unsafe-eval'" : ''} https://www.googletagmanager.com https://www.google-analytics.com`,
              "style-src 'self' 'unsafe-inline'",
              "img-src 'self' data: blob: https:",
              "connect-src 'self' https://www.google-analytics.com https://stats.g.doubleclick.net",
              "font-src 'self' data:",
              "object-src 'none'",
              "base-uri 'self'",
              "form-action 'self'",
              "frame-src https://www.google.com https://maps.google.com",
              "frame-ancestors 'self'",
            ].join('; '),
          },
        ],
      },
    ];
  },

  async redirects() {
    return [
      // preserved has: rules (bare domain → www),
      { source: '/:path*', has: [{ type: 'host', value: 'cosscloudsol.com' }], destination: 'https://www.cosscloudsol.com/:path*', permanent: true, },
      // infrastructure redirects — exact-match (always preserved by sync-redirects),
      { source: '/data-analytics-bi', destination: '/courses/data-analytics-bi', permanent: true },
      { source: '/data-analytics-bi/', destination: '/courses/data-analytics-bi', permanent: true },
      { source: '/software-testing-os', destination: '/courses/software-testing-os', permanent: true },
      { source: '/software-testing-os/', destination: '/courses/software-testing-os', permanent: true },
      { source: '/courses/cyber-security-networking', destination: '/courses/cyber-security', permanent: true },
      { source: '/courses/cyber-security-networking/', destination: '/courses/cyber-security', permanent: true },
      { source: '/courses/programming-full-stack-development', destination: '/courses/programming-full-stack', permanent: true },
      { source: '/courses/programming-full-stack-development/', destination: '/courses/programming-full-stack', permanent: true },
      { source: '/blogs', destination: '/blog', permanent: true },
      { source: '/blogs/', destination: '/blog', permanent: true },
      { source: '/aws-cloud-training-institute-in-hyderabad', destination: '/aws-training-institute-in-hyderabad', permanent: true },
      { source: '/aws-devops-cloud-training-institute-in-hyderabad', destination: '/aws-devops-training-institute-in-hyderabad', permanent: true },
      { source: '/ccna-networking-training-institute-in-hyderabad', destination: '/ccna-training-institute-in-hyderabad', permanent: true },
      { source: '/cloud-computing-training-institute-in-hyderabad', destination: '/courses/multi-cloud-architecture-training-in-hyderabad', permanent: true },
      { source: '/multi-cloud-engineer-training-in-hyderabad', destination: '/courses/multi-cloud-architecture-training-in-hyderabad', permanent: true },
      { source: '/multi-cloud-engineer-training-institute-in-hyderabad', destination: '/courses/multi-cloud-architecture-training-in-hyderabad', permanent: true },
      { source: '/multi-cloud-devops-training-institute-in-hyderabad', destination: '/courses/multi-cloud-architecture-training-in-hyderabad', permanent: true },
      { source: '/cloud-data-engineer-training-in-hyderabad', destination: '/data-engineering-training-institute-in-hyderabad', permanent: true },
      { source: '/cloud-data-engineer-training-institute-in-hyderabad', destination: '/data-engineering-training-institute-in-hyderabad', permanent: true },
      { source: '/communication-skills-training-institute-in-hyderabad', destination: '/communication-skills-training-in-hyderabad', permanent: true },
      { source: '/erp-crm-training-institute-in-hyderabad', destination: '/courses/erp-crm-enterprise-tools/salesforce-admin-developer-training-in-hyderabad', permanent: true },
      { source: '/oracle-fusion-hcm-training-in-hyderabad', destination: '/courses/erp-crm-enterprise-tools/salesforce-admin-developer-training-in-hyderabad', permanent: true },
      { source: '/oracle-fusion-hcm-training-institute-in-hyderabad', destination: '/courses/erp-crm-enterprise-tools/salesforce-admin-developer-training-in-hyderabad', permanent: true },
      { source: '/java-full-stack-training-institute-in-hyderabad', destination: '/java-training-institute-in-hyderabad', permanent: true },
      { source: '/salesforce-crm-training-institute-in-hyderabad', destination: '/salesforce-training-institute-in-hyderabad', permanent: true },
      // DB-managed rules,
      { source: '/digital-marketing-course-dilsukhnagar', destination: '/blog/digital-marketing-course-dilsukhnagar', permanent: true },
      { source: '/best-spoken-english-institute-in-dilsukhnagar-hyderabad-coss-cloud-solutions', destination: '/blog/best-spoken-english-institute-in-dilsukhnagar-hyderabad-coss-cloud-solutions', permanent: true },
      { source: '/best-certification-course-institute-in-ameerpet-hyderabad-coss-cloud-solutions', destination: '/blog/best-certification-course-institute-in-ameerpet-hyderabad-coss-cloud-solutions', permanent: true },
      { source: '/digital-marketing-training-in-dilsukhnagar', destination: '/blog/digital-marketing-training-in-dilsukhnagar', permanent: true },
      { source: '/best-communication-skills-institute-in-dilsukhnagar-hyderabad-coss-cloud-solutions', destination: '/blog/best-communication-skills-institute-in-dilsukhnagar-hyderabad-coss-cloud-solutions', permanent: true },
      { source: '/cloud-computing-training-institute-in-dilsukhnagar-hyderabad', destination: '/blog/cloud-computing-training-institute-in-dilsukhnagar-hyderabad', permanent: true },
      { source: '/data-science-training-dilsukhnagar-hyderabad', destination: '/blog/data-science-training-dilsukhnagar-hyderabad', permanent: true },
      { source: '/top-rated-digital-marketing-institute-in-dilsukhnagar-hyderabad', destination: '/blog/top-rated-digital-marketing-institute-in-dilsukhnagar-hyderabad', permanent: true },
      { source: '/full-stack-power-bi-training-in-dilsukhnagar-hyderabad', destination: '/blog/full-stack-power-bi-training-in-dilsukhnagar-hyderabad', permanent: true },
      { source: '/azure-data-engineer-training-in-dilsukhnagar-hyderabad', destination: '/blog/azure-data-engineer-training-in-dilsukhnagar-hyderabad', permanent: true },
      { source: '/best-cyber-security-institute-in-dilsukhnagar-hyderabad-coss-cloud-solutions', destination: '/blog/best-cyber-security-institute-in-dilsukhnagar-hyderabad-coss-cloud-solutions', permanent: true },
      { source: '/machine-learning-training-in-dilsukhnagar-hyderabad', destination: '/blog/machine-learning-training-in-dilsukhnagar-hyderabad', permanent: true },
      { source: '/data-science-training-institute-in-dilsukhnagar-coss-cloud-solutions', destination: '/blog/data-science-training-institute-in-dilsukhnagar-coss-cloud-solutions', permanent: true },
      { source: '/best-tally-institute-in-hyderabad-coss-cloud-solutions', destination: '/blog/best-tally-institute-in-hyderabad-coss-cloud-solutions', permanent: true },
      { source: '/digital-marketing-course-in-hyderabad', destination: '/blog/digital-marketing-course-in-hyderabad', permanent: true },
      { source: '/best-ethical-hacking-institute-in-dilsukhnagar-hyderabad-coss-cloud-solutions', destination: '/blog/best-ethical-hacking-institute-in-dilsukhnagar-hyderabad-coss-cloud-solutions', permanent: true },
      { source: '/best-java-institute-in-dilsukhnagar-hyderabad-coss-cloud-solution', destination: '/blog/best-java-institute-in-dilsukhnagar-hyderabad-coss-cloud-solution', permanent: true },
      { source: '/learn-azure-devops-in-dilsukhnagar-hyderabad-with-coss-cloud-solutions', destination: '/blog/learn-azure-devops-in-dilsukhnagar-hyderabad-with-coss-cloud-solutions', permanent: true },
      { source: '/artificial-intelligence-training-in-dilsukhnagar-with-coss-cloud-solutions', destination: '/blog/artificial-intelligence-training-in-dilsukhnagar-with-coss-cloud-solutions', permanent: true },
      { source: '/best-python-institute-in-hyderabad-coss-cloud-solutions', destination: '/blog/best-python-institute-in-hyderabad-coss-cloud-solutions', permanent: true },
      { source: '/full-stack-power-bi-training-in-hyderabad', destination: '/blog/full-stack-power-bi-training-in-hyderabad', permanent: true },
      { source: '/digital-marketing-course-training-dilsukhnagar-hyderabad', destination: '/blog/digital-marketing-course-training-dilsukhnagar-hyderabad', permanent: true },
      { source: '/best-communication-skills-institute-in-hyderabad-coss-cloud-solutions', destination: '/blog/best-communication-skills-institute-in-hyderabad-coss-cloud-solutions', permanent: true },
      { source: '/learn-ms-office-in-dilsukhnagar-hyderabad-by-coss-cloud-solutions', destination: '/blog/learn-ms-office-in-dilsukhnagar-hyderabad-by-coss-cloud-solutions', permanent: true },
      { source: '/data-science-training-in-hyderabad', destination: '/blog/data-science-training-in-hyderabad', permanent: true },
      { source: '/best-python-institute-in-dilsukhnagar-hyderabad-coss-cloud-solutions', destination: '/blog/best-python-institute-in-dilsukhnagar-hyderabad-coss-cloud-solutions', permanent: true },
      { source: '/best-certification-course-institute-in-dilsukhnagar-hyderabad-coss-cloud-solutions', destination: '/blog/best-certification-course-institute-in-dilsukhnagar-hyderabad-coss-cloud-solutions', permanent: true },
      { source: '/best-digital-marketing-institute-in-hyderabad-coss-cloud-solutions', destination: '/blog/best-digital-marketing-institute-in-hyderabad-coss-cloud-solutions', permanent: true },
      { source: '/aws-devops-multi-cloud-course-dilsukhnagar', destination: '/blog/aws-devops-multi-cloud-course-dilsukhnagar', permanent: true },
      { source: '/devops-training-in-dilsukhnagar', destination: '/blog/devops-training-in-dilsukhnagar', permanent: true },
      { source: '/best-linux-institute-in-dilsukhnagar-hyderabad-coss-cloud-solution', destination: '/blog/best-linux-institute-in-dilsukhnagar-hyderabad-coss-cloud-solution', permanent: true },
      { source: '/best-certification-course-institute-in-kukatpally-hyderabad-coss-cloud-solutions', destination: '/blog/best-certification-course-institute-in-kukatpally-hyderabad-coss-cloud-solutions', permanent: true },
      { source: '/best-linux-training-institute-in-dilsukhnagarhyderabad', destination: '/blog/best-linux-training-institute-in-dilsukhnagarhyderabad', permanent: true },
      { source: '/job-opportunities-for-devops-professionals-in-hyderabad', destination: '/blog/job-opportunities-for-devops-professionals-in-hyderabad', permanent: true },
      { source: '/digital-marketing-training-in-dilsukhnagar-hyderabad-with-coss-cloud-solutions', destination: '/blog/digital-marketing-training-in-dilsukhnagar-hyderabad-with-coss-cloud-solutions', permanent: true },
      { source: '/learn-azure-cloud-with-coss-cloud-solutions-in-hyderabad', destination: '/blog/learn-azure-cloud-with-coss-cloud-solutions-in-hyderabad', permanent: true },
      { source: '/best-azure-devops-institute-in-dilsukhnagar-hyderabad-coss-cloud-solution', destination: '/blog/best-azure-devops-institute-in-dilsukhnagar-hyderabad-coss-cloud-solution', permanent: true },
      { source: '/data-analytics-training-in-hyderabad', destination: '/blog/data-analytics-training-in-hyderabad', permanent: true },
      { source: '/best-full-stack-java-training-institute-in-dilsukhnagar-hyderabad-coss-cloud-solutions', destination: '/blog/best-full-stack-java-training-institute-in-dilsukhnagar-hyderabad-coss-cloud-solutions', permanent: true },
      { source: '/learn-aws-devops-from-industry-experts-at-coss-cloud-solutions-hyderabad', destination: '/blog/learn-aws-devops-from-industry-experts-at-coss-cloud-solutions-hyderabad', permanent: true },
      { source: '/best-ms-office-institute-in-hyderabad-coss-cloud-solutions', destination: '/blog/best-ms-office-institute-in-hyderabad-coss-cloud-solutions', permanent: true },
      { source: '/join-our-industry-leading-aws-cloud-institute-in-dilsukhnagar-hyderabad', destination: '/blog/join-our-industry-leading-aws-cloud-institute-in-dilsukhnagar-hyderabad', permanent: true },
      { source: '/cloud-computing-classes-with-coss-cloud-solutions-in-hyderabad', destination: '/blog/cloud-computing-classes-with-coss-cloud-solutions-in-hyderabad', permanent: true },
      { source: '/advance-your-career-at-the-top-devops-institute-in-dilsukhnagar-coss-cloud-solutions', destination: '/blog/advance-your-career-at-the-top-devops-institute-in-dilsukhnagar-coss-cloud-solutions', permanent: true },
      { source: '/cloud-computing-training-in-hyderabad-the-best-career-move-in-2025', destination: '/blog/cloud-computing-training-in-hyderabad-the-best-career-move-in-2025', permanent: true },
      { source: '/get-placed-with-coss-cloud-solutions-corporate-training-in-hyderabad', destination: '/blog/get-placed-with-coss-cloud-solutions-corporate-training-in-hyderabad', permanent: true },
      { source: '/best-google-cloud-institute-in-dilsukhnagar-hyderabad-coss-cloud-solution', destination: '/blog/best-google-cloud-institute-in-dilsukhnagar-hyderabad-coss-cloud-solution', permanent: true },
      { source: '/best-ms-office-institute-in-dilsukhnagar-hyderabad-coss-cloud-solutions', destination: '/blog/best-ms-office-institute-in-dilsukhnagar-hyderabad-coss-cloud-solutions', permanent: true },
      { source: '/devops-training-in-hyderabad-with-coss-cloud-solutions', destination: '/blog/devops-training-in-hyderabad-with-coss-cloud-solutions', permanent: true },
      { source: '/best-ethical-hacking-institute-in-hyderabad-coss-cloud-solutions', destination: '/blog/best-ethical-hacking-institute-in-hyderabad-coss-cloud-solutions', permanent: true },
      { source: '/sap-fico-training-in-hyderabad', destination: '/blog/sap-fico-training-in-hyderabad', permanent: true },
      { source: '/soc-analyst-training-hyderabad', destination: '/blog/soc-analyst-training-hyderabad', permanent: true },
      { source: '/best-microsoft-office-training-institute-in-dilsukhnagar-hyderabad-coss-cloud-solutions', destination: '/blog/best-microsoft-office-training-institute-in-dilsukhnagar-hyderabad-coss-cloud-solutions', permanent: true },
      { source: '/sql-mysql-postgresql-training-in-dilsukhnagar-hyderabad', destination: '/blog/sql-mysql-postgresql-training-in-dilsukhnagar-hyderabad', permanent: true },
      { source: '/artificial-intelligence-training-in-hyderabad', destination: '/blog/artificial-intelligence-training-in-hyderabad', permanent: true },
      { source: '/azure-devops-training-dilsukhnagar-hyderabad', destination: '/blog/azure-devops-training-dilsukhnagar-hyderabad', permanent: true },
      { source: '/best-azure-cloud-institute-in-dilsukhnagar-hyderabad-coss-cloud-solution', destination: '/blog/best-azure-cloud-institute-in-dilsukhnagar-hyderabad-coss-cloud-solution', permanent: true },
      { source: '/cyber-security-training-dilsukhnagar-hyderabad', destination: '/blog/cyber-security-training-dilsukhnagar-hyderabad', permanent: true },
      { source: '/machine-learning-training-in-hyderabad', destination: '/blog/machine-learning-training-in-hyderabad', permanent: true },
      { source: '/best-salesforce-institute-dilsukhnagar-hyderabad-coss-cloud-solutions', destination: '/blog/best-salesforce-institute-dilsukhnagar-hyderabad-coss-cloud-solutions', permanent: true },
      { source: '/digital-marketing-classes-in-hyderabad', destination: '/blog/digital-marketing-classes-in-hyderabad', permanent: true },
      { source: '/best-tally-institute-in-dilsukhnagar-hyderabad-coss-cloud-solutions', destination: '/blog/best-tally-institute-in-dilsukhnagar-hyderabad-coss-cloud-solutions', permanent: true },
      { source: '/digital-marketing-institute-in-kukatpally-hyderabad-coss-cloud-solutions', destination: '/blog/digital-marketing-institute-in-kukatpally-hyderabad-coss-cloud-solutions', permanent: true },
      { source: '/data-analytics-institute-in-dilsukhnagar-hyderabad', destination: '/blog/data-analytics-institute-in-dilsukhnagar-hyderabad', permanent: true },
      { source: '/best-digital-marketing-institute-in-ameerpet-hyderabad-coss-cloud-solutions', destination: '/blog/best-digital-marketing-institute-in-ameerpet-hyderabad-coss-cloud-solutions', permanent: true },
      { source: '/best-aws-institutes-in-hyderabad-coss-cloud-solutions', destination: '/blog/best-aws-institutes-in-hyderabad-coss-cloud-solutions', permanent: true },
      { source: '/best-digital-marketing-institute-in-hyderabad-coss-cloud-solutions-2', destination: '/blog/best-digital-marketing-institute-in-hyderabad-coss-cloud-solutions-2', permanent: true },
      { source: '/best-cyber-security-institute-in-hyderabad-coss-cloud-solutions', destination: '/blog/best-cyber-security-institute-in-hyderabad-coss-cloud-solutions', permanent: true },
      { source: '/aws-cloud-course-training-in-hyderabad-with-coss-cloud-solutions', destination: '/blog/aws-cloud-course-training-in-hyderabad-with-coss-cloud-solutions', permanent: true },
      { source: '/learn-ethical-hacking-in-hyderabad-with-coss-cloud-solutions', destination: '/blog/learn-ethical-hacking-in-hyderabad-with-coss-cloud-solutions', permanent: true },
      { source: '/learn-aws-devops-in-hyderabad-with-coss-cloud-solutions', destination: '/blog/learn-aws-devops-in-hyderabad-with-coss-cloud-solutions', permanent: true },
      { source: '/cloud-computing-future-in-hyderabad-with-coss-cloud-solutions', destination: '/blog/cloud-computing-future-in-hyderabad-with-coss-cloud-solutions', permanent: true },
      { source: '/grow-your-skills-with-cloud-computing-in-hyderabad-coss-cloud-solutions', destination: '/blog/grow-your-skills-with-cloud-computing-in-hyderabad-coss-cloud-solutions', permanent: true },
      { source: '/learn-digital-marketing-in-dilsukhnagar-hyderabad-with-coss-cloud-solutions', destination: '/blog/learn-digital-marketing-in-dilsukhnagar-hyderabad-with-coss-cloud-solutions', permanent: true },
      { source: '/learn-tally-in-dilsukhnagar-hyderabad-by-coss-cloud-solutions', destination: '/blog/learn-tally-in-dilsukhnagar-hyderabad-by-coss-cloud-solutions', permanent: true },
      { source: '/devops-institute-in-dilsukhnagar-hyderabad', destination: '/blog/devops-institute-in-dilsukhnagar-hyderabad', permanent: true },
      { source: '/data-engineer-course-training-hyderabad', destination: '/blog/data-engineer-course-training-hyderabad', permanent: true },
      { source: '/learn-linux-with-coss-cloud-solutions-in-dilsukhnagar-hyderabad', destination: '/blog/learn-linux-with-coss-cloud-solutions-in-dilsukhnagar-hyderabad', permanent: true },
      { source: '/best-certification-course-institute-in-hyderabad-coss-cloud-solutions', destination: '/blog/best-certification-course-institute-in-hyderabad-coss-cloud-solutions', permanent: true },
      { source: '/best-institute-for-devops-in-hyderabad-coss-cloud-solutions', destination: '/blog/best-institute-for-devops-in-hyderabad-coss-cloud-solutions', permanent: true },
      { source: '/best-digital-marketing-course-in-dilsukhnagar-coss-cloud-solutions', destination: '/blog/best-digital-marketing-course-in-dilsukhnagar-coss-cloud-solutions', permanent: true },
      { source: '/best-digital-marketing-institute-in-dilsukhnagar-hyderabad-coss-cloud-solutions', destination: '/blog/best-digital-marketing-institute-in-dilsukhnagar-hyderabad-coss-cloud-solutions', permanent: true },
      { source: '/coss-cloud-solutions-best-linux-training-institute-in-dilsukhnagar-hyderabad', destination: '/blog/coss-cloud-solutions-best-linux-training-institute-in-dilsukhnagar-hyderabad', permanent: true },
      { source: '/how-to-learn-aws-cloud-for-beginners', destination: '/blog/how-to-learn-aws-cloud-for-beginners', permanent: true },
      { source: '/aws-cloud-training-advantages-with-coss-cloud-solutions-in-hyderabad', destination: '/blog/aws-cloud-training-advantages-with-coss-cloud-solutions-in-hyderabad', permanent: true },
      { source: '/learning-tally-with-coss-cloud-solutions-in-dilsukhnagar-hyderabad', destination: '/blog/learning-tally-with-coss-cloud-solutions-in-dilsukhnagar-hyderabad', permanent: true },
      { source: '/azure-data-engineer-training-in-hyderabad', destination: '/courses/data-engineering/azure-data-factory-training-in-hyderabad', permanent: true },
      { source: '/cloud-computing-training-institute-in-ameerpet-hyderabad', destination: '/courses/cloud-computing', permanent: true },
      { source: '/cloud-computing-classes-in-hyderabad', destination: '/courses/cloud-computing', permanent: true },
      { source: '/cloud-computing-training-in-madhapur-hyderabad', destination: '/courses/cloud-computing', permanent: true },
      { source: '/cloud-computing-training-institute-in-kukatpally-hyderabad', destination: '/courses/cloud-computing', permanent: true },
      { source: '/cloud-computing', destination: '/courses/cloud-computing', permanent: true },
      { source: '/cloud-technology-course-in-hyderabad', destination: '/courses/cloud-computing', permanent: true },
      { source: '/aws-cloud-training-institute-in-ameerpet-hyderabad', destination: '/aws-training-institute-in-hyderabad', permanent: true },
      { source: '/aws-cloud-training-institute-in-dilsukhnagar-hyderabad', destination: '/aws-training-institute-in-hyderabad', permanent: true },
      { source: '/aws-cloud-training-institute-in-madhapur-hyderabad', destination: '/aws-training-institute-in-hyderabad', permanent: true },
      { source: '/aws-course-in-hyderabad', destination: '/aws-training-institute-in-hyderabad', permanent: true },
      { source: '/aws-cloud-institute-in-hyderabad', destination: '/aws-training-institute-in-hyderabad', permanent: true },
      { source: '/azure-cloud-training-institute-in-dilsukhnagar-hyderabad', destination: '/azure-training-institute-in-hyderabad', permanent: true },
      { source: '/microsoft-azure-training-in-hyderabad', destination: '/azure-training-institute-in-hyderabad', permanent: true },
      { source: '/devops-training-institute-in-ameerpet-hyderabad', destination: '/devops-training-institute-in-hyderabad', permanent: true },
      { source: '/devops-training-institute-in-madhapur-hyderabad', destination: '/devops-training-institute-in-hyderabad', permanent: true },
      { source: '/devops-training-institute-in-dilsukhnagar-hyderabad', destination: '/devops-training-institute-in-hyderabad', permanent: true },
      { source: '/devops-training-institute-in-kukatpally-hyderabad', destination: '/devops-training-institute-in-hyderabad', permanent: true },
      { source: '/aws-devops-training-in-hyderabad', destination: '/aws-devops-training-institute-in-hyderabad', permanent: true },
      { source: '/master-aws-devops-in-hyderabad-with-coss-cloud-solutions', destination: '/aws-devops-training-institute-in-hyderabad', permanent: true },
      { source: '/devops-with-aws-training-in-hyderabad-by-coss-cloud-solutions', destination: '/courses/devops-multi-cloud', permanent: true },
      { source: '/azure-devops-in-hyderabad-coss-cloud-solutions', destination: '/azure-devops-training-institute-in-hyderabad', permanent: true },
      { source: '/linux-training-institute-in-kukatpally-hyderabad', destination: '/linux-administration-training-institute-in-hyderabad', permanent: true },
      { source: '/linux-training-institute-in-ameerpet-hyderabad', destination: '/linux-administration-training-institute-in-hyderabad', permanent: true },
      { source: '/linux-training-institute-in-dilsukhnagar-hyderabad', destination: '/linux-administration-training-institute-in-hyderabad', permanent: true },
      { source: '/linux-training-institute-in-madhapur-hyderabad', destination: '/linux-administration-training-institute-in-hyderabad', permanent: true },
      { source: '/linux-administration-training-in-hyderabad', destination: '/linux-administration-training-institute-in-hyderabad', permanent: true },
      { source: '/linux-operating-system-training-in-hyderabad-by-coss-cloud-solutions', destination: '/linux-administration-training-institute-in-hyderabad', permanent: true },
      { source: '/linux-classes-near-me-in-hyderabad-coss-cloud-solutions', destination: '/linux-administration-training-institute-in-hyderabad', permanent: true },
      { source: '/linux-institutes-near-me-in-hyderabad-coss-cloud-solutions', destination: '/linux-administration-training-institute-in-hyderabad', permanent: true },
      { source: '/linux-course-in-hyderabad-by-coss-cloud-solutions', destination: '/linux-administration-training-institute-in-hyderabad', permanent: true },
      { source: '/linux-training-in-hyderabad-by-coss-cloud-solutions', destination: '/linux-administration-training-institute-in-hyderabad', permanent: true },
      { source: '/python-training-institute-in-dilsukhnagar-hyderabad', destination: '/python-training-institute-in-hyderabad', permanent: true },
      { source: '/python-institute-in-hyderabad-by-coss-cloud-solutions', destination: '/python-training-institute-in-hyderabad', permanent: true },
      { source: '/java-full-stack-developer-course-in-hyderabad-with-coss-cloud-solutions', destination: '/java-training-institute-in-hyderabad', permanent: true },
      { source: '/java-language-course-in-hyderabad', destination: '/java-training-institute-in-hyderabad', permanent: true },
      { source: '/java-course-near-me-in-hyderabad-coss-cloud-solutions', destination: '/java-training-institute-in-hyderabad', permanent: true },
      { source: '/full-stack-developer-training-in-hyderabad', destination: '/courses/programming-full-stack/full-stack-java-developer-training-in-hyderabad', permanent: true },
      { source: '/best-azure-data-engineer-training-in-hyderabad', destination: '/azure-data-engineer-training-institute-in-hyderabad', permanent: true },
      { source: '/data-science-training-institute-in-hyderabad', destination: '/courses/data-science-training-institute-in-hyderabad', permanent: true },
      { source: '/data-analytics-training-institute-in-hyderabad', destination: '/courses/data-analytics-training-institute-in-hyderabad', permanent: true },
      { source: '/machine-learning-ml-training-institute-in-hyderabad', destination: '/machine-learning-training-institute-in-hyderabad', permanent: true },
      { source: '/digital-marketing-institute-in-dilsukhnagar-hyderabad', destination: '/digital-marketing-training-institute-in-hyderabad', permanent: true },
      { source: '/digital-marketing-classes-in-hyderabad-by-coss-cloud-solutions', destination: '/digital-marketing-training-institute-in-hyderabad', permanent: true },
      { source: '/digital-marketing-course-near-me-in-hyderabad', destination: '/digital-marketing-training-institute-in-hyderabad', permanent: true },
      { source: '/register-digital-marketing-classes-in-hyderabad-with-coss-cloud-solutions', destination: '/digital-marketing-training-institute-in-hyderabad', permanent: true },
      { source: '/digital-marketing-coaching-centre-near-me-in-hyderabad', destination: '/digital-marketing-training-institute-in-hyderabad', permanent: true },
      { source: '/enroll-for-digital-marketing-course-in-hyderabad-with-coss-cloud-solutions', destination: '/digital-marketing-training-institute-in-hyderabad', permanent: true },
      { source: '/tally-training-institute-in-dilsukhnagar-hyderabad', destination: '/tally-erp-training-institute-in-hyderabad', permanent: true },
      { source: '/tally-courses-in-hyderabad-by-coss-cloud-solutions', destination: '/tally-erp-training-institute-in-hyderabad', permanent: true },
      { source: '/tally-courses-in-hyderabad-with-coss-cloud-solutions', destination: '/tally-erp-training-institute-in-hyderabad', permanent: true },
      { source: '/tally-classes-near-me-in-hyderabad-by-coss-cloud-solutions', destination: '/tally-erp-training-institute-in-hyderabad', permanent: true },
      { source: '/ms-office-training-institute-in-dilsukhnagar-hyderabad', destination: '/ms-office-training-institute-in-hyderabad', permanent: true },
      { source: '/ms-office-course-near-me-in-hyderabad-coss-cloud-solutions', destination: '/ms-office-training-institute-in-hyderabad', permanent: true },
      { source: '/certification-in-hyderabad', destination: '/certification', permanent: true },
      { source: '/sql-training-in-hyderabad', destination: '/sql-training-institute-in-hyderabad', permanent: true },
      { source: '/learn-spoken-english-in-hyderabad-with-coss-cloud-solution', destination: '/spoken-english-training-institute-in-hyderabad', permanent: true },
      { source: '/computer-classes-near-me-in-hyderabad-coss-cloud-solutions', destination: '/courses', permanent: true },
      { source: '/computer-training-near-me-in-hyderabad-coss-cloud-solutions', destination: '/courses', permanent: true },
      { source: '/computer-institutes-near-me-in-hyderabad-coss-cloud-solutions', destination: '/courses', permanent: true },
      { source: '/it-training-institute-dilsukhnagar', destination: '/courses', permanent: true },
      { source: '/communication-skills-training-in-hyderabad-coss-cloud-solutions', destination: '/communication-skills-training-in-hyderabad', permanent: true },
      { source: '/spoken-english-institute-in-hyderabad-coss-cloud-solutions', destination: '/spoken-english-training-institute-in-hyderabad', permanent: true },
      { source: '/ethical-hacking-in-hyderabad-coss-cloud-solutions', destination: '/ethical-hacking-training-institute-in-hyderabad', permanent: true },
      { source: '/redhat-linux-certification-course-in-hyderabad', destination: '/linux-administration-training-institute-in-hyderabad', permanent: true },
      { source: '/full-stack-power-bi-training-institute-in-hyderabad', destination: '/power-bi-training-institute-in-hyderabad', permanent: true },
      { source: '/sap-fico-training-institute-in-hyderabad', destination: '/courses/erp-crm-enterprise-tools/sap-fico-training-institute-in-hyderabad', permanent: true },
      { source: '/aws-devops-in-hyderabad', destination: '/aws-devops-training-institute-in-hyderabad', permanent: true },
      { source: '/artificial-intelligence-ai-training-institute-in-hyderabad', destination: '/artificial-intelligence-training-institute-in-hyderabad', permanent: true },
      { source: '/azure-devops-courses-in-hyderabad-by-coss-cloud-solutions', destination: '/azure-devops-training-institute-in-hyderabad', permanent: true },
      { source: '/aws-devops-course-in-hyderabad-by-coss-cloud-solutions', destination: '/aws-devops-training-institute-in-hyderabad', permanent: true },
      { source: '/aws-cloud-training-in-hyderabad', destination: '/aws-training-institute-in-hyderabad', permanent: true },
      { source: '/digital-marketing-training-institute-in-dilsukhnagar-hyderabad', destination: '/digital-marketing-training-institute-in-hyderabad', permanent: true },
      { source: '/ccna-networking-training-in-hyderabad', destination: '/ccna-training-institute-in-hyderabad', permanent: true },
      { source: '/sql-mysql-postgresql-training-in-hyderabad', destination: '/sql-training-institute-in-hyderabad', permanent: true },
      { source: '/tally-classes-in-hyderabad', destination: '/tally-erp-training-institute-in-hyderabad', permanent: true },
      { source: '/ui-ux-design-training-in-hyderabad', destination: '/ui-ux-design-training-institute-in-hyderabad', permanent: true },
      { source: '/linux-training-in-hyderabad', destination: '/linux-administration-training-institute-in-hyderabad', permanent: true },
      { source: '/devops-training-in-hyderabad', destination: '/devops-training-institute-in-hyderabad', permanent: true },
      { source: '/digital-marketing-course-in-hyderabad-by-coss-cloud-solutions', destination: '/digital-marketing-training-institute-in-hyderabad', permanent: true },
      { source: '/oracle-fusion-cloud-hcm-training-in-hyderabad', destination: '/courses/erp-crm-enterprise-tools/salesforce-admin-developer-training-in-hyderabad', permanent: true },
      { source: '/salesforce-training-center-in-hyderabad', destination: '/salesforce-training-institute-in-hyderabad', permanent: true },
      { source: '/big-data-training-in-hyderabad', destination: '/big-data-training-institute-in-hyderabad', permanent: true },
      { source: '/branches', destination: '/contact-us', permanent: true },
      { source: '/gallery', destination: '/about-us', permanent: true },
      { source: '/our-team', destination: '/about-us', permanent: true },
      { source: '/results', destination: '/student-reviews', permanent: true },
      { source: '/downloads', destination: '/', permanent: true },
      { source: '/app', destination: '/', permanent: true },
      { source: '/1-home', destination: '/', permanent: true },
      { source: '/book-a-free-demo-class', destination: '/free-demo-class', permanent: true },
      { source: '/sap-fico-training-institute-in-hyderabad-coss-cloud-solutions', destination: '/courses/erp-crm-enterprise-tools/sap-fico-training-institute-in-hyderabad', permanent: true },
      { source: '/training-institutes-in-hyderabad/dilsukhnagar', destination: '/locations/dilsukhnagar', permanent: true },
      { source: '/training-institutes-in-hyderabad/kukatpally', destination: '/locations/kukatpally', permanent: true },
      { source: '/training-institutes-in-hyderabad/madhapur', destination: '/locations/madhapur-hitec-city', permanent: true },
      { source: '/training-institutes-in-hyderabad/dilsukhnagar/devops-training-dilsukhnagar-hyderabad', destination: '/devops-training-institute-in-hyderabad', permanent: true },
      { source: '/training-institutes-in-hyderabad/ameerpet/linux-training-ameerpet-hyderabad', destination: '/linux-administration-training-institute-in-hyderabad', permanent: true },
      { source: '/training-institutes-in-hyderabad/ameerpet/cloud-computing-training-ameerpet-hyderabad', destination: '/courses/cloud-computing', permanent: true },
      { source: '/training-institutes-in-hyderabad/ameerpet/devops-training-ameerpet-hyderabad', destination: '/devops-training-institute-in-hyderabad', permanent: true },
      { source: '/training-institutes-in-hyderabad/ameerpet/aws-cloud-training-ameerpet-hyderabad', destination: '/aws-training-institute-in-hyderabad', permanent: true },
      { source: '/training-institutes-in-hyderabad/dilsukhnagar/cloud-computing-training-dilsukhnagar-hyderabad', destination: '/courses/cloud-computing', permanent: true },
      { source: '/training-institutes-in-hyderabad/madhapur/cloud-computing-training-madhapur-hyderabad', destination: '/courses/cloud-computing', permanent: true },
      { source: '/training-institutes-in-hyderabad/madhapur/aws-cloud-training-madhapur-hyderabad', destination: '/aws-training-institute-in-hyderabad', permanent: true },
      { source: '/training-institutes-in-hyderabad/madhapur/devops-training-madhapur-hyderabad', destination: '/devops-training-institute-in-hyderabad', permanent: true },
      { source: '/training-institutes-in-hyderabad/kukatpally/linux-training-kukatpally-hyderabad', destination: '/linux-administration-training-institute-in-hyderabad', permanent: true },
      { source: '/training-institutes-in-hyderabad/kukatpally/cloud-computing-training-kukatpally-hyderabad', destination: '/courses/cloud-computing', permanent: true },
      { source: '/training-institutes-in-hyderabad/dilsukhnagar/linux-training-dilsukhnagar-hyderabad', destination: '/linux-administration-training-institute-in-hyderabad', permanent: true },
      { source: '/training-institutes-in-hyderabad/dilsukhnagar/aws-cloud-training-dilsukhnagar-hyderabad', destination: '/aws-training-institute-in-hyderabad', permanent: true },
      { source: '/training-institutes-in-hyderabad/dilsukhnagar/azure-cloud-training-dilsukhnagar-hyderabad', destination: '/azure-training-institute-in-hyderabad', permanent: true },
      { source: '/training-institutes-in-hyderabad/madhapur/azure-cloud-training-madhapur-hyderabad', destination: '/azure-training-institute-in-hyderabad', permanent: true },
      { source: '/training-institutes-in-hyderabad/kukatpally/azure-cloud-training-kukatpally-hyderabad', destination: '/azure-training-institute-in-hyderabad', permanent: true },
      { source: '/training-institutes-in-hyderabad/ameerpet/azure-cloud-training-ameerpet-hyderabad', destination: '/azure-training-institute-in-hyderabad', permanent: true },
      { source: '/training-institutes-in-hyderabad/aws-training-institute-in-hyderabad', destination: '/aws-training-institute-in-hyderabad', permanent: true },
      { source: '/training-institutes-in-hyderabad/devops-training-in-hyderabad', destination: '/devops-training-institute-in-hyderabad', permanent: true },
      { source: '/training-institutes-in-hyderabad/linux-training-institute-in-hyderabad', destination: '/linux-administration-training-institute-in-hyderabad', permanent: true },
      { source: '/training-institutes-in-hyderabad/linux-training-in-hyderabad', destination: '/linux-administration-training-institute-in-hyderabad', permanent: true },
      { source: '/training-institutes-in-hyderabad/cloud-computing-training-in-hyderabad', destination: '/courses/cloud-computing', permanent: true },
      { source: '/training-institutes-in-hyderabad/cloud-computing-institute-in-hyderabad', destination: '/courses/cloud-computing', permanent: true },
      { source: '/training-institutes-in-hyderabad/cloud-computing-training-institute-in-hyderabad', destination: '/courses/cloud-computing', permanent: true },
      { source: '/training-institutes-in-hyderabad/azure-training-institute-in-hyderabad', destination: '/azure-training-institute-in-hyderabad', permanent: true },
      { source: '/training-institutes-in-hyderabad/azure-cloud-training-in-hyderabad', destination: '/azure-training-institute-in-hyderabad', permanent: true },
      { source: '/training-institutes-in-hyderabad/kukatpally/devops-training-kukatpally-hyderabad', destination: '/devops-training-institute-in-hyderabad', permanent: true },
      { source: '/training-institutes-in-hyderabad/kukatpally/aws-cloud-training-kukatpally-hyderabad', destination: '/aws-training-institute-in-hyderabad', permanent: true },
      { source: '/training-institutes-in-hyderabad/ameerpet', destination: '/locations/ameerpet', permanent: true },
      { source: '/coaching-centres-in-hyderabad/cloud-computing-coaching-in-hyderabad', destination: '/courses/cloud-computing', permanent: true },
      { source: '/coaching-centres-in-hyderabad/azure-cloud-coaching-in-hyderabad', destination: '/azure-training-institute-in-hyderabad', permanent: true },
      { source: '/coaching-centres-in-hyderabad/devops-coaching-in-hyderabad', destination: '/devops-training-institute-in-hyderabad', permanent: true },
      { source: '/coaching-centres-in-hyderabad/aws-cloud-coaching-in-hyderabad', destination: '/aws-training-institute-in-hyderabad', permanent: true },
      { source: '/coaching-centres-in-hyderabad/linux-coaching-in-hyderabad', destination: '/linux-administration-training-institute-in-hyderabad', permanent: true },
      { source: '/branches/java-training-institute-in-dilsukhnagar-hyderabad', destination: '/java-training-institute-in-hyderabad', permanent: true },
      { source: '/sql/mysql/postgresql-training-in-hyderabad', destination: '/sql-training-institute-in-hyderabad', permanent: true },
      { source: '/sql/mysql/postgresql-training-institute-in-hyderabad', destination: '/sql-training-institute-in-hyderabad', permanent: true },
      { source: '/courses/cloud-data-engineer-training-in-hyderabad', destination: '/data-engineering-python-training-in-hyderabad', permanent: true },
      { source: '/courses/oracle-fusion-cloud-hcm-training-in-hyderabad', destination: '/salesforce-admin-developer-training-in-hyderabad', permanent: true },
      { source: '/courses/salesforce-training-center-in-hyderabad', destination: '/salesforce-training-institute-in-hyderabad', permanent: true },
      { source: '/courses/multi-cloud-engineer-training-in-hyderabad', destination: '/multi-cloud-architecture-training-in-hyderabad', permanent: true },
      { source: '/digital-marketing-course-in-hyderabad-with-coss-cloud-solutions', destination: '/digital-marketing-training-institute-in-hyderabad', permanent: true },
      { source: '/courses/tally-classes-in-hyderabad', destination: '/tally-erp-training-institute-in-hyderabad', permanent: true },
      { source: '/courses/ms-office', destination: '/ms-office-training-institute-in-hyderabad', permanent: true },
      { source: '/python-full-stack-course-in-hyderabad-with-coss-cloud-solutions', destination: '/python-training-institute-in-hyderabad', permanent: true },
      { source: '/courses/aws-cloud-training-center-in-hyderabad', destination: '/aws-solutions-architect-training-in-hyderabad', permanent: true },
      { source: '/courses/data-science', destination: '/courses/data-analytics-bi', permanent: true },
      { source: '/courses/linux-training-center-in-hyderabad', destination: '/linux-shell-scripting-training-in-hyderabad', permanent: true },
      { source: '/courses/linux', destination: '/linux-shell-scripting-training-in-hyderabad', permanent: true },
      { source: '/courses/sql-mysql-postgresql', destination: '/sql-data-analytics-training-hyderabad', permanent: true },
      { source: '/courses/data-engineering/apache-kafka-training-institute-in-hyderabad', destination: '/courses/data-engineering/apache-kafka-training-in-hyderabad', permanent: true },
      { source: '/courses/data-engineering/apache-spark-data-engineering-training-hyderabad', destination: '/courses/data-engineering/apache-spark-training-in-hyderabad', permanent: true },
      { source: '/courses/software-testing-os/api-testing-postman-training-hyderabad', destination: '/courses/software-testing-os/api-testing-postman-training-in-hyderabad', permanent: true },
      { source: '/courses/professional-soft-skills/business-communication-english-training-hyderabad', destination: '/courses/professional-soft-skills/business-communication-english-training-in-hyderabad', permanent: true },
      { source: '/courses/business-communication-training-in-hyderabad', destination: '/courses/professional-soft-skills/business-communication-english-training-in-hyderabad', permanent: true },
      { source: '/courses/comptia-security-plus-training-in-hyderabad', destination: '/courses/cyber-security/comptia-security-plus-training-hyderabad', permanent: true },
      { source: '/courses/digital-design/digital-marketing-training-institute-in-hyderabad', destination: '/courses/digital-design/digital-marketing-training-in-hyderabad', permanent: true },
      { source: '/courses/full-stack-java-training-in-hyderabad', destination: '/courses/programming-full-stack/full-stack-java-developer-training-in-hyderabad', permanent: true },
      { source: '/courses/professional-soft-skills/interview-prep-resume-building-training-in-hyderabad', destination: '/courses/professional-soft-skills/interview-prep-resume-building-hyderabad', permanent: true },
      { source: '/courses/software-testing-os/linux-shell-scripting-training-hyderabad', destination: '/courses/software-testing-os/linux-shell-scripting-training-in-hyderabad', permanent: true },
      { source: '/courses/software-testing-os/manual-testing-certification-training-in-hyderabad', destination: '/courses/software-testing-os/manual-testing-training-in-hyderabad', permanent: true },
      { source: '/courses/manual-testing-training-institute-in-hyderabad', destination: '/courses/software-testing-os/manual-testing-training-in-hyderabad', permanent: true },
      { source: '/courses/cloud-computing/azure-administrator-certification-training-hyderabad', destination: '/courses/azure-administrator-training-in-hyderabad', permanent: true },
      { source: '/courses/erp-crm-enterprise-tools/salesforce-admin-developer-training-hyderabad', destination: '/courses/erp-crm-enterprise-tools/salesforce-admin-developer-training-in-hyderabad', permanent: true },
      { source: '/courses/erp-crm-enterprise-tools/sap-fico-training-in-hyderabad', destination: '/courses/erp-crm-enterprise-tools/sap-fico-training-institute-in-hyderabad', permanent: true },
      { source: '/courses/erp-crm-enterprise-tools/sap-mm-sd-training-institute-in-hyderabad', destination: '/courses/erp-crm-enterprise-tools/sap-mm-sd-training-in-hyderabad', permanent: true },
      { source: '/courses/software-testing-os/selenium-automation-testing-training-hyderabad', destination: '/courses/software-testing-os/selenium-automation-testing-training-in-hyderabad', permanent: true },
      { source: '/courses/selenium-testing-training-in-hyderabad', destination: '/courses/software-testing-os/selenium-automation-testing-training-in-hyderabad', permanent: true },
      { source: '/courses/snowflake-training-in-hyderabad', destination: '/courses/data-engineering/snowflake-data-warehousing-training-in-hyderabad', permanent: true },
      { source: '/courses/digital-design/ui-ux-design-training-in-hyderabad', destination: '/courses/digital-design/ui-ux-design-training-institute-in-hyderabad', permanent: true },
      // infrastructure redirects — wildcard (must stay after exact-match rules above),
      { source: '/category/:path*', destination: '/courses', permanent: true },
      { source: '/tag/:path*', destination: '/courses', permanent: true },
      { source: '/author/:path*', destination: '/', permanent: true },
      { source: '/training-institutes-in-hyderabad/:path*', destination: '/courses', permanent: true },
      { source: '/coaching-centres-in-hyderabad/:path*', destination: '/courses', permanent: true },
      { source: '/branches/:path*', destination: '/contact-us', permanent: true },
      { source: '/sql/mysql/:path*', destination: '/sql-training-institute-in-hyderabad', permanent: true },
    ];
  },
};

const withMDX = createMDX({
  options: {
    remarkPlugins: [],
    rehypePlugins: [],
  },
});

export default withMDX(nextConfig);
