-- 2026-10-03 Banned claims in page metadata and course copy (fix/meta-claims).
-- Run in the Supabase SQL Editor, in order, AFTER the fix/meta-claims deploy is live.
-- Not run by Claude. Generated by scripts/generate-meta-claims-sql.mjs from the live
-- production sweep (scripts/audit-rendered-claims.mjs); simulated before writing:
--   2072 live page texts + 75 Course/BlogPost rows checked; banned phrases left after
--   this SQL: 4, each copy from code (fixed by the deploy) or a truncated course card
--   whose Course row this SQL fixes:
--     /courses/cloud-computing body text: "0%"
--     /courses/cloud-computing body text: "top IT companies"
--     /courses/cyber-security body text: "top IT companies"
--     /corporate-training body text: "500+ COMPANIES"
-- Allowed claims only: since 2010, 5,000+ students trained, 50+ hiring partners, 1-year LMS access.
--
-- Run the steps in order: 0 → 1 → 2 → 3 → 4. Each can be run on its own (the
-- helper is a normal function, so it survives separate SQL Editor runs; step 4 drops it).
-- The SQL Editor shows only the last result: run each SELECT on its own to see it.

-- ── STEP 0: helper function (dropped in step 4) ────────────────────────────
CREATE OR REPLACE FUNCTION public.coss_claims_fix_20261003(t text) RETURNS text LANGUAGE plpgsql IMMUTABLE AS $fn$
DECLARE
  s text := t;
BEGIN
  IF s IS NULL THEN RETURN NULL; END IF;
  -- 1. Seeded blog suffix (also when cut short with "…").
  IF s ~* '\s*—\s*Expert IT training insights from Coss Cloud Solutions, Hyderabad''s leading IT.*$' THEN
    s := regexp_replace(s, '\s*—\s*Expert IT training insights from Coss Cloud Solutions, Hyderabad''s leading IT.*$', '', 'i');
    IF length(s) + 43 <= 158 THEN s := s || ' — Expert IT training insights, since 2010.'; END IF;
  END IF;
  -- 2. Literal phrase pairs, longest first.
  s := replace(s, 'With our 15+ years of experience, we prepare you for the exam and the real-world demands of companies in HITEC City and Gachibowli, ensuring you''re ready for placements.', 'Training IT professionals since 2010, we prepare you for the exam and the real-world demands of companies in HITEC City and Gachibowli.');
  s := replace(s, 'Get job-ready skills for the vibrant IT market in Hyderabad, including companies in HITEC City, Gachibowli, and Madhapur, just like our 5000+ placed students.', 'Get job-ready skills for the IT market in Hyderabad, including companies in HITEC City, Gachibowli, and Madhapur.');
  s := replace(s, 'Get top Cyber Security Training in Hyderabad. Land high-paying jobs as Security Analyst or Ethical Hacker with Coss Cloud Solutions'' placement support.', 'Cyber Security Training in Hyderabad since 2010. Prepare for Security Analyst and Ethical Hacker roles with Coss Cloud Solutions'' placement support.');
  s := replace(s, 'With 15+ years of training experience, Coss Cloud Solutions helps you tap into the thriving IT job market in Hyderabad''s HITEC City and Gachibowli.', 'Training IT professionals since 2010, Coss Cloud Solutions helps you prepare for the IT job market in Hyderabad''s HITEC City and Gachibowli.');
  s := replace(s, 'Our 15+ years of experience and placement support through 50+ hiring partners mean you get quality training and support to land a great job.', 'Training since 2010 and placement support through 50+ hiring partners mean you get quality training and support.');
  s := replace(s, 'Gain practical skills demanded by top companies in Hyderabad, including those in HITEC City, Gachibowli, and Madhapur.', 'Gain practical skills for cloud roles in Hyderabad, including HITEC City, Gachibowli, and Madhapur.');
  s := replace(s, 'Our training focuses on practical projects, helping you secure great job opportunities with top companies.', 'Our training focuses on practical projects that prepare you for data engineering roles.');
  s := replace(s, 'This guide cuts through the noise, showing you how to build a high-paying career right here in Telangana.', 'This guide shows you how to build a cloud career in Telangana.');
  s := replace(s, 'Coss Cloud Solutions has helped thousands of students get placed at leading IT firms for over 15 years.', 'Coss Cloud Solutions has trained 5,000+ students since 2010.');
  s := replace(s, 'Craft ATS-friendly resumes, ace 3+ mock interviews, and land your dream job in Hyderabad.', 'Craft ATS-friendly resumes and ace 3+ mock interviews in Hyderabad.');
  s := replace(s, 'Coss Cloud Solutions has 15+ years of experience placing students in top IT companies.', 'Coss Cloud Solutions has trained IT professionals since 2010, with placement support through 50+ hiring partners.');
  s := replace(s, 'Get placed in top IT companies after completing our practical, job-focused training.', 'Build job-ready skills with our practical, job-focused training.');
  s := replace(s, 'Prepare for Architect roles at Hyderabad''s top IT companies, with placement support.', 'Prepare for Solutions Architect roles, with placement support from 50+ hiring partners.');
  s := replace(s, 'We focus on practical skills you can use from day one, helping you land a good job.', 'We focus on practical skills you can use from day one.');
  s := replace(s, 'Get certified, analyze data, and prepare for data roles at Hyderabad''s top firms.', 'Get certified, analyze data, and prepare for data roles in Hyderabad.');
  s := replace(s, 'Prepare for Security Analyst roles in Hyderabad''s top IT companies and startups.', 'Prepare for Security Analyst roles in Hyderabad''s IT companies and startups.');
  s := replace(s, 'Build ETL/ELT pipelines for top firms and boost your data engineering career.', 'Build ETL/ELT pipelines and boost your data engineering career.');
  s := replace(s, 'Get expert training and strong placement assistance for top tech companies.', 'Get expert training and placement assistance with 50+ hiring partners.');
  s := replace(s, 'Get placed as an SEO Analyst or Digital Marketer with Coss Cloud Solutions.', 'Prepare for SEO Analyst or Digital Marketer roles with Coss Cloud Solutions.');
  s := replace(s, 'Placement support for Data Scientist, ML Engineer roles in top companies.', 'Placement support for Data Scientist and ML Engineer roles.');
  s := replace(s, 'you''ll have a solid strategy to land that job and nail the negotiation.', 'you''ll have a solid strategy for interviews and salary negotiation.');
  s := replace(s, 'Best Artificial Intelligence Course in Hyderabad: Complete Career Guide', 'Artificial Intelligence Course in Hyderabad: Complete Career Guide');
  s := replace(s, 'Ready to build something incredible from scratch and land a great job?', 'Ready to build something incredible from scratch?');
  s := replace(s, 'Workforce planning frameworks used by HRBPs at top Hyderabad IT firms', 'Workforce planning frameworks used by HRBPs at Hyderabad IT firms');
  s := replace(s, 'Get certified, analyze data, and land jobs in Hyderabad''s top firms.', 'Get certified and analyze real business data.');
  s := replace(s, 'build a strong portfolio to land your first design job in Hyderabad.', 'build a strong design portfolio in Hyderabad.');
  s := replace(s, 'Confused about choosing the best Data Science course in Hyderabad?', 'Confused about choosing a Data Science course in Hyderabad?');
  s := replace(s, 'Get full stack skills and placement support for top IT companies.', 'Get full stack skills and placement support with 50+ hiring partners.');
  s := replace(s, 'for hands-on Azure training in Hyderabad and land top cloud jobs.', 'for hands-on Azure training in Hyderabad.');
  s := replace(s, 'Get placed in top companies in HITEC City, Gachibowli, Madhapur.', 'Prepare for HITEC City & Gachibowli roles.');
  s := replace(s, 'Get job-ready for finance roles in Hyderabad''s top companies.', 'Get job-ready for SAP finance roles in Hyderabad.');
  s := replace(s, 'Explore the best Artificial Intelligence course in Hyderabad.', 'Explore our Artificial Intelligence course in Hyderabad.');
  s := replace(s, 'with the exact tools you need to land your first DevOps job.', 'with the exact tools used in DevOps roles.');
  s := replace(s, 'Get placed in top IT companies in HITEC City & Gachibowli.', 'Prepare for cloud roles in HITEC City & Gachibowli.');
  s := replace(s, 'Discover why 5,000+ students chose Coss Cloud Solutions — ', '5,000+ students trained since 2010 — ');
  s := replace(s, 'Our training prepares you for interviews at top companies.', 'Our training prepares you for technical and HR interviews.');
  s := replace(s, 'Discover why 5,000+ students chose Coss Cloud Solutions.', '5,000+ students trained since 2010.');
  s := replace(s, 'a leading IT training institute in Hyderabad since 2010', 'an IT training institute in Hyderabad since 2010');
  s := replace(s, 'Get placed at top companies with Coss Cloud Solutions.', 'Train with Coss Cloud Solutions, since 2010.');
  s := replace(s, 'Our training helps secure placements in top companies.', 'Our training prepares you for technical and HR interviews.');
  s := replace(s, 'Get ready for a high-paying career in cloud computing.', 'Get ready for a career in cloud computing.');
  s := replace(s, 'Leading IT training institute in Hyderabad since 2010', 'IT training institute in Hyderabad since 2010');
  s := replace(s, 'Get certified for jobs in Hyderabad''s top tech firms.', 'Get certified with hands-on Power BI projects.');
  s := replace(s, 'Best Data Science Course in Hyderabad: How to Choose', 'Data Science Course in Hyderabad: How to Choose');
  s := replace(s, 'High salaries, global demand, and CEH certification', 'Global demand and CEH certification');
  s := replace(s, 'This course is built for you to land a job quickly.', 'This course is built to make you job-ready.');
  s := replace(s, 'and deploy solutions for Hyderabad''s top IT firms.', 'and deploy real data solutions.');
  s := replace(s, 'Placement assistance for Hyderabad''s top companies', 'Placement assistance with 50+ hiring partners');
  s := replace(s, 'Best ethical hacking course in Hyderabad at COSS.', 'Ethical hacking course in Hyderabad at COSS.');
  s := replace(s, 'Get top Cyber Security Training in Hyderabad.', 'Cyber Security Training in Hyderabad since 2010.');
  s := replace(s, 'Get certified & land top jobs in Hyderabad.', 'Get certified in Hyderabad.');
  s := replace(s, 'Get certified & land jobs with top firms.', 'Get certified.');
  s := replace(s, 'Best Microsoft Office Training Institute', 'Microsoft Office Training');
  s := replace(s, 'Best IT Training Institute in Hyderabad', 'IT Training Institute in Hyderabad Since 2010');
  s := replace(s, 'Best Full Stack Java Training Institute', 'Full Stack Java Training');
  s := replace(s, 'Start your dev career and get placed!', 'Start your dev career with real projects!');
  s := replace(s, 'Top-Rated Digital Marketing Institute', 'Digital Marketing Training');
  s := replace(s, 'Best Artificial Intelligence Training', 'Artificial Intelligence Training');
  s := replace(s, 'Placement support for top companies.', 'Placement support with 50+ hiring partners.');
  s := replace(s, 'TopRated Digital Marketing Institute', 'Digital Marketing Training');
  s := replace(s, 'Industry Leading AWS Cloud Institute', 'AWS Cloud Training');
  s := replace(s, 'Best Communication Skills Institute', 'Communication Skills Training');
  s := replace(s, 'Best SQL/MySQL/PostgreSQL Training', 'SQL/MySQL/PostgreSQL Training');
  s := replace(s, 'Best Full Stack Power BI Training', 'Full Stack Power BI Training');
  s := replace(s, 'Best Azure Data Engineer Training', 'Azure Data Engineer Training');
  s := replace(s, 'Best Digital Marketing Institute', 'Digital Marketing Training');
  s := replace(s, 'Best Digital Marketing Training', 'Digital Marketing Training');
  s := replace(s, 'Best Machine Learning Training', 'Machine Learning Training');
  s := replace(s, 'Best Ethical Hacking Institute', 'Ethical Hacking Training');
  s := replace(s, 'Top IT training in Hyderabad.', 'IT training in Hyderabad since 2010.');
  s := replace(s, 'Best Spoken English Institute', 'Spoken English Training');
  s := replace(s, 'Best Linux Training Institute', 'Linux Training');
  s := replace(s, 'Best Digital Marketing Course', 'Digital Marketing Course');
  s := replace(s, 'Best Cyber Security Institute', 'Cyber Security Training');
  s := replace(s, 'Best Data Analytics Training', 'Data Analytics Training');
  s := replace(s, 'Best Google Cloud Institute', 'Google Cloud Training');
  s := replace(s, 'Best Azure Devops Institute', 'Azure Devops Training');
  s := replace(s, 'Best IT Training Institute', 'IT Training');
  s := replace(s, 'Best Data Science Training', 'Data Science Training');
  s := replace(s, 'Best Azure Cloud Institute', 'Azure Cloud Training');
  s := replace(s, 'Best Salesforce Institute', 'Salesforce Training');
  s := replace(s, 'Best Institute for DevOps', 'DevOps Training');
  s := replace(s, 'Best Certification Course', 'Certification Course');
  s := replace(s, 'Best MS Office Institute', 'MS Office Training');
  s := replace(s, 'Best Data Science Course', 'Data Science Course');
  s := replace(s, 'Best SAP Fico Training', 'SAP Fico Training');
  s := replace(s, 'Best SAP FICO Training', 'SAP FICO Training');
  s := replace(s, 'Best SAP Fico Training', 'SAP Fico Training');
  s := replace(s, 'Best Python Institute', 'Python Training');
  s := replace(s, 'Best Tally Institute', 'Tally Training');
  s := replace(s, 'Best Linux Institute', 'Linux Training');
  s := replace(s, 'Top DevOps Institute', 'DevOps Training');
  s := replace(s, 'Top DevOps Training', 'DevOps Training');
  s := replace(s, 'Best Java Institute', 'Java Training');
  s := replace(s, 'Best AWS Institutes', 'AWS Training');
  s := replace(s, 'Best AWS Course', 'AWS Course');
  s := replace(s, 'Best AI Course', 'AI Course');
  RETURN s;
END
$fn$;

-- ── STEP 1: PREVIEW (read-only) — old and new text side by side ────────────
-- Expected: PageSeo rows for blog posts (seeded suffix, "Best … Institute" titles),
-- course pages (job-outcome sentences) and home/about/why-us (up to ~100 pages);
-- Course: 23 rows (cmq587yfc0002uhify94y0moo, cmq588dkz0003uhif3doslfiq, cmq59akvb000452fmxxk7gzuy, cmq5jnctt00023hrq18225pvx, cmq59g60f000g52fmmshel3in, cmq247cm0000xnmi59qz1w2ye, cmq2fluew001hxd37ive4oubj, cmq5jr6810000h4xj8jde9ytt, cmpieh0ag0002552d70bd1454, cmpkvqetn0007x26h0i2jczpu, cmq2fapry0001xd37y78galtj, cmq59gyrp000i52fmexblzbui, cmq5jssqb0000uaorxf4qf2gi, cmq599j6d000152fm3ky0nabx, cmq2455fc000nnmi5wefkjabm, cmq59hqvw000k52fmjio8kbko, cmq2fe1x7000hxd377uxnu99r, cmq246ziy000vnmi5pya46pzb, cmq2p0lds000327uftxhsvk8y, cmq59ctzw000952fmk18xvxgy, cmq2fjefp0015xd370xcdo9fd, cmq5997qn000052fm5v790tat, cmq241wdf0009nmi52tt7l2uh);
-- BlogPost: 4 rows (cmr8du7wr00025xxkiiw2wks4, cmpieh1qz0004552dfsgmaf0v, cmr8ecpcd0000hdk9a1isiag7, cmr8e725r00035xxkaqoq6ylg).
SELECT 'PageSeo' AS tbl, "pageSlug" AS key, col, old, public.coss_claims_fix_20261003(old) AS new
FROM "PageSeo", LATERAL (VALUES ('metaTitle', "metaTitle"), ('metaDescription', "metaDescription"), ('ogTitle', "ogTitle"), ('ogDescription', "ogDescription")) v(col, old)
WHERE old IS DISTINCT FROM public.coss_claims_fix_20261003(old)
UNION ALL
SELECT 'Course', id || ' ' || slug, col, old, public.coss_claims_fix_20261003(old)
FROM "Course", LATERAL (VALUES ('title', title), ('excerpt', excerpt), ('description', description), ('seoTitle', "seoTitle"), ('seoDesc', "seoDesc")) v(col, old)
WHERE old IS DISTINCT FROM public.coss_claims_fix_20261003(old)
UNION ALL
SELECT 'Course', id || ' ' || slug, 'highlights[' || i || ']', x, public.coss_claims_fix_20261003(x)
FROM "Course", unnest(highlights) WITH ORDINALITY AS u(x, i)
WHERE x IS DISTINCT FROM public.coss_claims_fix_20261003(x)
UNION ALL
SELECT 'BlogPost', id || ' ' || slug, col, old, public.coss_claims_fix_20261003(old)
FROM "BlogPost", LATERAL (VALUES ('title', title), ('excerpt', excerpt), ('seoTitle', "seoTitle"), ('seoDesc', "seoDesc")) v(col, old)
WHERE old IS DISTINCT FROM public.coss_claims_fix_20261003(old)
ORDER BY 1, 2, 3;

-- ── STEP 2: UPDATE … RETURNING (one transaction) ───────────────────────────
BEGIN;

UPDATE "PageSeo" SET
  "metaTitle" = public.coss_claims_fix_20261003("metaTitle"),
  "metaDescription" = public.coss_claims_fix_20261003("metaDescription"),
  "ogTitle" = public.coss_claims_fix_20261003("ogTitle"),
  "ogDescription" = public.coss_claims_fix_20261003("ogDescription"),
  "updatedAt" = now()
WHERE "metaTitle" IS DISTINCT FROM public.coss_claims_fix_20261003("metaTitle")
   OR "metaDescription" IS DISTINCT FROM public.coss_claims_fix_20261003("metaDescription")
   OR "ogTitle" IS DISTINCT FROM public.coss_claims_fix_20261003("ogTitle")
   OR "ogDescription" IS DISTINCT FROM public.coss_claims_fix_20261003("ogDescription")
RETURNING 'PageSeo' AS tbl, "pageSlug", "metaTitle", "metaDescription", "ogTitle", "ogDescription";

UPDATE "Course" SET
  title = public.coss_claims_fix_20261003(title),
  excerpt = public.coss_claims_fix_20261003(excerpt),
  description = public.coss_claims_fix_20261003(description),
  "seoTitle" = public.coss_claims_fix_20261003("seoTitle"),
  "seoDesc" = public.coss_claims_fix_20261003("seoDesc"),
  highlights = ARRAY(SELECT public.coss_claims_fix_20261003(x) FROM unnest(highlights) WITH ORDINALITY AS u(x, i) ORDER BY i),
  "updatedAt" = now()
WHERE "title" IS DISTINCT FROM public.coss_claims_fix_20261003("title")
   OR "excerpt" IS DISTINCT FROM public.coss_claims_fix_20261003("excerpt")
   OR "description" IS DISTINCT FROM public.coss_claims_fix_20261003("description")
   OR "seoTitle" IS DISTINCT FROM public.coss_claims_fix_20261003("seoTitle")
   OR "seoDesc" IS DISTINCT FROM public.coss_claims_fix_20261003("seoDesc")
   OR "highlights" IS DISTINCT FROM ARRAY(SELECT public.coss_claims_fix_20261003(x) FROM unnest("highlights") WITH ORDINALITY AS u(x, i) ORDER BY i)
RETURNING 'Course' AS tbl, id, slug, "seoDesc", excerpt;

UPDATE "BlogPost" SET
  title = public.coss_claims_fix_20261003(title),
  excerpt = public.coss_claims_fix_20261003(excerpt),
  "seoTitle" = public.coss_claims_fix_20261003("seoTitle"),
  "seoDesc" = public.coss_claims_fix_20261003("seoDesc"),
  "updatedAt" = now()
WHERE "title" IS DISTINCT FROM public.coss_claims_fix_20261003("title")
   OR "excerpt" IS DISTINCT FROM public.coss_claims_fix_20261003("excerpt")
   OR "seoTitle" IS DISTINCT FROM public.coss_claims_fix_20261003("seoTitle")
   OR "seoDesc" IS DISTINCT FROM public.coss_claims_fix_20261003("seoDesc")
RETURNING 'BlogPost' AS tbl, id, slug, "seoDesc", excerpt;

COMMIT;

-- ── STEP 3: VERIFY (read-only) ──────────────────────────────────────────────
-- Expected: 0 rows (nothing left that the fix would still change).
SELECT 'PageSeo' AS tbl, count(*) FROM "PageSeo" WHERE "metaTitle" IS DISTINCT FROM public.coss_claims_fix_20261003("metaTitle")
   OR "metaDescription" IS DISTINCT FROM public.coss_claims_fix_20261003("metaDescription")
   OR "ogTitle" IS DISTINCT FROM public.coss_claims_fix_20261003("ogTitle")
   OR "ogDescription" IS DISTINCT FROM public.coss_claims_fix_20261003("ogDescription")
UNION ALL
SELECT 'Course', count(*) FROM "Course" WHERE "title" IS DISTINCT FROM public.coss_claims_fix_20261003("title")
   OR "excerpt" IS DISTINCT FROM public.coss_claims_fix_20261003("excerpt")
   OR "description" IS DISTINCT FROM public.coss_claims_fix_20261003("description")
   OR "seoTitle" IS DISTINCT FROM public.coss_claims_fix_20261003("seoTitle")
   OR "seoDesc" IS DISTINCT FROM public.coss_claims_fix_20261003("seoDesc")
   OR "highlights" IS DISTINCT FROM ARRAY(SELECT public.coss_claims_fix_20261003(x) FROM unnest("highlights") WITH ORDINALITY AS u(x, i) ORDER BY i)
UNION ALL
SELECT 'BlogPost', count(*) FROM "BlogPost" WHERE "title" IS DISTINCT FROM public.coss_claims_fix_20261003("title")
   OR "excerpt" IS DISTINCT FROM public.coss_claims_fix_20261003("excerpt")
   OR "seoTitle" IS DISTINCT FROM public.coss_claims_fix_20261003("seoTitle")
   OR "seoDesc" IS DISTINCT FROM public.coss_claims_fix_20261003("seoDesc");
-- Expected: tbl/count = PageSeo 0, Course 0, BlogPost 0.

-- Expected: 0 rows — no meta description over 160 characters among the rows touched.
SELECT "pageSlug", length("metaDescription") FROM "PageSeo"
WHERE length("metaDescription") > 160 AND "updatedAt" > now() - interval '1 hour';

-- ── STEP 4: drop the helper ─────────────────────────────────────────────────
DROP FUNCTION IF EXISTS public.coss_claims_fix_20261003(text);

-- Then tell Claude "SQL done": the full production sweep is re-run
-- (node scripts/audit-rendered-claims.mjs) and before/after counts reported.
