-- 2026-10-03 Banned claims in page metadata and course/blog copy (v2, after fix/meta-claims-2).
-- Run in the Supabase SQL Editor AFTER the fix/meta-claims-2 deploy is live. Not run by Claude.
--
-- APPLIED 2026-10-04 by Subodh in the Supabase SQL Editor. Do not run again. This file is the
-- record of the main pass; passes 2 and 3 were written and applied by review, not by the
-- generator.
--   Main pass (this file, coss_claims_fix_20261003): PageSeo 145, Course 33, BlogPost 4 rows.
--     The simulation below expected 101 / 28 / 4. It only covered rows reachable from the
--     live site (sitemap + /courses links + their public API rows). The extra rows were
--     orphaned PageSeo keys and draft courses.
--   Pass 2 (coss_claims_fix2_20261003): "Get placed…" in 3 PageSeo rows and the Selenium
--     Course seoDesc; "Get Hired" in blog/digital-marketing-course-dilsukhnagar; a doubled
--     "since 2010" in the home metaDescription.
--   Pass 3 (coss_claims_fix3_20261004): a DB-wide scan, drafts and Course.description
--     included, found 61 more. These were "get placed", "land (top) jobs", "15+ years (of
--     placement success)", "thousands of students", "400/180+ students trained", the
--     TCS/Infosys/Wipro mention, "top/leading companies", and 12 orphaned PageSeo
--     descriptions starting "Best…". All fixed.
--   Kept on purpose (9): career-advice "best career" phrasing in 2 blog metas, "hiring
--     strategies used by top companies" (HR course curriculum), the "Find best career path"
--     highlight, and the React/Node "trainers with 15+ years in the industry" (waits on the
--     client, like "7 to 20+ years").
--   Backups: coss_backup."PageSeo_20261003", "Course_20261003", "BlogPost_20261003",
--     "PageSeo_20261004_p3", "Course_20261004_p3". Helper functions dropped.
--   Made live by redeploying production from 806d409. Full production sweep after that, 2026-10-04:
--     237 URLs, 237 HTTP 200, 0 hits (before: 451 hits on 141 URLs).
--   Next time, generate a new file. Its STEP S scans the whole DB first; pass --db-scan
--     with that export, so drafts and orphaned rows are covered and the counts are exact.
-- Generated by scripts/generate-meta-claims-sql.mjs from the production sweep
-- (scripts/audit-rendered-claims.mjs, every match): 237 URLs fetched, 237 returned 200.
-- Simulated before writing on 1153 live page texts + 75 live Course/BlogPost rows:
-- banned matches left after this SQL: 0.
-- Allowed claims only: since 2010, 5,000+ students trained, 50+ hiring partners, 1-year LMS access.
--
-- Expected rows changed (from the simulation; STEP 1 shows the exact list):
--   PageSeo:  101 pages (pageSlug: big-data-training-institute-in-hyderabad, machine-learning-training-institute-in-hyderabad, artificial-intelligence-training-institute-in-hyderabad, power-bi-training-institute-in-hyderabad, sql-training-institute-in-hyderabad, azure-training-institute-in-hyderabad, google-cloud-training-institute-in-hyderabad, devops-training-institute-in-hyderabad, aws-devops-training-institute-in-hyderabad, azure-devops-training-institute-in-hyderabad, python-training-institute-in-hyderabad, java-training-institute-in-hyderabad, data-engineering-training-institute-in-hyderabad, cyber-security-training-institute-in-hyderabad, tally-erp-training-institute-in-hyderabad, software-testing-training-institute-in-hyderabad, digital-marketing-training-institute-in-hyderabad, ui-ux-design-training-institute-in-hyderabad, spoken-english-training-institute-in-hyderabad, ms-office-training-institute-in-hyderabad, aws-training-institute-in-hyderabad, communication-skills-training-in-hyderabad, home, about-us, why-us, blog/top-rated-digital-marketing-institute-in-dilsukhnagar-hyderabad, blog/sql-mysql-postgresql-training-in-dilsukhnagar-hyderabad, blog/spoken-english-institute-in-hyderabad, blog/sap-fico-training-in-hyderabad, blog/machine-learning-training-in-dilsukhnagar-hyderabad, blog/learning-tally-with-coss-cloud-solutions-in-dilsukhnagar-hyderabad, blog/learn-tally-in-dilsukhnagar-hyderabad-by-coss-cloud-solutions, blog/learn-ms-office-in-dilsukhnagar-hyderabad-by-coss-cloud-solutions, blog/learn-linux-with-coss-cloud-solutions-in-dilsukhnagar-hyderabad, blog/learn-ethical-hacking-in-hyderabad-with-coss-cloud-solutions, blog/learn-azure-cloud-with-coss-cloud-solutions-in-hyderabad, blog/learn-aws-devops-in-hyderabad-with-coss-cloud-solutions, blog/join-our-industry-leading-aws-cloud-institute-in-dilsukhnagar-hyderabad, blog/job-opportunities-for-devops-professionals-in-hyderabad, blog/how-to-learn-aws-cloud-for-beginners, blog/get-placed-with-coss-cloud-solutions-corporate-training-in-hyderabad, blog/digital-marketing-classes-in-hyderabad, blog/devops-institute-in-dilsukhnagar-hyderabad, blog/data-science-training-dilsukhnagar-hyderabad, blog/data-engineer-course-training-hyderabad, blog/data-analytics-institute-in-dilsukhnagar-hyderabad, blog/cyber-security-training-dilsukhnagar-hyderabad, blog/coss-cloud-solutions-best-linux-training-institute-in-dilsukhnagar-hyderabad, blog/cloud-computing-training-institute-in-dilsukhnagar-hyderabad, blog/cloud-computing-training-in-hyderabad-the-best-career-move-in-2025, blog/cloud-computing-future-in-hyderabad-with-coss-cloud-solutions, blog/cloud-computing-classes-with-coss-cloud-solutions-in-hyderabad, blog/best-tally-institute-in-hyderabad-coss-cloud-solutions, blog/best-tally-institute-in-dilsukhnagar-hyderabad-coss-cloud-solutions, blog/best-spoken-english-institute-in-dilsukhnagar-hyderabad-coss-cloud-solutions, blog/best-salesforce-institute-dilsukhnagar-hyderabad-coss-cloud-solutions, blog/best-python-institute-in-hyderabad-coss-cloud-solutions, blog/best-python-institute-in-dilsukhnagar-hyderabad-coss-cloud-solutions, blog/best-ms-office-institute-in-hyderabad-coss-cloud-solutions, blog/best-ms-office-institute-in-dilsukhnagar-hyderabad-coss-cloud-solutions, blog/best-microsoft-office-training-institute-in-dilsukhnagar-hyderabad-coss-cloud-solutions, blog/best-linux-training-institute-in-dilsukhnagarhyderabad, blog/best-linux-institute-in-dilsukhnagar-hyderabad-coss-cloud-solution, blog/best-java-institute-in-dilsukhnagar-hyderabad-coss-cloud-solution, blog/best-institute-for-devops-in-hyderabad-coss-cloud-solutions, blog/best-google-cloud-institute-in-dilsukhnagar-hyderabad-coss-cloud-solution, blog/best-ethical-hacking-institute-in-hyderabad-coss-cloud-solutions, blog/best-ethical-hacking-institute-in-dilsukhnagar-hyderabad-coss-cloud-solutions, blog/best-digital-marketing-institute-in-hyderabad-coss-cloud-solutions-2, blog/best-digital-marketing-institute-in-hyderabad-coss-cloud-solutions, blog/best-digital-marketing-institute-in-dilsukhnagar-hyderabad-coss-cloud-solutions, blog/best-digital-marketing-institute-in-ameerpet-hyderabad-coss-cloud-solutions, blog/best-digital-marketing-course-in-dilsukhnagar-coss-cloud-solutions, blog/best-cyber-security-institute-in-hyderabad-coss-cloud-solutions, blog/best-cyber-security-institute-in-dilsukhnagar-hyderabad-coss-cloud-solutions, blog/best-communication-skills-institute-in-hyderabad-coss-cloud-solutions, blog/best-communication-skills-institute-in-dilsukhnagar-hyderabad-coss-cloud-solutions, blog/best-certification-course-institute-in-hyderabad-coss-cloud-solutions, blog/best-certification-course-institute-in-dilsukhnagar-hyderabad-coss-cloud-solutions, blog/best-certification-course-institute-in-ameerpet-hyderabad-coss-cloud-solutions, blog/best-azure-devops-institute-in-dilsukhnagar-hyderabad-coss-cloud-solution, blog/best-azure-cloud-institute-in-dilsukhnagar-hyderabad-coss-cloud-solution, blog/best-aws-institutes-in-hyderabad-coss-cloud-solutions, blog/best-aws-course-provider-in-hyderabad-coss-cloud-solutions, blog/azure-data-engineer-training-in-hyderabad, blog/aws-cloud-course-training-in-hyderabad-with-coss-cloud-solutions, blog/artificial-intelligence-training-in-hyderabad, blog/advance-your-career-at-the-top-devops-institute-in-dilsukhnagar-coss-cloud-solutions, blog/77674-2, data-analytics-training-institute-in-hyderabad, courses/data-analytics-bi/power-bi-training-in-hyderabad, courses/full-stack-python-training-in-hyderabad, courses/python-programming-training-in-hyderabad, courses/erp-crm-enterprise-tools/salesforce-admin-developer-training-in-hyderabad, courses/interview-preparation-training-in-hyderabad, courses/digital-design/digital-marketing-training-in-hyderabad, courses/programming-full-stack/mern-stack-training-in-hyderabad, courses/aws-solutions-architect-training-in-hyderabad, courses/multi-cloud-architecture-training-in-hyderabad, blog/top-10-reasons-cyber-security-career-hyderabad, courses/seo-training-institute-in-hyderabad)
--   Course:   28 rows (cmq587yfc0002uhify94y0moo, cmq588dkz0003uhif3doslfiq, cmq59akvb000452fmxxk7gzuy, cmq5jnctt00023hrq18225pvx, cmq59g60f000g52fmmshel3in, cmq247cm0000xnmi59qz1w2ye, cmq5877qs0000uhif3hrxzyay, cmq587jqp0001uhifgxgjz7q7, cmq2fluew001hxd37ive4oubj, cmq5jr6810000h4xj8jde9ytt, cmpieh0ag0002552d70bd1454, cmpkvqetn0007x26h0i2jczpu, cmq59b130000552fmsohamnvc, cmq2fapry0001xd37y78galtj, cmq59gyrp000i52fmexblzbui, cmq5jssqb0000uaorxf4qf2gi, cmq59ipk9000n52fm5ehgwgm0, cmq599j6d000152fm3ky0nabx, cmq2455fc000nnmi5wefkjabm, cmq59hqvw000k52fmjio8kbko, cmq2fe1x7000hxd377uxnu99r, cmq246ziy000vnmi5pya46pzb, cmq2p0lds000327uftxhsvk8y, cmq59ctzw000952fmk18xvxgy, cmq2fjefp0015xd370xcdo9fd, cmq5997qn000052fm5v790tat, cmq241wdf0009nmi52tt7l2uh, cmq59a7co000352fmh50ttd5v)
--   BlogPost: 4 rows (cmr8du7wr00025xxkiiw2wks4, cmpieh1qz0004552dfsgmaf0v, cmr8e725r00035xxkaqoq6ylg, cmr8ecpcd0000hdk9a1isiag7)
-- PageSeo can be higher if rows not reachable from the sitemap/course links carry the same phrases.
--
-- The fix makes no description longer than 160 characters (STEP 1 checks this). Already
-- over 160 before it, and only shortened by it (9):
--   /machine-learning-training-institute-in-hyderabad meta description: 168 → 163
--   /machine-learning-training-institute-in-hyderabad og:description: 168 → 163
--   /machine-learning-training-institute-in-hyderabad twitter:description: 168 → 163
--   /cyber-security-training-institute-in-hyderabad meta description: 167 → 162
--   /cyber-security-training-institute-in-hyderabad og:description: 167 → 162
--   /cyber-security-training-institute-in-hyderabad twitter:description: 167 → 162
--   /digital-marketing-training-institute-in-hyderabad meta description: 168 → 163
--   /digital-marketing-training-institute-in-hyderabad og:description: 168 → 163
--   /digital-marketing-training-institute-in-hyderabad twitter:description: 168 → 163
--
-- Run the steps in order: 0 → 1 → 2 → 3 → 4. Each can be run on its own (the
-- helper is a normal function, so it survives separate SQL Editor runs; step 4 drops it).
-- The SQL Editor shows only the last result: run each SELECT on its own to see it.

-- ── STEP 0: helper function (dropped in step 4) ────────────────────────────
CREATE OR REPLACE FUNCTION public.coss_claims_fix_20261003(t text) RETURNS text LANGUAGE plpgsql IMMUTABLE AS $fn$
DECLARE
  s text := t;
BEGIN
  IF s IS NULL THEN RETURN NULL; END IF;
  -- 1. Seeded blog suffix (also when cut short with "…").
  IF s ~* '\s*—\s*Expert IT training insights from Coss Cloud Solutions, Hyderabad''s.*$' THEN
    s := regexp_replace(s, '\s*—\s*Expert IT training insights from Coss Cloud Solutions, Hyderabad''s.*$', '', 'i');
    IF length(s) + 43 <= 158 THEN s := s || ' — Expert IT training insights, since 2010.'; END IF;
  END IF;
  -- 2. Literal phrase pairs, longest first.
  s := replace(s, 'With our 15+ years of experience, we prepare you for the exam and the real-world demands of companies in HITEC City and Gachibowli, ensuring you''re ready for placements.', 'Training IT professionals since 2010, we prepare you for the exam and the real-world demands of companies in HITEC City and Gachibowli.');
  s := replace(s, 'Get job-ready skills for the vibrant IT market in Hyderabad, including companies in HITEC City, Gachibowli, and Madhapur, just like our 5000+ placed students.', 'Get job-ready skills for the IT market in Hyderabad, including companies in HITEC City, Gachibowli, and Madhapur.');
  s := replace(s, 'This course helps you join leading companies such as TCS, Wipro, Infosys, and local startups, giving you the skills needed to start a fulfilling career in AI.', 'This course gives you the skills needed to start a fulfilling career in AI.');
  s := replace(s, 'Get top Cyber Security Training in Hyderabad. Land high-paying jobs as Security Analyst or Ethical Hacker with Coss Cloud Solutions'' placement support.', 'Cyber Security Training in Hyderabad since 2010. Prepare for Security Analyst and Ethical Hacker roles with Coss Cloud Solutions'' placement support.');
  s := replace(s, 'With 15+ years of training experience, Coss Cloud Solutions helps you tap into the thriving IT job market in Hyderabad''s HITEC City and Gachibowli.', 'Training IT professionals since 2010, Coss Cloud Solutions helps you prepare for the IT job market in Hyderabad''s HITEC City and Gachibowli.');
  s := replace(s, 'Our 15+ years of experience and placement support through 50+ hiring partners mean you get quality training and support to land a great job.', 'Training since 2010 and placement support through 50+ hiring partners mean you get quality training and support.');
  s := replace(s, 'Gain practical skills demanded by top companies in Hyderabad, including those in HITEC City, Gachibowli, and Madhapur.', 'Gain practical skills for cloud roles in Hyderabad, including HITEC City, Gachibowli, and Madhapur.');
  s := replace(s, 'Get certified and secure top cybersecurity roles with practical training and placement support at leading companies.', 'Get certified and prepare for cybersecurity roles with practical training and placement support.');
  s := replace(s, 'Our training focuses on practical projects, helping you secure great job opportunities with top companies.', 'Our training focuses on practical projects that prepare you for data engineering roles.');
  s := replace(s, 'This guide cuts through the noise, showing you how to build a high-paying career right here in Telangana.', 'This guide shows you how to build a cloud career in Telangana.');
  s := replace(s, 'Coss Cloud Solutions has helped thousands of students get placed at leading IT firms for over 15 years.', 'Coss Cloud Solutions has trained 5,000+ students since 2010.');
  s := replace(s, 'Craft ATS-friendly resumes, ace 3+ mock interviews, and land your dream job in Hyderabad.', 'Craft ATS-friendly resumes and ace 3+ mock interviews in Hyderabad.');
  s := replace(s, 'Get certified and secure top placements at leading companies in HITEC City, Gachibowli.', 'Get certified and prepare for Architect roles in HITEC City & Gachibowli.');
  s := replace(s, 'Coss Cloud Solutions has 15+ years of experience placing students in top IT companies.', 'Coss Cloud Solutions has trained IT professionals since 2010, with placement support through 50+ hiring partners.');
  s := replace(s, 'Get placed in top IT companies after completing our practical, job-focused training.', 'Build job-ready skills with our practical, job-focused training.');
  s := replace(s, 'Prepare for Architect roles at Hyderabad''s top IT companies, with placement support.', 'Prepare for Solutions Architect roles, with placement support from 50+ hiring partners.');
  s := replace(s, 'We focus on practical skills you can use from day one, helping you land a good job.', 'We focus on practical skills you can use from day one.');
  s := replace(s, 'Get certified, analyze data, and prepare for data roles at Hyderabad''s top firms.', 'Get certified, analyze data, and prepare for data roles in Hyderabad.');
  s := replace(s, 'Prepare for Security Analyst roles in Hyderabad''s top IT companies and startups.', 'Prepare for Security Analyst roles in Hyderabad''s IT companies and startups.');
  s := replace(s, 'Why COSS Cloud Solutions Offers the Best Digital Marketing Course in Hyderabad', 'Digital Marketing Course in Hyderabad at COSS Cloud Solutions');
  s := replace(s, 'Build ETL/ELT pipelines for top firms and boost your data engineering career.', 'Build ETL/ELT pipelines and boost your data engineering career.');
  s := replace(s, 'Get expert training and strong placement assistance for top tech companies.', 'Get expert training and placement assistance with 50+ hiring partners.');
  s := replace(s, 'Get placed as an SEO Analyst or Digital Marketer with Coss Cloud Solutions.', 'Prepare for SEO Analyst or Digital Marketer roles with Coss Cloud Solutions.');
  s := replace(s, 'Placement support for Data Scientist, ML Engineer roles in top companies.', 'Placement support for Data Scientist and ML Engineer roles.');
  s := replace(s, 'you''ll have a solid strategy to land that job and nail the negotiation.', 'you''ll have a solid strategy for interviews and salary negotiation.');
  s := replace(s, 'Best Artificial Intelligence Course in Hyderabad: Complete Career Guide', 'Artificial Intelligence Course in Hyderabad: Complete Career Guide');
  s := replace(s, 'Get Placed with Coss Cloud Solutions "Corporate Training" in Hyderabad', 'Train with Coss Cloud Solutions "Corporate Training" in Hyderabad');
  s := replace(s, 'Ready to build something incredible from scratch and land a great job?', 'Ready to build something incredible from scratch?');
  s := replace(s, 'Workforce planning frameworks used by HRBPs at top Hyderabad IT firms', 'Workforce planning frameworks used by HRBPs at Hyderabad IT firms');
  s := replace(s, 'Get certified, analyze data, and land jobs in Hyderabad''s top firms.', 'Get certified and analyze real business data.');
  s := replace(s, 'build a strong portfolio to land your first design job in Hyderabad.', 'build a strong design portfolio in Hyderabad.');
  s := replace(s, 'Confused about choosing the best Data Science course in Hyderabad?', 'Confused about choosing a Data Science course in Hyderabad?');
  s := replace(s, 'Get personalized career guidance & placement support for top jobs.', 'Get personalized career guidance & placement support.');
  s := replace(s, 'Get full stack skills and placement support for top IT companies.', 'Get full stack skills and placement support with 50+ hiring partners.');
  s := replace(s, 'for hands-on Azure training in Hyderabad and land top cloud jobs.', 'for hands-on Azure training in Hyderabad.');
  s := replace(s, 'Get placed in top companies in HITEC City, Gachibowli, Madhapur.', 'Prepare for HITEC City & Gachibowli roles.');
  s := replace(s, 'Advance Your Career at the Top DevOps Institute in Dilsukhnagar', 'Advance Your Career at Our DevOps Institute in Dilsukhnagar');
  s := replace(s, 'Get job-ready for finance roles in Hyderabad''s top companies.', 'Get job-ready for SAP finance roles in Hyderabad.');
  s := replace(s, 'Explore the best Artificial Intelligence course in Hyderabad.', 'Explore our Artificial Intelligence course in Hyderabad.');
  s := replace(s, 'with the exact tools you need to land your first DevOps job.', 'with the exact tools used in DevOps roles.');
  s := replace(s, 'Master Multi-Cloud Architecture for top IT jobs in Hyderabad', 'Master Multi-Cloud Architecture in Hyderabad');
  s := replace(s, 'Get placed in top IT companies in HITEC City & Gachibowli.', 'Prepare for cloud roles in HITEC City & Gachibowli.');
  s := replace(s, 'Discover why 5,000+ students chose Coss Cloud Solutions — ', '5,000+ students trained since 2010 — ');
  s := replace(s, 'Our training prepares you for interviews at top companies.', 'Our training prepares you for technical and HR interviews.');
  s := replace(s, 'as a Data Scientist or Analyst in leading tech companies.', 'as a Data Scientist or Analyst.');
  s := replace(s, 'Discover why 5,000+ students chose Coss Cloud Solutions.', '5,000+ students trained since 2010.');
  s := replace(s, 'Join the Best Digital Marketing Training in Dilsukhnagar', 'Join Our Digital Marketing Training in Dilsukhnagar');
  s := replace(s, 'a leading IT training institute in Hyderabad since 2010', 'an IT training institute in Hyderabad since 2010');
  s := replace(s, 'Get placed at top companies with Coss Cloud Solutions.', 'Train with Coss Cloud Solutions, since 2010.');
  s := replace(s, 'Our training helps secure placements in top companies.', 'Our training prepares you for technical and HR interviews.');
  s := replace(s, 'Get ready for a high-paying career in cloud computing.', 'Get ready for a career in cloud computing.');
  s := replace(s, 'Get skilled in Data Science for top jobs in Hyderabad.', 'Get skilled in Data Science in Hyderabad.');
  s := replace(s, 'Leading IT training institute in Hyderabad since 2010', 'IT training institute in Hyderabad since 2010');
  s := replace(s, 'Get certified for jobs in Hyderabad''s top tech firms.', 'Get certified with hands-on Power BI projects.');
  s := replace(s, 'Best Data Science Course in Hyderabad: How to Choose', 'Data Science Course in Hyderabad: How to Choose');
  s := replace(s, 'placement assistance for top digital marketing jobs.', 'placement assistance for digital marketing roles.');
  s := replace(s, 'Placement support for Hyderabad''s leading companies.', 'Placement support with 50+ hiring partners.');
  s := replace(s, 'High salaries, global demand, and CEH certification', 'Global demand and CEH certification');
  s := replace(s, 'This course is built for you to land a job quickly.', 'This course is built to make you job-ready.');
  s := replace(s, 'and deploy solutions for Hyderabad''s top IT firms.', 'and deploy real data solutions.');
  s := replace(s, 'Placement assistance for Hyderabad''s top companies', 'Placement assistance with 50+ hiring partners');
  s := replace(s, 'Best ethical hacking course in Hyderabad at COSS.', 'Ethical hacking course in Hyderabad at COSS.');
  s := replace(s, 'Expert training, real projects, strong placement.', 'Expert training, real projects, placement support.');
  s := replace(s, 'neural networks for top tech jobs in Hyderabad.', 'neural networks in Hyderabad.');
  s := replace(s, 'Join Our Industry Leading AWS Cloud Institute', 'Join Our AWS Cloud Institute');
  s := replace(s, 'Get top Cyber Security Training in Hyderabad.', 'Cyber Security Training in Hyderabad since 2010.');
  s := replace(s, 'Best Multi Cloud & DevOps Course in Hyderabad', 'Multi Cloud & DevOps Course in Hyderabad');
  s := replace(s, 'Best soft skills and spoken English training', 'Soft skills and spoken English training');
  s := replace(s, 'Get certified & land top jobs in Hyderabad.', 'Get certified in Hyderabad.');
  s := replace(s, 'Get certified & land jobs with top firms.', 'Get certified.');
  s := replace(s, 'Best IT Training Institute in Hyderabad', 'IT Training Institute in Hyderabad Since 2010');
  s := replace(s, 'Best Institute for DevOps in Hyderabad', 'DevOps Training in Hyderabad');
  s := replace(s, 'Start your dev career and get placed!', 'Start your dev career with real projects!');
  s := replace(s, 'Get practical skills for top IT jobs.', 'Get practical, job-ready skills.');
  s := replace(s, 'Best Artificial Intelligence training', 'Artificial Intelligence training');
  s := replace(s, 'Best Artificial Intelligence Training', 'Artificial Intelligence Training');
  s := replace(s, 'TopRated Digital Marketing Institute', 'Digital Marketing Institute');
  s := replace(s, 'Placement support for top companies.', 'Placement support with 50+ hiring partners.');
  s := replace(s, 'Gain practical skills for top jobs.', 'Gain practical, job-ready skills.');
  s := replace(s, 'Best Communication Skills Institute', 'Communication Skills Training');
  s := replace(s, 'Best SQL/MySQL/PostgreSQL Training', 'SQL/MySQL/PostgreSQL Training');
  s := replace(s, 'Best Communication Skills training', 'Communication Skills training');
  s := replace(s, 'Best Full Stack Power BI Training', 'Full Stack Power BI Training');
  s := replace(s, 'Best Azure Data Engineer Training', 'Azure Data Engineer Training');
  s := replace(s, 'Best Digital Marketing Institute', 'Digital Marketing Training');
  s := replace(s, 'Best digital marketing training', 'Digital marketing training');
  s := replace(s, 'Best Machine Learning training', 'Machine Learning training');
  s := replace(s, 'Best Data Engineering training', 'Data Engineering training');
  s := replace(s, 'Best software testing training', 'Software testing training');
  s := replace(s, 'Best Machine Learning Training', 'Machine Learning Training');
  s := replace(s, 'Best Microsoft Office Training', 'Microsoft Office Training');
  s := replace(s, 'Best Ethical Hacking Institute', 'Ethical Hacking Training');
  s := replace(s, 'Top IT training in Hyderabad.', 'IT training in Hyderabad since 2010.');
  s := replace(s, 'Best Spoken English Institute', 'Spoken English Training');
  s := replace(s, 'Best Full Stack Java Training', 'Full Stack Java Training');
  s := replace(s, 'Best Digital Marketing Course', 'Digital Marketing Course');
  s := replace(s, 'Best Cyber Security Institute', 'Cyber Security Training');
  s := replace(s, 'Best cyber security training', 'Cyber security training');
  s := replace(s, 'Best Spoken English training', 'Spoken English training');
  s := replace(s, 'Best Data Analytics Training', 'Data Analytics Training');
  s := replace(s, 'Best data analytics training', 'Data analytics training');
  s := replace(s, 'Best Google Cloud Institute', 'Google Cloud Training');
  s := replace(s, 'Best Azure Devops Institute', 'Azure Devops Training');
  s := replace(s, 'Best UI/UX Design training', 'UI/UX Design training');
  s := replace(s, 'Best Google Cloud training', 'Google Cloud training');
  s := replace(s, 'Best Azure DevOps training', 'Azure DevOps training');
  s := replace(s, 'Best Data Science Training', 'Data Science Training');
  s := replace(s, 'Best Azure Cloud Institute', 'Azure Cloud Training');
  s := replace(s, 'Best Salesforce Institute', 'Salesforce Training');
  s := replace(s, 'Best Certification Course', 'Certification Course');
  s := replace(s, 'Best AWS DevOps training', 'AWS DevOps training');
  s := replace(s, 'Best MS Office Institute', 'MS Office Training');
  s := replace(s, 'Best Data Science Course', 'Data Science Course');
  s := replace(s, 'Best Tally ERP training', 'Tally ERP training');
  s := replace(s, 'Best MS Office training', 'MS Office training');
  s := replace(s, 'Best Big Data training', 'Big Data training');
  s := replace(s, 'Best Power BI training', 'Power BI training');
  s := replace(s, U&'Best SAP\00a0Fico Training', U&'SAP\00a0Fico Training');
  s := replace(s, 'Best SAP Fico Training', 'SAP Fico Training');
  s := replace(s, 'Best Python Institute', 'Python Training');
  s := replace(s, 'Best DevOps training', 'DevOps training');
  s := replace(s, 'Best Python training', 'Python training');
  s := replace(s, 'Best Tally Institute', 'Tally Training');
  s := replace(s, 'Best Linux Institute', 'Linux Training');
  s := replace(s, 'Best Azure training', 'Azure training');
  s := replace(s, 'Top DevOps Training', 'DevOps Training');
  s := replace(s, 'Best Linux Training', 'Linux Training');
  s := replace(s, 'Best Java Institute', 'Java Training');
  s := replace(s, 'Best AWS Institutes', 'AWS Training');
  s := replace(s, 'Best Java training', 'Java training');
  s := replace(s, 'Best SQL training', 'SQL training');
  s := replace(s, 'Best AWS training', 'AWS training');
  s := replace(s, 'top IT companies', 'IT companies');
  s := replace(s, 'Best AWS Course', 'AWS Course');
  s := replace(s, 'Best AI Course', 'AI Course');
  RETURN s;
END
$fn$;

-- ── STEP 1: PREVIEW (read-only) — old and new text side by side ────────────
SELECT 'PageSeo' AS tbl, "pageSlug" AS key, col, old, public.coss_claims_fix_20261003(old) AS new
FROM "PageSeo", LATERAL (VALUES ('metaTitle', "metaTitle"), ('metaDescription', "metaDescription"), ('ogTitle', "ogTitle"), ('ogDescription', "ogDescription")) v(col, old)
WHERE old IS DISTINCT FROM public.coss_claims_fix_20261003(old)
UNION ALL
SELECT 'Course', id || ' ' || slug, col, old, public.coss_claims_fix_20261003(old)
FROM "Course", LATERAL (VALUES ('title', title), ('excerpt', excerpt), ('description', description), ('seoTitle', "seoTitle"), ('seoDesc', "seoDesc")) v(col, old)
WHERE old IS DISTINCT FROM public.coss_claims_fix_20261003(old)
UNION ALL
SELECT 'Course', id || ' ' || slug, 'highlights[' || i || ']', x, public.coss_claims_fix_20261003(x)
FROM "Course", unnest(highlights) WITH ORDINALITY AS u(x, i)
WHERE x IS DISTINCT FROM public.coss_claims_fix_20261003(x)
UNION ALL
SELECT 'BlogPost', id || ' ' || slug, col, old, public.coss_claims_fix_20261003(old)
FROM "BlogPost", LATERAL (VALUES ('title', title), ('excerpt', excerpt), ('seoTitle', "seoTitle"), ('seoDesc', "seoDesc")) v(col, old)
WHERE old IS DISTINCT FROM public.coss_claims_fix_20261003(old)
ORDER BY 1, 2, 3;

-- Row counts the UPDATEs in STEP 2 will touch (compare with the expected counts above):
SELECT 'PageSeo' AS tbl, count(*) FROM "PageSeo" WHERE "metaTitle" IS DISTINCT FROM public.coss_claims_fix_20261003("metaTitle")
   OR "metaDescription" IS DISTINCT FROM public.coss_claims_fix_20261003("metaDescription")
   OR "ogTitle" IS DISTINCT FROM public.coss_claims_fix_20261003("ogTitle")
   OR "ogDescription" IS DISTINCT FROM public.coss_claims_fix_20261003("ogDescription")
UNION ALL
SELECT 'Course', count(*) FROM "Course" WHERE "title" IS DISTINCT FROM public.coss_claims_fix_20261003("title")
   OR "excerpt" IS DISTINCT FROM public.coss_claims_fix_20261003("excerpt")
   OR "description" IS DISTINCT FROM public.coss_claims_fix_20261003("description")
   OR "seoTitle" IS DISTINCT FROM public.coss_claims_fix_20261003("seoTitle")
   OR "seoDesc" IS DISTINCT FROM public.coss_claims_fix_20261003("seoDesc")
   OR "highlights" IS DISTINCT FROM ARRAY(SELECT public.coss_claims_fix_20261003(x) FROM unnest("highlights") WITH ORDINALITY AS u(x, i) ORDER BY i)
UNION ALL
SELECT 'BlogPost', count(*) FROM "BlogPost" WHERE "title" IS DISTINCT FROM public.coss_claims_fix_20261003("title")
   OR "excerpt" IS DISTINCT FROM public.coss_claims_fix_20261003("excerpt")
   OR "seoTitle" IS DISTINCT FROM public.coss_claims_fix_20261003("seoTitle")
   OR "seoDesc" IS DISTINCT FROM public.coss_claims_fix_20261003("seoDesc");

-- Expected: 0 rows — no description the fix makes longer AND over 160 characters.
SELECT tbl, key, col, length(old) AS old_len, length(new) AS new_len FROM (
  SELECT 'PageSeo' AS tbl, "pageSlug" AS key, col, old, public.coss_claims_fix_20261003(old) AS new
  FROM "PageSeo", LATERAL (VALUES ('metaDescription', "metaDescription"), ('ogDescription', "ogDescription")) v(col, old)
  UNION ALL
  SELECT 'Course', slug, 'seoDesc', "seoDesc", public.coss_claims_fix_20261003("seoDesc") FROM "Course"
  UNION ALL
  SELECT 'BlogPost', slug, 'seoDesc', "seoDesc", public.coss_claims_fix_20261003("seoDesc") FROM "BlogPost"
) d
WHERE length(new) > 160 AND length(new) > length(old);

-- ── STEP 2: UPDATE … RETURNING (one transaction) ───────────────────────────
BEGIN;

UPDATE "PageSeo" SET
  "metaTitle" = public.coss_claims_fix_20261003("metaTitle"),
  "metaDescription" = public.coss_claims_fix_20261003("metaDescription"),
  "ogTitle" = public.coss_claims_fix_20261003("ogTitle"),
  "ogDescription" = public.coss_claims_fix_20261003("ogDescription"),
  "updatedAt" = now()
WHERE "metaTitle" IS DISTINCT FROM public.coss_claims_fix_20261003("metaTitle")
   OR "metaDescription" IS DISTINCT FROM public.coss_claims_fix_20261003("metaDescription")
   OR "ogTitle" IS DISTINCT FROM public.coss_claims_fix_20261003("ogTitle")
   OR "ogDescription" IS DISTINCT FROM public.coss_claims_fix_20261003("ogDescription")
RETURNING 'PageSeo' AS tbl, "pageSlug", "metaTitle", "metaDescription", "ogTitle", "ogDescription";

UPDATE "Course" SET
  "title" = public.coss_claims_fix_20261003("title"),
  "excerpt" = public.coss_claims_fix_20261003("excerpt"),
  "description" = public.coss_claims_fix_20261003("description"),
  "seoTitle" = public.coss_claims_fix_20261003("seoTitle"),
  "seoDesc" = public.coss_claims_fix_20261003("seoDesc"),
  highlights = ARRAY(SELECT public.coss_claims_fix_20261003(x) FROM unnest(highlights) WITH ORDINALITY AS u(x, i) ORDER BY i),
  "updatedAt" = now()
WHERE "title" IS DISTINCT FROM public.coss_claims_fix_20261003("title")
   OR "excerpt" IS DISTINCT FROM public.coss_claims_fix_20261003("excerpt")
   OR "description" IS DISTINCT FROM public.coss_claims_fix_20261003("description")
   OR "seoTitle" IS DISTINCT FROM public.coss_claims_fix_20261003("seoTitle")
   OR "seoDesc" IS DISTINCT FROM public.coss_claims_fix_20261003("seoDesc")
   OR "highlights" IS DISTINCT FROM ARRAY(SELECT public.coss_claims_fix_20261003(x) FROM unnest("highlights") WITH ORDINALITY AS u(x, i) ORDER BY i)
RETURNING 'Course' AS tbl, id, slug, "seoDesc", excerpt;

UPDATE "BlogPost" SET
  "title" = public.coss_claims_fix_20261003("title"),
  "excerpt" = public.coss_claims_fix_20261003("excerpt"),
  "seoTitle" = public.coss_claims_fix_20261003("seoTitle"),
  "seoDesc" = public.coss_claims_fix_20261003("seoDesc"),
  "updatedAt" = now()
WHERE "title" IS DISTINCT FROM public.coss_claims_fix_20261003("title")
   OR "excerpt" IS DISTINCT FROM public.coss_claims_fix_20261003("excerpt")
   OR "seoTitle" IS DISTINCT FROM public.coss_claims_fix_20261003("seoTitle")
   OR "seoDesc" IS DISTINCT FROM public.coss_claims_fix_20261003("seoDesc")
RETURNING 'BlogPost' AS tbl, id, slug, "seoDesc", excerpt;

COMMIT;

-- ── STEP 3: VERIFY (read-only) ──────────────────────────────────────────────
-- Expected: PageSeo 0, Course 0, BlogPost 0 (nothing left that the fix would still change).
SELECT 'PageSeo' AS tbl, count(*) FROM "PageSeo" WHERE "metaTitle" IS DISTINCT FROM public.coss_claims_fix_20261003("metaTitle")
   OR "metaDescription" IS DISTINCT FROM public.coss_claims_fix_20261003("metaDescription")
   OR "ogTitle" IS DISTINCT FROM public.coss_claims_fix_20261003("ogTitle")
   OR "ogDescription" IS DISTINCT FROM public.coss_claims_fix_20261003("ogDescription")
UNION ALL
SELECT 'Course', count(*) FROM "Course" WHERE "title" IS DISTINCT FROM public.coss_claims_fix_20261003("title")
   OR "excerpt" IS DISTINCT FROM public.coss_claims_fix_20261003("excerpt")
   OR "description" IS DISTINCT FROM public.coss_claims_fix_20261003("description")
   OR "seoTitle" IS DISTINCT FROM public.coss_claims_fix_20261003("seoTitle")
   OR "seoDesc" IS DISTINCT FROM public.coss_claims_fix_20261003("seoDesc")
   OR "highlights" IS DISTINCT FROM ARRAY(SELECT public.coss_claims_fix_20261003(x) FROM unnest("highlights") WITH ORDINALITY AS u(x, i) ORDER BY i)
UNION ALL
SELECT 'BlogPost', count(*) FROM "BlogPost" WHERE "title" IS DISTINCT FROM public.coss_claims_fix_20261003("title")
   OR "excerpt" IS DISTINCT FROM public.coss_claims_fix_20261003("excerpt")
   OR "seoTitle" IS DISTINCT FROM public.coss_claims_fix_20261003("seoTitle")
   OR "seoDesc" IS DISTINCT FROM public.coss_claims_fix_20261003("seoDesc");

-- ── STEP 4: drop the helper ─────────────────────────────────────────────────
DROP FUNCTION IF EXISTS public.coss_claims_fix_20261003(text);

-- Then tell Claude "SQL done": the full production sweep is re-run
-- (node scripts/audit-rendered-claims.mjs) and before/after counts reported.
