-- 2026-10-08 READ-ONLY scan before deleting unused CSS (item 14). Run in the Supabase SQL Editor
-- (production). It only reads (SELECT); nothing changes. Not run by Claude.
--
-- globals.css has 266 class names that no code and no rendered page uses. Before deleting them,
-- this checks the text stored in the database (drafts included) for any of those names.
-- The result lists only the names it finds (with the table.column and the number of rows).
-- An empty result ("Success. No rows returned") means none are used: tell Claude Code "no rows".
-- Otherwise copy the result grid to Claude Code; those classes are kept.

WITH candidates(cls) AS (
  SELECT unnest(ARRAY[
    'theme-toggle',
    'topbar-inner',
    'topbar-left',
    'topbar-right',
    'topbar-phone',
    'topbar-email',
    'topbar-pay',
    'sticky-chrome',
    'site-header',
    'header-scrolled',
    'header-topbar',
    'header-topbar-inner',
    'header-topbar-left',
    'header-topbar-right',
    'htb-item',
    'htb-phone',
    'htb-icon',
    'htb-star',
    'htb-sep',
    'htb-badge',
    'header-inner',
    'desktop-nav',
    'nav-item',
    'nav-item-icon',
    'nav-chevron',
    'nav-dropdown-wrap',
    'nav-cta-group',
    'nav-demo',
    'nav-enroll',
    'nav-dropdown',
    'nav-dropdown-header',
    'dropdown-item',
    'hamburger',
    'mobile-header-actions',
    'mobile-phone-btn',
    'mobile-enroll-btn',
    'mobile-nav--open',
    'mobile-phone-strip',
    'mobile-nav-item',
    'mobile-nav-item-inner',
    'mobile-acc-label',
    'mob-chevron',
    'mob-acc-body',
    'mob-acc-body--open',
    'mobile-sub-item',
    'mobile-nav-ctas',
    'mobile-nav-demo',
    'mobile-nav-enroll',
    'hero-section',
    'hero-wave-lines',
    'hero-bg-sweep',
    'hero-orb-right',
    'hero-orb-left',
    'hero-inner',
    'hero-badge',
    'hero-badge-icon',
    'hero-badge-accent',
    'hero-title',
    'hero-title-white',
    'hero-title-orange',
    'hero-title-blue',
    'hero-desc',
    'hero-btns',
    'btn-outline-white',
    'btn-outline-dark',
    'hero-trust-row',
    'hero-trust-item',
    'hero-trust-icon',
    'hero-trust-item-orange',
    'hero-trust-item-purple',
    'hero-trust-item-blue',
    'hero-trust-item-emerald',
    'hero-trust-value',
    'hero-trust-label',
    'hero-laptop-parallax',
    'hero-laptop-float',
    'hero-laptop-img',
    'hero-ring',
    'hero-ring-outer',
    'hero-ring-inner',
    'hero-cat-tile-wrap',
    'hero-cat-tile',
    'hero-cat-tile-icon',
    'hero-cat-tile-label',
    'hero-cat-tile-1',
    'hero-cat-tile-2',
    'hero-cat-tile-3',
    'hero-cat-tile-4',
    'hero-cat-tile-5',
    'hero-cat-tile-6',
    'enroll-form-section',
    'stats-bar',
    'stats-inner',
    'stat-number',
    'stat-label',
    'section-light',
    'section-dark',
    'section-white',
    'section-inner',
    'section-header',
    'section-tag',
    'section-title',
    'section-subtitle',
    'course-card',
    'course-card-img',
    'course-card-body',
    'course-card-more',
    'why-grid',
    'why-card',
    'why-icon',
    'two-col',
    'check-list',
    'company-grid',
    'company-chip',
    'testimonial-grid',
    'testimonial-card',
    'testimonial-author',
    'author-avatar',
    'author-name',
    'blog-date-day',
    'blog-date-mon',
    'about-grid',
    'about-why-box',
    'about-why-item',
    'about-why-check',
    'about-why-label',
    'about-why-desc',
    'cta-section',
    'cta-btns',
    'btn-white',
    'btn-white-outline',
    'center-btn',
    'wp-shortcode',
    'enroll-hero',
    'enroll-hero-glow',
    'enroll-hero-dots',
    'enroll-hero-inner',
    'enroll-breadcrumb',
    'enroll-hero-title',
    'enroll-hero-accent',
    'enroll-hero-sub',
    'enroll-trust-row',
    'enroll-trust-pill',
    'enroll-body',
    'enroll-body-inner',
    'enroll-form-col',
    'enroll-form-label-tag',
    'enroll-form-heading',
    'enroll-form-sub',
    'enroll-social-proof',
    'enroll-avatars',
    'enroll-avatar',
    'enroll-social-text',
    'enroll-assurance',
    'enroll-assurance-item',
    'enroll-info-col',
    'enroll-why-box',
    'enroll-why-title',
    'enroll-why-grid',
    'enroll-why-card',
    'enroll-why-icon',
    'enroll-why-card-title',
    'enroll-why-card-desc',
    'enroll-branches',
    'enroll-branches-title',
    'enroll-branch-cards',
    'enroll-branch-card',
    'enroll-branch-name',
    'enroll-branch-addr',
    'enroll-contact-row',
    'enroll-contact-link',
    'enroll-contact-email',
    'enroll-contact-sep',
    'ef-optional',
    'ef-select',
    'ef-textarea',
    'hero-trust',
    'hero-trust-check',
    'hero-trust-sep',
    'hero-cta-primary',
    'hero-cta-secondary',
    'course-card-v2',
    'course-card-v2-banner',
    'course-card-v2-icon',
    'course-card-v2-body',
    'course-card-v2-title',
    'course-card-v2-desc',
    'course-card-v2-pills',
    'course-pill',
    'course-card-v2-tags',
    'course-card-v2-cta',
    'why-grid-v2',
    'why-card-v2',
    'why-icon-v2',
    'why-card-v2-title',
    'why-card-v2-desc',
    'testimonial-card-v2',
    'testimonial-header',
    'css-stars',
    'testimonial-text',
    'testimonial-course-badge',
    'cta-pattern',
    'cta-eyebrow',
    'cta-headline',
    'cta-sub',
    'stat-item',
    'wa-panel-body',
    'wa-bubble',
    'wa-bubble-agent',
    'wa-start-btn',
    'wcu-section',
    'wcu-dot-grid',
    'wcu-wave',
    'wcu-heading',
    'wcu-stats-bar',
    'wcu-stat-item',
    'wcu-stat-divider',
    'wcu-stat-icon-wrap',
    'wcu-stat-number',
    'wcu-stat-label',
    'wcu-cards-layout',
    'wcu-featured-card',
    'wcu-feat-icon-wrap',
    'wcu-feat-illustration',
    'wcu-feat-svg',
    'wcu-feat-title',
    'wcu-feat-desc',
    'wcu-feat-cta',
    'wcu-orange-bar',
    'wcu-right-grid',
    'wcu-small-card',
    'wcu-small-icon-wrap',
    'wcu-small-title',
    'wcu-small-desc',
    'wcu-watermark',
    'wcu-banner',
    'wcu-banner-left',
    'wcu-banner-rocket',
    'wcu-banner-title',
    'wcu-banner-sub',
    'wcu-banner-btns',
    'wcu-banner-btn-primary',
    'wcu-banner-btn-outline',
    'ann-bar',
    'ann-bar__inner',
    'ann-bar__text',
    'ann-bar__cta',
    'ann-bar__close',
    'scrollbar-hide',
    'tab-icon-home',
    'tab-label-home',
    'tab-icon-courses',
    'tab-label-courses',
    'tab-icon-batches',
    'tab-label-batches',
    'tab-icon-reviews',
    'tab-label-reviews',
    'tab-underline-home',
    'tab-underline-courses',
    'tab-underline-batches',
    'tab-underline-reviews',
    'cat-bg-kenburns',
    'cat-bg-orb',
    'cat-bg-orb-1',
    'cat-bg-orb-2',
    'cat-bg-header-veil'
  ]::text[])
),
texts(src, t) AS (
  SELECT 'BlogPost.content', "content"::text FROM "BlogPost"
  UNION ALL
  SELECT 'BlogPost.excerpt', "excerpt"::text FROM "BlogPost"
  UNION ALL
  SELECT 'ContentBlock.title', "title"::text FROM "ContentBlock"
  UNION ALL
  SELECT 'ContentBlock.body', "body"::text FROM "ContentBlock"
  UNION ALL
  SELECT 'Course.description', "description"::text FROM "Course"
  UNION ALL
  SELECT 'Course.excerpt', "excerpt"::text FROM "Course"
  UNION ALL
  SELECT 'Course.highlights', "highlights"::text FROM "Course"
  UNION ALL
  SELECT 'CourseCategory.description', "description"::text FROM "CourseCategory"
  UNION ALL
  SELECT 'Job.description', "description"::text FROM "Job"
  UNION ALL
  SELECT 'Trainer.bio', "bio"::text FROM "Trainer"
  UNION ALL
  SELECT 'Testimonial.quote', "quote"::text FROM "Testimonial"
  UNION ALL
  SELECT 'HomepageSettings.heroHeadline', "heroHeadline"::text FROM "HomepageSettings"
  UNION ALL
  SELECT 'HomepageSettings.heroSubtext', "heroSubtext"::text FROM "HomepageSettings"
  UNION ALL
  SELECT 'HomepageSettings.announcementText', "announcementText"::text FROM "HomepageSettings"
  UNION ALL
  SELECT 'HomepageSettings.featuredSectionSubtext', "featuredSectionSubtext"::text FROM "HomepageSettings"
  UNION ALL
  SELECT 'AnnouncementBar.text', "text"::text FROM "AnnouncementBar"
  UNION ALL
  SELECT 'PageSeo.schemaMarkup', "schemaMarkup"::text FROM "PageSeo"
  UNION ALL
  SELECT 'PageSeo.schemaOverride', "schemaOverride"::text FROM "PageSeo"
  UNION ALL
  SELECT 'SiteSettings.schemaOrgOverride', "schemaOrgOverride"::text FROM "SiteSettings"
  UNION ALL
  SELECT 'SiteSettings.schemaWebSiteOverride', "schemaWebSiteOverride"::text FROM "SiteSettings"
  UNION ALL
  SELECT 'SiteSettings.schemaDilsOverride', "schemaDilsOverride"::text FROM "SiteSettings"
  UNION ALL
  SELECT 'SiteSettings.schemaAmeerpetOverride', "schemaAmeerpetOverride"::text FROM "SiteSettings"
)
SELECT c.cls AS class_name, t.src AS found_in, count(*) AS rows_with_it
FROM candidates c
JOIN texts t ON t.t ~ ('(^|[^A-Za-z0-9_-])' || c.cls || '([^A-Za-z0-9_-]|$)')
GROUP BY c.cls, t.src
ORDER BY c.cls, t.src;
