-- ═══════════════════════════════════════════════════════════════════════════
-- DEV DATABASE ONLY — never run on production
-- ═══════════════════════════════════════════════════════════════════════════
-- 2026-10-04 dev catch-up: brings the local dev Postgres (.env.development.local) up to
-- prisma/schema.prisma. Production already has these changes (applied over time via the
-- manual migrations in this folder); the dev DB never got them, so local builds failed
-- (e.g. "The table public.Trainer does not exist").
--
-- Source: npx prisma migrate diff --from-schema-datasource (dev DB) --to-schema-datamodel
--   prisma/schema.prisma --script   (read-only; prints SQL, applies nothing)
-- Kept: 10 statements that only ADD (tables, columns, enum types/values, indexes, FKs).
-- Excluded: 0 statements that would DROP or ALTER existing dev data (listed at the
--   bottom, commented out). They mean the dev DB has something the schema doesn't; review them.
--
-- Adds: tables 2, columns 5, enum types 0, enum values 1, indexes 4, foreign keys 0, other 1.
-- ALTERs an existing column's definition only (no rows change; a DEFAULT affects future inserts):
--   ALTER TABLE "HomepageSettings" ALTER COLUMN "stat4Value" SET DEFAULT '50+';
-- Enum values added: CONTENT_SEO_MANAGER. ADD VALUE inside a transaction needs PostgreSQL 12+.
-- No later statement uses a new value (no DEFAULT/UPDATE/INSERT with it), so one transaction is safe.
-- Local dev server: PostgreSQL 16.13 (server_version_num 160013).
--
-- Each change and the production migration it mirrors:
--   AdminRole + CONTENT_SEO_MANAGER   2026-09-25-add-content-seo-manager-role.sql (applied by hand 25 Sep, record added 4 Oct)
--   CorporateLead.requirements        2026-09-26-corporate-lead-requirements.sql
--   HomepageSettings.stat4Value       2026-08-25-fix-stat4-default.sql  (old schema default "200+")
--   Lead.consentAt, jobCompany, jobId, jobTitle + Lead_jobId_idx
--                                     2026-08-30-lead-job-application-fields.sql
--   Trainer + index                   2026-09-15-add-trainer.sql
--   SocialPost + index                2026-09-15-add-social-post.sql (+ later SocialPost changes)
--   Batch_status_centre_idx           2026-09-17-add-batch-status-centre-index.sql
--
-- Run with the dev URL, e.g. from the project root in Git Bash:
--   npx dotenv-cli -e .env.development.local -- npx prisma db execute --file prisma/migrations/manual/dev-catchup-2026-10-04.sql --schema prisma/schema.prisma
-- (dotenv-cli sets the dev URL first, so Prisma's own .env loading can't point it at production.)
-- Then run the two VERIFY queries below in psql or any client on the dev DB.

BEGIN;

-- AlterEnum
ALTER TYPE "AdminRole" ADD VALUE 'CONTENT_SEO_MANAGER';

-- AlterTable
ALTER TABLE "CorporateLead" ADD COLUMN     "requirements" TEXT;

-- AlterTable
ALTER TABLE "HomepageSettings" ALTER COLUMN "stat4Value" SET DEFAULT '50+';

-- AlterTable
ALTER TABLE "Lead" ADD COLUMN     "consentAt" TIMESTAMP(3),
ADD COLUMN     "jobCompany" TEXT,
ADD COLUMN     "jobId" TEXT,
ADD COLUMN     "jobTitle" TEXT;

-- CreateTable
CREATE TABLE "Trainer" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "category" TEXT,
    "skills" TEXT,
    "teaches" TEXT,
    "startYear" INTEGER,
    "bio" TEXT,
    "photoUrl" TEXT,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "isVisible" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Trainer_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SocialPost" (
    "id" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "channels" TEXT NOT NULL,
    "courseId" TEXT,
    "hook" TEXT,
    "hashtags" TEXT,
    "imageUrl" TEXT,
    "imageAltText" TEXT,
    "linkUrl" TEXT,
    "scheduledFor" TIMESTAMP(3) NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'draft',
    "bufferPostIds" TEXT,
    "attemptCount" INTEGER NOT NULL DEFAULT 0,
    "lastError" TEXT,
    "sentAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SocialPost_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "Trainer_isVisible_sortOrder_idx" ON "Trainer"("isVisible", "sortOrder");

-- CreateIndex
CREATE INDEX "SocialPost_status_scheduledFor_idx" ON "SocialPost"("status", "scheduledFor");

-- CreateIndex
CREATE INDEX "Batch_status_centre_idx" ON "Batch"("status", "centre");

-- CreateIndex
CREATE INDEX "Lead_jobId_idx" ON "Lead"("jobId");

COMMIT;

-- ── VERIFY (read-only) ──────────────────────────────────────────────────────
-- 1. The tables and columns this file adds: expected present = true on every row.
SELECT e.tbl, e.col, (c.column_name IS NOT NULL) AS present
FROM (VALUES
  ('Lead', 'jobId'),
  ('Lead', 'jobTitle'),
  ('Lead', 'jobCompany'),
  ('Lead', 'consentAt'),
  ('CorporateLead', 'requirements'),
  ('Trainer', 'id'),
  ('Trainer', 'name'),
  ('Trainer', 'title'),
  ('Trainer', 'category'),
  ('Trainer', 'skills'),
  ('Trainer', 'teaches'),
  ('Trainer', 'startYear'),
  ('Trainer', 'bio'),
  ('Trainer', 'photoUrl'),
  ('Trainer', 'sortOrder'),
  ('Trainer', 'isVisible'),
  ('Trainer', 'createdAt'),
  ('Trainer', 'updatedAt'),
  ('SocialPost', 'id'),
  ('SocialPost', 'content'),
  ('SocialPost', 'channels'),
  ('SocialPost', 'courseId'),
  ('SocialPost', 'hook'),
  ('SocialPost', 'hashtags'),
  ('SocialPost', 'imageUrl'),
  ('SocialPost', 'imageAltText'),
  ('SocialPost', 'linkUrl'),
  ('SocialPost', 'scheduledFor'),
  ('SocialPost', 'status'),
  ('SocialPost', 'bufferPostIds'),
  ('SocialPost', 'attemptCount'),
  ('SocialPost', 'lastError'),
  ('SocialPost', 'sentAt'),
  ('SocialPost', 'createdAt'),
  ('SocialPost', 'updatedAt')
) AS e(tbl, col)
LEFT JOIN information_schema.columns c
  ON c.table_schema = 'public' AND c.table_name = e.tbl AND c.column_name = e.col
ORDER BY 1, 2;

-- 2. Every table and column in schema.prisma: expected 0 rows (nothing missing).
SELECT e.tbl, e.col AS missing_column
FROM (VALUES
  ('Lead', 'id'),
  ('Lead', 'name'),
  ('Lead', 'phone'),
  ('Lead', 'email'),
  ('Lead', 'course'),
  ('Lead', 'branch'),
  ('Lead', 'formType'),
  ('Lead', 'status'),
  ('Lead', 'message'),
  ('Lead', 'utmSource'),
  ('Lead', 'utmMedium'),
  ('Lead', 'utmCampaign'),
  ('Lead', 'referrer'),
  ('Lead', 'landingPage'),
  ('Lead', 'submitPath'),
  ('Lead', 'deviceType'),
  ('Lead', 'jobId'),
  ('Lead', 'jobTitle'),
  ('Lead', 'jobCompany'),
  ('Lead', 'consentAt'),
  ('Lead', 'createdAt'),
  ('CorporateLead', 'id'),
  ('CorporateLead', 'companyName'),
  ('CorporateLead', 'contactPerson'),
  ('CorporateLead', 'phone'),
  ('CorporateLead', 'email'),
  ('CorporateLead', 'trainingDomain'),
  ('CorporateLead', 'employeeCount'),
  ('CorporateLead', 'requirements'),
  ('CorporateLead', 'status'),
  ('CorporateLead', 'createdAt'),
  ('PageSeo', 'id'),
  ('PageSeo', 'pageSlug'),
  ('PageSeo', 'pageTitle'),
  ('PageSeo', 'metaTitle'),
  ('PageSeo', 'metaDescription'),
  ('PageSeo', 'ogTitle'),
  ('PageSeo', 'ogDescription'),
  ('PageSeo', 'ogImage'),
  ('PageSeo', 'canonicalUrl'),
  ('PageSeo', 'noIndex'),
  ('PageSeo', 'noFollow'),
  ('PageSeo', 'schemaMarkup'),
  ('PageSeo', 'schemaEnabled'),
  ('PageSeo', 'schemaOverride'),
  ('PageSeo', 'focusKeyword'),
  ('PageSeo', 'keywords'),
  ('PageSeo', 'sitemapInclude'),
  ('PageSeo', 'sitemapPriority'),
  ('PageSeo', 'changeFreq'),
  ('PageSeo', 'updatedAt'),
  ('PageSeo', 'createdAt'),
  ('SeoSettings', 'id'),
  ('SeoSettings', 'googleAnalyticsId'),
  ('SeoSettings', 'googleSearchConsoleId'),
  ('SeoSettings', 'defaultOgImage'),
  ('SeoSettings', 'siteTitle'),
  ('SeoSettings', 'twitterHandle'),
  ('SeoSettings', 'robotsTxt'),
  ('SeoSettings', 'updatedAt'),
  ('AnnouncementBar', 'id'),
  ('AnnouncementBar', 'enabled'),
  ('AnnouncementBar', 'text'),
  ('AnnouncementBar', 'ctaLabel'),
  ('AnnouncementBar', 'ctaUrl'),
  ('AnnouncementBar', 'bgColor'),
  ('AnnouncementBar', 'textColor'),
  ('AnnouncementBar', 'updatedAt'),
  ('AdminUser', 'id'),
  ('AdminUser', 'name'),
  ('AdminUser', 'email'),
  ('AdminUser', 'passwordHash'),
  ('AdminUser', 'role'),
  ('AdminUser', 'permissions'),
  ('AdminUser', 'isActive'),
  ('AdminUser', 'createdAt'),
  ('AdminUser', 'updatedAt'),
  ('PushSubscription', 'id'),
  ('PushSubscription', 'adminUserId'),
  ('PushSubscription', 'endpoint'),
  ('PushSubscription', 'p256dh'),
  ('PushSubscription', 'auth'),
  ('PushSubscription', 'userAgent'),
  ('PushSubscription', 'createdAt'),
  ('CourseCategory', 'id'),
  ('CourseCategory', 'name'),
  ('CourseCategory', 'slug'),
  ('CourseCategory', 'description'),
  ('CourseCategory', 'icon'),
  ('CourseCategory', 'color'),
  ('CourseCategory', 'sortOrder'),
  ('CourseCategory', 'isLegacy'),
  ('CourseCategory', 'status'),
  ('CourseCategory', 'seoTitle'),
  ('CourseCategory', 'seoDesc'),
  ('CourseCategory', 'createdAt'),
  ('CourseCategory', 'updatedAt'),
  ('Course', 'id'),
  ('Course', 'title'),
  ('Course', 'slug'),
  ('Course', 'description'),
  ('Course', 'excerpt'),
  ('Course', 'category'),
  ('Course', 'duration'),
  ('Course', 'mode'),
  ('Course', 'level'),
  ('Course', 'price'),
  ('Course', 'originalPrice'),
  ('Course', 'badge'),
  ('Course', 'thumbnail'),
  ('Course', 'brochureUrl'),
  ('Course', 'syllabus'),
  ('Course', 'highlights'),
  ('Course', 'tools'),
  ('Course', 'status'),
  ('Course', 'featured'),
  ('Course', 'sortOrder'),
  ('Course', 'seoTitle'),
  ('Course', 'seoDesc'),
  ('Course', 'categoryId'),
  ('Course', 'categorySlug'),
  ('Course', 'urlType'),
  ('Course', 'createdAt'),
  ('Course', 'updatedAt'),
  ('BlogPost', 'id'),
  ('BlogPost', 'title'),
  ('BlogPost', 'slug'),
  ('BlogPost', 'excerpt'),
  ('BlogPost', 'content'),
  ('BlogPost', 'category'),
  ('BlogPost', 'tags'),
  ('BlogPost', 'thumbnail'),
  ('BlogPost', 'author'),
  ('BlogPost', 'authorRole'),
  ('BlogPost', 'readTime'),
  ('BlogPost', 'status'),
  ('BlogPost', 'featured'),
  ('BlogPost', 'views'),
  ('BlogPost', 'seoTitle'),
  ('BlogPost', 'seoDesc'),
  ('BlogPost', 'publishedAt'),
  ('BlogPost', 'createdAt'),
  ('BlogPost', 'updatedAt'),
  ('Job', 'id'),
  ('Job', 'title'),
  ('Job', 'slug'),
  ('Job', 'company'),
  ('Job', 'companyLogo'),
  ('Job', 'location'),
  ('Job', 'type'),
  ('Job', 'mode'),
  ('Job', 'category'),
  ('Job', 'experience'),
  ('Job', 'salary'),
  ('Job', 'description'),
  ('Job', 'skills'),
  ('Job', 'applyUrl'),
  ('Job', 'relatedCourseId'),
  ('Job', 'status'),
  ('Job', 'featured'),
  ('Job', 'expiresAt'),
  ('Job', 'postedAt'),
  ('Job', 'updatedAt'),
  ('Batch', 'id'),
  ('Batch', 'courseId'),
  ('Batch', 'batchName'),
  ('Batch', 'mode'),
  ('Batch', 'centre'),
  ('Batch', 'startDate'),
  ('Batch', 'endDate'),
  ('Batch', 'schedule'),
  ('Batch', 'totalSeats'),
  ('Batch', 'seatsAvailable'),
  ('Batch', 'trainer'),
  ('Batch', 'price'),
  ('Batch', 'status'),
  ('Batch', 'featured'),
  ('Batch', 'notes'),
  ('Batch', 'createdAt'),
  ('Batch', 'updatedAt'),
  ('Trainer', 'id'),
  ('Trainer', 'name'),
  ('Trainer', 'title'),
  ('Trainer', 'category'),
  ('Trainer', 'skills'),
  ('Trainer', 'teaches'),
  ('Trainer', 'startYear'),
  ('Trainer', 'bio'),
  ('Trainer', 'photoUrl'),
  ('Trainer', 'sortOrder'),
  ('Trainer', 'isVisible'),
  ('Trainer', 'createdAt'),
  ('Trainer', 'updatedAt'),
  ('LeadActivity', 'id'),
  ('LeadActivity', 'leadId'),
  ('LeadActivity', 'action'),
  ('LeadActivity', 'note'),
  ('LeadActivity', 'createdAt'),
  ('CallClick', 'id'),
  ('CallClick', 'createdAt'),
  ('CallClick', 'path'),
  ('CallClick', 'pageType'),
  ('CallClick', 'courseSlug'),
  ('CallClick', 'branchKey'),
  ('CallClick', 'phoneNumber'),
  ('CallClick', 'deviceType'),
  ('CallClick', 'referrer'),
  ('CallClick', 'utmSource'),
  ('CallClick', 'utmMedium'),
  ('CallClick', 'utmCampaign'),
  ('WhatsAppClick', 'id'),
  ('WhatsAppClick', 'createdAt'),
  ('WhatsAppClick', 'path'),
  ('WhatsAppClick', 'pageType'),
  ('WhatsAppClick', 'ctaType'),
  ('WhatsAppClick', 'courseSlug'),
  ('WhatsAppClick', 'branchKey'),
  ('WhatsAppClick', 'phoneNumber'),
  ('WhatsAppClick', 'hadPrefill'),
  ('WhatsAppClick', 'deviceType'),
  ('WhatsAppClick', 'referrer'),
  ('WhatsAppClick', 'utmSource'),
  ('WhatsAppClick', 'utmMedium'),
  ('WhatsAppClick', 'utmCampaign'),
  ('HomepageSettings', 'id'),
  ('HomepageSettings', 'heroHeadline'),
  ('HomepageSettings', 'heroSubtext'),
  ('HomepageSettings', 'heroCTAPrimaryText'),
  ('HomepageSettings', 'heroCTAPrimaryUrl'),
  ('HomepageSettings', 'heroCTASecondaryText'),
  ('HomepageSettings', 'heroCTASecondaryUrl'),
  ('HomepageSettings', 'stat1Value'),
  ('HomepageSettings', 'stat1Label'),
  ('HomepageSettings', 'stat2Value'),
  ('HomepageSettings', 'stat2Label'),
  ('HomepageSettings', 'stat3Value'),
  ('HomepageSettings', 'stat3Label'),
  ('HomepageSettings', 'stat4Value'),
  ('HomepageSettings', 'stat4Label'),
  ('HomepageSettings', 'announcementEnabled'),
  ('HomepageSettings', 'announcementText'),
  ('HomepageSettings', 'announcementUrl'),
  ('HomepageSettings', 'announcementBgColor'),
  ('HomepageSettings', 'featuredCourseIds'),
  ('HomepageSettings', 'featuredSectionTitle'),
  ('HomepageSettings', 'featuredSectionSubtext'),
  ('HomepageSettings', 'showFeaturedCourses'),
  ('HomepageSettings', 'showTestimonials'),
  ('HomepageSettings', 'showHiringPartners'),
  ('HomepageSettings', 'showStats'),
  ('HomepageSettings', 'updatedAt'),
  ('BranchSettings', 'id'),
  ('BranchSettings', 'branchKey'),
  ('BranchSettings', 'branchName'),
  ('BranchSettings', 'addressLine1'),
  ('BranchSettings', 'addressLine2'),
  ('BranchSettings', 'city'),
  ('BranchSettings', 'state'),
  ('BranchSettings', 'pincode'),
  ('BranchSettings', 'phone'),
  ('BranchSettings', 'email'),
  ('BranchSettings', 'latitude'),
  ('BranchSettings', 'longitude'),
  ('BranchSettings', 'workingHoursOpen'),
  ('BranchSettings', 'workingHoursClose'),
  ('BranchSettings', 'workingDays'),
  ('BranchSettings', 'mapEmbedUrl'),
  ('BranchSettings', 'serviceAreas'),
  ('BranchSettings', 'reviewCount'),
  ('BranchSettings', 'schemaEnabled'),
  ('BranchSettings', 'createdAt'),
  ('BranchSettings', 'updatedAt'),
  ('SiteSettings', 'id'),
  ('SiteSettings', 'ogImageUrl'),
  ('SiteSettings', 'logoUrl'),
  ('SiteSettings', 'logoLightUrl'),
  ('SiteSettings', 'faviconUrl'),
  ('SiteSettings', 'appleTouchUrl'),
  ('SiteSettings', 'courseOgDefault'),
  ('SiteSettings', 'primaryPhone'),
  ('SiteSettings', 'secondaryPhone'),
  ('SiteSettings', 'email'),
  ('SiteSettings', 'whatsappNumber'),
  ('SiteSettings', 'websiteUrl'),
  ('SiteSettings', 'facebookUrl'),
  ('SiteSettings', 'instagramUrl'),
  ('SiteSettings', 'linkedinUrl'),
  ('SiteSettings', 'youtubeUrl'),
  ('SiteSettings', 'twitterUrl'),
  ('SiteSettings', 'orgName'),
  ('SiteSettings', 'orgLegalName'),
  ('SiteSettings', 'orgFoundedYear'),
  ('SiteSettings', 'orgGstNumber'),
  ('SiteSettings', 'googleMapsUrl'),
  ('SiteSettings', 'schemaOrgOverride'),
  ('SiteSettings', 'schemaWebSiteOverride'),
  ('SiteSettings', 'schemaDilsOverride'),
  ('SiteSettings', 'schemaAmeerpetOverride'),
  ('SiteSettings', 'schemaOrgEnabled'),
  ('SiteSettings', 'schemaWebSiteEnabled'),
  ('SiteSettings', 'schemaDilsEnabled'),
  ('SiteSettings', 'schemaAmeerpetEnabled'),
  ('SiteSettings', 'updatedAt'),
  ('SiteSettings', 'createdAt'),
  ('MediaScanResult', 'id'),
  ('MediaScanResult', 'scannedAt'),
  ('MediaScanResult', 'totalImages'),
  ('MediaScanResult', 'brokenCount'),
  ('MediaScanResult', 'slowCount'),
  ('MediaScanResult', 'redirectCount'),
  ('MediaScanResult', 'results'),
  ('MediaScanResult', 'createdAt'),
  ('MediaAsset', 'id'),
  ('MediaAsset', 'publicId'),
  ('MediaAsset', 'altText'),
  ('MediaAsset', 'title'),
  ('MediaAsset', 'tags'),
  ('MediaAsset', 'createdAt'),
  ('MediaAsset', 'updatedAt'),
  ('Testimonial', 'id'),
  ('Testimonial', 'name'),
  ('Testimonial', 'jobTitle'),
  ('Testimonial', 'company'),
  ('Testimonial', 'quote'),
  ('Testimonial', 'rating'),
  ('Testimonial', 'photoUrl'),
  ('Testimonial', 'scope'),
  ('Testimonial', 'courseSlug'),
  ('Testimonial', 'visible'),
  ('Testimonial', 'sortOrder'),
  ('Testimonial', 'source'),
  ('Testimonial', 'reviewDate'),
  ('Testimonial', 'createdAt'),
  ('Testimonial', 'updatedAt'),
  ('HiringPartner', 'id'),
  ('HiringPartner', 'name'),
  ('HiringPartner', 'logoUrl'),
  ('HiringPartner', 'altText'),
  ('HiringPartner', 'website'),
  ('HiringPartner', 'isVisible'),
  ('HiringPartner', 'sortOrder'),
  ('HiringPartner', 'createdAt'),
  ('HiringPartner', 'updatedAt'),
  ('Redirect', 'id'),
  ('Redirect', 'source'),
  ('Redirect', 'destination'),
  ('Redirect', 'statusCode'),
  ('Redirect', 'isActive'),
  ('Redirect', 'createdAt'),
  ('Redirect', 'updatedAt'),
  ('ContentBlock', 'id'),
  ('ContentBlock', 'blockType'),
  ('ContentBlock', 'page'),
  ('ContentBlock', 'title'),
  ('ContentBlock', 'body'),
  ('ContentBlock', 'icon'),
  ('ContentBlock', 'metadata'),
  ('ContentBlock', 'gridStyle'),
  ('ContentBlock', 'isVisible'),
  ('ContentBlock', 'sortOrder'),
  ('ContentBlock', 'createdAt'),
  ('ContentBlock', 'updatedAt'),
  ('Notification', 'id'),
  ('Notification', 'type'),
  ('Notification', 'title'),
  ('Notification', 'body'),
  ('Notification', 'link'),
  ('Notification', 'targetRole'),
  ('Notification', 'targetUserId'),
  ('Notification', 'isRead'),
  ('Notification', 'createdAt'),
  ('NotificationPreference', 'id'),
  ('NotificationPreference', 'userId'),
  ('NotificationPreference', 'eventType'),
  ('NotificationPreference', 'inApp'),
  ('NotificationPreference', 'push'),
  ('NotificationPreference', 'email'),
  ('NotificationPreference', 'createdAt'),
  ('NotificationPreference', 'updatedAt'),
  ('SocialPost', 'id'),
  ('SocialPost', 'content'),
  ('SocialPost', 'channels'),
  ('SocialPost', 'courseId'),
  ('SocialPost', 'hook'),
  ('SocialPost', 'hashtags'),
  ('SocialPost', 'imageUrl'),
  ('SocialPost', 'imageAltText'),
  ('SocialPost', 'linkUrl'),
  ('SocialPost', 'scheduledFor'),
  ('SocialPost', 'status'),
  ('SocialPost', 'bufferPostIds'),
  ('SocialPost', 'attemptCount'),
  ('SocialPost', 'lastError'),
  ('SocialPost', 'sentAt'),
  ('SocialPost', 'createdAt'),
  ('SocialPost', 'updatedAt')
) AS e(tbl, col)
LEFT JOIN information_schema.columns c
  ON c.table_schema = 'public' AND c.table_name = e.tbl AND c.column_name = e.col
WHERE c.column_name IS NULL
ORDER BY 1, 2;
